### ISSUE TITLE
How to avoid training radomness?

### ISSUE THREAD

**Issue by zhaochenyang20** [huggingface/trl#1014]
I’m using the `trl.SFTTrainer` to fine-tune Vicuna, and I’m using the same data and parameters for fine-tuning. However, I’ve noticed that even after setting:

```
def set_seed(seed=42):
    # set seed for all possible avenues of stochasticity
    numpy.random.seed(seed=seed)
    random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True

training_args = TrainingArguments(
        report_to="none",
        output_dir=str(ckpt_path),
        do_eval=False,
        save_strategy="epoch",
        evaluation_strategy="no",
        num_train_epochs=training_epochs,
        seed=42,
    )
 ```
 
the fine-tuned checkpoint’s evaluation remains unstable. Every time I fine-tune with the same dataset, I get significantly different results. How can I ensure the stability of my fine-tuning?

I also tried this:

https://discuss.huggingface.co/t/fixing-the-random-seed-in-the-trainer-does-not-produce-the-same-results-across-runs/3442

But I was wrong even with this codes:

```
    def model_init():
        return AutoModelForCausalLM.from_pretrained(
             "/data/ckpts/huggingface/models/models--lmsys--vicuna-7b-v1.5/snapshots/de56c35b1763eaae20f4d60efd64af0a9091ebe5",
            device_map="auto",
            torch_dtype=torch.bfloat16,
            use_flash_attention_2=True,
        )

    training_args = TrainingArguments(
        report_to="none",
        output_dir=str(ckpt_path),
        do_eval=False,
        save_strategy="epoch",
        evaluation_strategy="no",
        num_train_epochs=training_epochs,
        seed=42,
    )
    trainer = SFTTrainer(
        model_init=model_init,
        args=training_args,
        train_dataset=mapped_dataset,
        dataset_text_field="text",
        data_collator=data_collator,
        max_seq_length=1500,
    )
```    
    
This would end in errors.

```
Traceback (most recent call last):
  File "/home/cyzhao/miniconda3/envs/prompt/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 261, in hf_raise_for_status
    response.raise_for_status()
  File "/home/cyzhao/miniconda3/envs/prompt/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/None/resolve/main/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cyzhao/miniconda3/envs/prompt/lib/python3.11/site-packages/transformers/utils/hub.py", line 429, in cached_file
    resolved_file = hf_hub_download(
                    ^^^^^^^^^^^^^^^^
  File "/home/cyzhao/miniconda3/envs/prompt/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/cyzhao/miniconda3/envs/prompt/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1346, in hf_hub_download
    raise head_call_error
  File "/home/cyzhao/miniconda3/envs/prompt/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1232, in hf_hub_download
    metadata = get_hf_file_metadata(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/cyzhao/miniconda3/envs/prompt/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/cyzhao/miniconda3/envs/prompt/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1608, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/home/cyzhao/miniconda3/envs/prompt/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 293, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-655b8b21-096243713e568c65194e1a69;8e4415fe-8069-43e1-8412-fdd028a8ebcd)

Repository Not Found for url: https://huggingface.co/None/resolve/main/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cyzhao/main/test_scripts/main.py", line 402, in <module>
    finetune_vicuna(
  File "/home/cyzhao/main/test_scripts/main.py", line 207, in finetune_vicuna
    trainer = SFTTrainer(
              ^^^^^^^^^^^
  File "/home/cyzhao/miniconda3/envs/prompt/lib/python3.11/site-packages/trl/trainer/sft_trainer.py", line 162, in __init__
    model = AutoModelForCausalLM.from_pretrained(model)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cyzhao/miniconda3/envs/prompt/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 487, in from_pretrained
    resolved_config_file = cached_file(
                           ^^^^^^^^^^^^
  File "/home/cyzhao/miniconda3/envs/prompt/lib/python3.11/site-packages/transformers/utils/hub.py", line 450, in cached_file
    raise EnvironmentError(
OSError: None is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
```

I think the init methods of SFTTrainer have some errors in the source codes. :sob:

**Comment by lvwerra** [comment]
It looks like this is not a valid model path: `"/data/ckpts/huggingface/models/models--lmsys--vicuna-7b-v1.5/snapshots/de56c35b1763eaae20f4d60efd64af0a9091ebe5"`. Are you trying to load from cache directly? If you replace it with this it should work I think: `"lmsys/vicuna-7b-v1.5"`.

**Comment by zhaochenyang20** [comment]
> It looks like this is not a valid model path: `"/data/ckpts/huggingface/models/models--lmsys--vicuna-7b-v1.5/snapshots/de56c35b1763eaae20f4d60efd64af0a9091ebe5"`. Are you trying to load from cache directly? If you replace it with this it should work I think: `"lmsys/vicuna-7b-v1.5"`.

@lvwerra Thanks for your reply. This is definitely a valid path. I am trying to load it from cache file.

**Comment by zhaochenyang20** [comment]
I can load it like this:

```
from vllm import LLM, SamplingParams

path = "/data/cyzhao/best_ckpt/SQuAD"

default = "/data/ckpts/huggingface/models/models--lmsys--vicuna-7b-v1.5/snapshots/de56c35b1763eaae20f4d60efd64af0a9091ebe5"

language_model = LLM(
    model=path,
    gpu_memory_utilization=0.5,
    tensor_parallel_size=1,
)
```

**Comment by lvwerra** [comment]
If you load with the original model path it should load the cache directly. I am not sure loading from the cache folder works in transformers. In any case it is a `transformers` issue and seems unrelated to randomness.

**Comment by zhaochenyang20** [comment]
Hmmmm. You see that:

```
OSError: None is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
```

At least I didn't pass in `None`. I pass in `"/data/ckpts/huggingface/models/models--lmsys--vicuna-7b-v1.5/snapshots/de56c35b1763eaae20f4d60efd64af0a9091ebe5"`.

**Comment by lvwerra** [comment]
Tagging @younesbelkada who is involved in the transformers FA2 integration.
