### ISSUE TITLE
ValueError: You are attempting to perform batched generation with padding_side='right'

### ISSUE THREAD

**Issue by pritishmishra703** [huggingface/trl#1018]
I'm encountering an error while fine-tuning the NousResearch/Yarn-Mistral-7b-128k model using the SFTTrainer. The error appears to be related to batched generation and the use of Flash Attention in Mistral. The specific error message suggests that setting padding_side='right' may lead to unexpected behavior.

## Error Details:

```
Traceback (most recent call last):
  File "train.py", line 183, in <module>
    main()
  File "train.py", line 176, in main
    trainer.train()
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 1556, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 1872, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 2739, in training_step
    loss = self.compute_loss(model, inputs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 2762, in compute_loss
    outputs = model(**inputs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/utils/operations.py", line 632, in forward
    return model_forward(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/utils/operations.py", line 620, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/peft/peft_model.py", line 931, in forward
    return self.base_model(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/peft/tuners/tuners_utils.py", line 94, in forward
    return self.model.forward(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/workspace/huggingface_home/modules/transformers_modules/NousResearch/Yarn-Mistral-7b-128k/d09f1f8ed437d61c1aff94c1beabee554843dcdd/modeling_mistral_yarn.py", line 1288, in forward
    outputs = self.model(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/huggingface_home/modules/transformers_modules/NousResearch/Yarn-Mistral-7b-128k/d09f1f8ed437d61c1aff94c1beabee554843dcdd/modeling_mistral_yarn.py", line 1125, in forward
    raise ValueError(
ValueError: You are attempting to perform batched generation with padding_side='right' this may lead to unexpected behaviour for Flash Attention version of Mistral. Make sure to  call `tokenizer.padding_side  = 'left'` before tokenizing the input.
```

Environment:

- Model: NousResearch/Yarn-Mistral-7b-128k
- transformers version: Latest from the main branch
- trl version: Latest from the main branch

**Comment by pritishmishra703** [comment]
Hey @lvwerra and @younesbelkada, could you please assist me with this? I apologize for tagging individually, but I really need a solution.

**Comment by edixiong** [comment]
hi @younesbelkada do you know where can I check if I can use left padding with flash attention 2? I do not see the error when using flash attention 2 + mistral now and I wonder if that means those combinations are ok. (Sorry for tagging)
