### ISSUE TITLE
Error when run `trl/examples/research_projects/stack_llama_2/scripts /sft_llama2.py`

### ISSUE THREAD

**Issue by yuqie** [huggingface/trl#1032]
I tried to run the stack_llama_2 project and encountered the following error.

The command I used:

```
accelerate launch sft_llama2.py --training_args.output_dir="sft"
```
The error is as folloing:
```
[2023-11-24 03:28:10,125] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/usr/local/lib/python3.10/dist-packages/trl/trainer/ppo_config.py:141: UserWarning: The `optimize_cuda_cache` arguement will be deprecated soon, please use `optimize_device_cache` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/tyro/_resolver.py:311: UserWarning: <class 'int'> does not match any type in Union: [<class 'float'>, <class 'NoneType'>]
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/tyro/_resolver.py:311: UserWarning: <class 'dict'> does not match any type in Union: [<class 'str'>, <class 'NoneType'>]
  warnings.warn(
Traceback (most recent call last):
  File "/home/trl/examples/research_projects/stack_llama_2/scripts/sft_llama2.py", line 69, in <module>
    script_args = tyro.cli(ScriptArguments)
  File "/usr/local/lib/python3.10/dist-packages/tyro/_cli.py", line 187, in cli
    output = _cli_impl(
  File "/usr/local/lib/python3.10/dist-packages/tyro/_cli.py", line 374, in _cli_impl
    parser_spec = _parsers.ParserSpecification.from_callable_or_type(
  File "/usr/local/lib/python3.10/dist-packages/tyro/_parsers.py", line 106, in from_callable_or_type
    field_out = handle_field(
  File "/usr/local/lib/python3.10/dist-packages/tyro/_parsers.py", line 320, in handle_field
    return ParserSpecification.from_callable_or_type(
  File "/usr/local/lib/python3.10/dist-packages/tyro/_parsers.py", line 106, in from_callable_or_type
    field_out = handle_field(
  File "/usr/local/lib/python3.10/dist-packages/tyro/_parsers.py", line 312, in handle_field
    if _fields.is_nested_type(field.type_or_callable, field.default):
  File "/usr/local/lib/python3.10/dist-packages/tyro/_unsafe_cache.py", line 33, in wrapped_f
    out = f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tyro/_fields.py", line 224, in is_nested_type
    _try_field_list_from_callable(typ, default_instance),
  File "/usr/local/lib/python3.10/dist-packages/tyro/_fields.py", line 348, in _try_field_list_from_callable
    return _field_list_from_dict(f, default_instance)
  File "/usr/local/lib/python3.10/dist-packages/tyro/_fields.py", line 734, in _field_list_from_dict
    if default_instance in MISSING_SINGLETONS or len(cast(dict, default_instance)) == 0:
TypeError: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 994, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 636, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', 'sft_llama2.py', '--training_args.output_dir=sft']' returned non-zero exit status 1.
```
It seems that line 69 of sft_llama2.py `script_args = tyro.cli(ScriptArguments)` leads to the error `TypeError: object of type 'NoneType' has no len()`. 
I am not familiar with tyro, could anyone help me with this problem? Any suggestions would be appreciated!

**Comment by lvwerra** [comment]
cc @vwxyzjn

**Comment by vwxyzjn** [comment]
Please update the `transformers` (`pip install --upgrade transformers`). This is a duplicate issue of https://github.com/huggingface/trl/pull/906#issuecomment-1815312980.

**Comment by brentyi** [comment]
As an FYI, the `unsupported operand type(s) for |: 'type' and '_LiteralGenericAlias'` error is because the `peft` repository recently added this `bool | Literal["gaussian", "loftq"]` type annotation:
https://github.com/huggingface/peft/blob/21c304f6f6ea62c7dcbef8e201d178a7575b471d/src/peft/tuners/lora/config.py#L100

This syntax requires Python 3.10; `Union[bool, Literal["gaussian", "loftq"]]` should be used for older versions of Python.

You can reproduce the same error as `tyro` with:
```python
from peft import LoraConfig
from typing import get_type_hints

get_type_hints(LoraConfig)
```

or:
```python
from peft import LoraConfig
from transformers import HfArgumentParser

HfArgumentParser(LoraConfig)
```
