### ISSUE TITLE
fails to continue train the model in ```examples/research_projects/stack_llama_2```

### ISSUE THREAD

**Issue by lavine-lmu** [huggingface/trl#1037]
I have ran some steps with the code ```examples/research_projects/stack_llama_2/scripts/sft_llama2.py``` and I'd like to continue train the model, but when I load the peft model and then feed the model to ```SFTTrainer```, it always appear the ```CUDA error```. 
##### Continue Training
+ I made the following changes to the code ```sft_llama2.py``` according to [this tutorial](https://huggingface.co/docs/trl/sft_trainer) and also [this issues](https://github.com/huggingface/trl/issues/786).
    - load the peftModel
    - pass the peftModel directly to the trainer without the peft_config argument being passed
```
from peft import  PeftModel
peft_model = PeftModel.from_pretrained(base_model, MY_CHECKPOINT)
trainer = SFTTrainer(
    model=peft_model,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    packing=script_args.packing,
    max_seq_length=None,
    tokenizer=tokenizer,
    args=training_args,
)
```
+ It is so strange that I have the following error, without any other changes of the code.
```
Traceback (most recent call last):
  File "sft_continue_training.py", line 214, in <module>
    peft_model = PeftModel.from_pretrained(base_model, 'MY_PATH')
  File "/lib/python3.9/site-packages/peft/peft_model.py", line 332, in from_pretrained
    model.load_adapter(model_id, adapter_name, is_trainable=is_trainable, **kwargs)
  File "lib/python3.9/site-packages/peft/peft_model.py", line 629, in load_adapter
    adapters_weights = load_peft_weights(model_id, device=torch_device, **hf_hub_download_kwargs)
  File "lib/python3.9/site-packages/peft/utils/save_and_load.py", line 222, in load_peft_weights
    adapters_weights = safe_load_file(filename, device=device)
  File "lib/python3.9/site-packages/safetensors/torch.py", line 310, in load_file
    result[k] = f.get_tensor(k)
RuntimeError: CUDA error: CUDA-capable device(s) is/are busy or unavailable
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```
@younesbelkada, maybe you know how to fix it? or do anyone else know what is the problem? Thanks!

**Comment by lavine-lmu** [comment]
It seems the code can not do continue training on multi-gpu? because when I use the same code to do the continue training, it works without error. But  when I change to multi-gpu, it fails. It is so strange that I can train the model on multi-gpu, but fails to continue training on multi-gpu. Anyone can help to fix this? Thanks!
