### ISSUE TITLE
dpo_llama2.py is outdated?

### ISSUE THREAD

**Issue by crescentluna** [huggingface/trl#1136]
The First question is about the discrepancy in the model used for fine-tuning in the blog "Fine-tune Llama 2 with DPO" (https://huggingface.co/blog/dpo-trl). The blog uses AutoPerfModelForCausalLM, which can load adapter models trained by LORA, whereas the shared dpo_llama2.py script (https://github.com/huggingface/trl/blob/main/examples/research_projects/stack_llama_2/scripts/dpo_llama2.py) still uses AutoModelForCausalLM. The question is about the difference between how these two models load. 

The Second question is regarding an issue encountered when defining model_ref and passing it to the DPOTrainer for training "A RuntimeError: Expected to mark a variable ready only once" is encountered. 
The detailed error information is
```
Traceback (most recent call last):
  File "/root/ryan.ch/codes/trl/examples/research_projects/stack_llama_2/scripts/dpo_llama2.py", line 220, in <module>
    dpo_trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1556, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1838, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 2704, in training_step
    self.accelerator.backward(loss)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 1905, in backward
    loss.backward(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/__init__.py", line 204, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py", line 161, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/__init__.py", line 204, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
Parameter at index 191 has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration. You can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print parameter names for further debugging.
```
I tried to remove model_ref definition but it still does not work

**Comment by crescentluna** [comment]
The seconed problem is fixed by setting gradient_checkpointing=False according to #722

**Comment by lvwerra** [comment]
tagging @kashif and @younesbelkada

**Comment by younesbelkada** [comment]
Indeed, to fix the issue you need to pass `gradient_checkpointing_kwargs={"use_reentrant": False}` here: https://github.com/huggingface/trl/blob/main/examples/research_projects/stack_llama_2/scripts/dpo_llama2.py#L173 @crescentluna would you be happy opening a PR to add that on the script?

**Comment by usuyama** [comment]
I just hit the same issue and this tip still worked!
