### ISSUE TITLE
Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by celsowm** [huggingface/trl#1151]
Hi
I trying to DPO train a merged SFT fine tuned model using this code on my 3060ti 12gb:

```python
from transformers import pipeline, AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig, TrainingArguments
from trl import SFTTrainer, DPOTrainer
from datasets import load_dataset, Dataset
from peft import LoraConfig, PeftModel, AutoPeftModelForCausalLM
import bitsandbytes as bnb
import torch, sys, os
from dataclasses import dataclass, field
from typing import Dict, Optional
from accelerate import Accelerator

torch.cuda.empty_cache()

os.environ['CUDA_VISIBLE_DEVICES'] ='0'

model_name_or_path = "outputs/mini-stack-exchange-paired-sft/final_checkpoint"
dataset_name = "celsowm/stack-exchange-paired-mini-1k"
max_length = 1024

def get_stack_exchange_paired(
    split: str,
    data_dir: str = "data/rl",
    sanity_check: bool = False,
    cache_dir: str = None,
    num_proc=24,
) -> Dataset:
    """Load the stack-exchange-paired dataset from Hugging Face and convert it to the necessary format.

    The dataset is converted to a dictionary with the following structure:
    {
        'prompt': List[str],
        'chosen': List[str],
        'rejected': List[str],
    }

    Prompts are structured as follows:
      "Question: " + <prompt> + "\n\nAnswer: "
    """
    dataset = load_dataset(
        dataset_name,
        split=split
    )
    original_columns = dataset.column_names

    if sanity_check:
        dataset = dataset.select(range(min(len(dataset), 1000)))

    def return_prompt_and_responses(samples) -> Dict[str, str]:
        
        return {
            "prompt": ["Question: " + question + "\n\nAnswer: " for question in samples["question"]],
            "chosen": samples["response_j"],
            "rejected": samples["response_k"],
        }

    return dataset.map(
        return_prompt_and_responses,
        batched=True,
        num_proc=num_proc,
        remove_columns=original_columns,
    )


model = AutoModelForCausalLM.from_pretrained(
        model_name_or_path,
        device_map={"": Accelerator().local_process_index},
        torch_dtype=torch.float16,
        load_in_4bit=True,
    )

model.config.use_cache = False

model_ref = AutoModelForCausalLM.from_pretrained(
        model_name_or_path,
        device_map={"": Accelerator().local_process_index},
        torch_dtype=torch.float16,
        load_in_4bit=True,
    )
 
tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-2-7b-hf")
tokenizer.pad_token = tokenizer.eos_token

train_dataset = get_stack_exchange_paired("train", data_dir="data/rl", sanity_check=True)
train_dataset = train_dataset.filter(
        lambda x: len(x["prompt"]) + len(x["chosen"]) <= max_length
        and len(x["prompt"]) + len(x["rejected"]) <= max_length
    )

# 3. Load evaluation dataset
eval_dataset = get_stack_exchange_paired("test", data_dir="data/evaluation", sanity_check=True)
eval_dataset = eval_dataset.filter(
        lambda x: len(x["prompt"]) + len(x["chosen"]) <= max_length
        and len(x["prompt"]) + len(x["rejected"]) <= max_length
    )

training_args = TrainingArguments(
        per_device_train_batch_size=4,
        per_device_eval_batch_size=1,
        max_steps=1000,
        logging_steps=10,
        save_steps=100,
        gradient_accumulation_steps=4,
        gradient_checkpointing=True,
        learning_rate=5e-4,
        evaluation_strategy="steps",
        eval_steps=100,
        output_dir="outputs/mini-stack-exchange-paired-sft/dpo",
        lr_scheduler_type="cosine",
        warmup_steps=100,
        optim="paged_adamw_32bit",
        bf16=True,
        remove_unused_columns=False,
        run_name="dpo_llama2",
    )

peft_config = LoraConfig(
        r=8,
        lora_alpha=16,
        lora_dropout=0.05,
        target_modules=[
            "q_proj",
            "v_proj",
            "k_proj",
            "out_proj",
            "fc_in",
            "fc_out",
            "wte",
        ],
        bias="none",
        task_type="CAUSAL_LM",
    )

dpo_trainer =  DPOTrainer(
        model,
        model_ref,
        args=training_args,
        #beta=script_args.beta,
        train_dataset=train_dataset,
        eval_dataset=eval_dataset,
        tokenizer=tokenizer,
        peft_config=peft_config,
        max_prompt_length=512,
        max_length=max_length
    )

dpo_trainer.train()
dpo_trainer.save_model(training_args.output_dir)

# 7. save
output_dir = os.path.join(training_args.output_dir, "final_checkpoint")
dpo_trainer.model.save_pretrained(output_dir)
```

And got:

`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat2 in method wrapper_CUDA_mm)`

**Comment by younesbelkada** [comment]
hi @celsowm 
Thanks for the issue! Can you share the full traceback?

**Comment by celsowm** [comment]
> hi @celsowm Thanks for the issue! Can you share the full traceback?

```
Traceback (most recent call last):
  File "/home/celso/Documents/ia/dpo_train_llama2_meta.py", line 146, in <module>
    dpo_trainer.train()
  File "/home/celso/.local/lib/python3.11/site-packages/transformers/trainer.py", line 1537, in train
    return inner_training_loop(
  File "/home/celso/.local/lib/python3.11/site-packages/transformers/trainer.py", line 1854, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/celso/.local/lib/python3.11/site-packages/transformers/trainer.py", line 2735, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/celso/.local/lib/python3.11/site-packages/trl/trainer/dpo_trainer.py", line 594, in compute_loss
    loss, metrics = self.get_batch_metrics(model, inputs, train_eval="train")
  File "/home/celso/.local/lib/python3.11/site-packages/trl/trainer/dpo_trainer.py", line 545, in get_batch_metrics
    ) = self.concatenated_forward(model, batch)
  File "/home/celso/.local/lib/python3.11/site-packages/trl/trainer/dpo_trainer.py", line 511, in concatenated_forward
    all_logits = model(
  File "/home/celso/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/celso/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/celso/.local/lib/python3.11/site-packages/accelerate/utils/operations.py", line 659, in forward
    return model_forward(*args, **kwargs)
  File "/home/celso/.local/lib/python3.11/site-packages/accelerate/utils/operations.py", line 647, in _call_
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/home/celso/.local/lib/python3.11/site-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/celso/.local/lib/python3.11/site-packages/peft/peft_model.py", line 1003, in forward
    return self.base_model(
  File "/home/celso/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/celso/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/celso/.local/lib/python3.11/site-packages/peft/tuners/tuners_utils.py", line 107, in forward
    return self.model.forward(*args, **kwargs)
  File "/home/celso/.local/lib/python3.11/site-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/celso/.local/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 1181, in forward
    outputs = self.model(
  File "/home/celso/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/celso/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/celso/.local/lib/python3.11/site-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/celso/.local/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 1058, in forward
    layer_outputs = self._gradient_checkpointing_func(
  File "/home/celso/.local/lib/python3.11/site-packages/torch/_compile.py", line 24, in inner
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
  File "/home/celso/.local/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "/home/celso/.local/lib/python3.11/site-packages/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/home/celso/.local/lib/python3.11/site-packages/torch/utils/checkpoint.py", line 451, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/celso/.local/lib/python3.11/site-packages/torch/autograd/function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/celso/.local/lib/python3.11/site-packages/torch/utils/checkpoint.py", line 230, in forward
    outputs = run_function(*args)
  File "/home/celso/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/celso/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/celso/.local/lib/python3.11/site-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/celso/.local/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 796, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/celso/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/celso/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/celso/.local/lib/python3.11/site-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/celso/.local/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 691, in forward
    query_states = self.q_proj(hidden_states)
  File "/home/celso/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/celso/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/celso/.local/lib/python3.11/site-packages/peft/tuners/lora/bnb.py", line 290, in forward
    output = lora_B(lora_A(dropout(x)))
  File "/home/celso/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/celso/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/celso/.local/lib/python3.11/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat2 in method wrapper_CUDA_mm)
```

**Comment by younesbelkada** [comment]
what peft version are you using?
