### ISSUE TITLE
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by sandyis** [huggingface/trl#1157]
getting below error when making a query in chat instruct gui
i event restored files for model ....is this some setting i did in inadvertently ?

`Traceback (most recent call last):
  File "/home/nsi/text-generation-webui-main/modules/callbacks.py", line 57, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nsi/text-generation-webui-main/modules/text_generation.py", line 351, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/nsi/text-generation-webui-main/installer_files/env/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/nsi/text-generation-webui-main/installer_files/env/lib/python3.11/site-packages/transformers/generation/utils.py", line 1764, in generate
    return self.sample(
           ^^^^^^^^^^^^
  File "/home/nsi/text-generation-webui-main/installer_files/env/lib/python3.11/site-packages/transformers/generation/utils.py", line 2897, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
`

model load was okay 

`2023-12-29 19:45:27 INFO:Loading llama-2-13b-chat-hf...
2023-12-29 19:45:27 INFO:Using the following 4-bit params: {'load_in_4bit': True, 'bnb_4bit_compute_dtype': torch.float16, 'bnb_4bit_quant_type': 'nf4', 'bnb_4bit_use_double_quant': False}
Output generated in 12.88 seconds (0.08 tokens/s, 1 tokens, context 1159, seed 1205013400)
Loading checkpoint shards: 100%|██████████| 6/6 [00:27<00:00,  4.56s/it]
2023-12-29 19:45:55 INFO:LOADER: Transformers
2023-12-29 19:45:55 INFO:TRUNCATION LENGTH: 2048
2023-12-29 19:45:55 INFO:INSTRUCTION TEMPLATE: Llama-v2
2023-12-29 19:45:55 INFO:Loaded the model in 27.90 seconds.
`

**Comment by lvwerra** [comment]
I think this is an issue for the [`text-generation-webui`](https://github.com/oobabooga/text-generation-webui) rather than TRL :)
