### ISSUE TITLE
FineTune Full Model (Mistral-7B) on 2xA100(80Gx2 = 160GB) give me OOM error. 

### ISSUE THREAD

**Issue by candygocandy** [huggingface/trl#1182]
Hi 

I am trying to finetune Mistral-7B (instruct v0.2) on 2xA100, each A100 has 80GB so a total of 160GB using your script. 
https://github.com/huggingface/trl/blob/main/examples/research_projects/stack_llama_2/scripts/dpo_llama2.py

Some changes that I make:
```

    model = AutoModelForCausalLM.from_pretrained(
        script_args.model_name_or_path,
        torch_dtype=torch.float16,
        device_map = 0, 
    )
    model.config.use_cache = False
    model_ref = AutoModelForCausalLM.from_pretrained(
        script_args.model_name_or_path,
        torch_dtype=torch.float16,
        device_map  = 1, 
    )
```
If I change the model to 1B model (TinyLamma1B), then my training script runs. However, using Mistral-7B, 
I am getting this error:
```
[2024-01-05 17:45:01,718] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 4112887 closing signal SIGTERM
[2024-01-05 17:45:02,823] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -9) local_rank: 1 (pid: 4112888) of binary: /home/gpu_user/miniconda3/envs/myenv/bin/python
Traceback (most recent call last):
  File "/home/gpu_user/miniconda3/envs/myenv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/gpu_user/miniconda3/envs/myenv/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/gpu_user/miniconda3/envs/myenv/lib/python3.9/site-packages/accelerate/commands/launch.py", line 1008, in launch_command
    multi_gpu_launcher(args)
  File "/home/gpu_user/miniconda3/envs/myenv/lib/python3.9/site-packages/accelerate/commands/launch.py", line 666, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/gpu_user/miniconda3/envs/myenv/lib/python3.9/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/gpu_user/miniconda3/envs/myenv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/gpu_user/miniconda3/envs/myenv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
examples/research_projects/stack_llama_2/scripts/dpo_llama2_test.py FAILED

```

Any help?

**Comment by younesbelkada** [comment]
Hi @candygocandy 
can you replace `device_map  = 1, ` and `device_map  = 0,` respectively with `device_map  = {"":1},` and `device_map  = {"": 0},` ? Also make sure to use gradient_checkpointing by passing `gradient_checkpointing=True`. Also are you using LoRA?
