### ISSUE TITLE
Load imdb dataset error in examples/scripts/ppo.py

### ISSUE THREAD

**Issue by 1485840691** [huggingface/trl#1260]
When I run  examples/scripts/ppo.py with default parameters, I encounter the following error:
`Traceback (most recent call last):
  File "D:\projects\trl_to_commit\trl\examples\scripts\ppo.py", line 116, in <module>
    dataset = build_dataset(args.ppo_config, args.ppo_config.query_dataset)
  File "D:\projects\trl_to_commit\trl\examples\scripts\ppo.py", line 99, in build_dataset
    ds = load_dataset(query_dataset, split="train")
  File "D:\projects\trl\venv\lib\site-packages\datasets\load.py", line 1782, in load_dataset
    builder_instance.download_and_prepare(
  File "D:\projects\trl\venv\lib\site-packages\datasets\builder.py", line 872, in download_and_prepare
    self._download_and_prepare(
  File "D:\projects\trl\venv\lib\site-packages\datasets\builder.py", line 985, in _download_and_prepare
    verify_splits(self.info.splits, split_dict)
  File "D:\projects\trl\venv\lib\site-packages\datasets\utils\info_utils.py", line 91, in verify_splits
    raise ExpectedMoreSplits(str(set(expected_splits) - set(recorded_splits)))
datasets.utils.info_utils.ExpectedMoreSplits: {"unsupervised"}`

This error happens when I load the imdb dataset.

After investigation, this error seems to be related with dataset revision.
https://github.com/huggingface/datasets/issues/876

Setting revision=1.1.3 seems to resolve the problem.

Would like to confirm if this is a real problem, or could be resolved in other ways.

**Comment by 1485840691** [comment]
Seem to be working in another environment. Close issue.
