### ISSUE TITLE
Error when using multiprocessing in the DPO data preprocessing

### ISSUE THREAD

**Issue by imraviagrawal** [huggingface/trl#1310]
dpo_trainer = DPOTrainer(
  File "/usr/local/lib/python3.10/dist-packages/trl/trainer/dpo_trainer.py", line 371, in __init__
    train_dataset = train_dataset.map(self.tokenize_row, num_proc=self.dataset_num_proc)
  File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py", line 592, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py", line 557, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py", line 3185, in map
    for rank, done, content in iflatmap_unordered(
  File "/usr/local/lib/python3.10/dist-packages/datasets/utils/py_utils.py", line 654, in iflatmap_unordered
    [async_result.get(timeout=0.05) for async_result in async_results]
  File "/usr/local/lib/python3.10/dist-packages/datasets/utils/py_utils.py", line 654, in <listcomp>
    [async_result.get(timeout=0.05) for async_result in async_results]
  File "/usr/local/lib/python3.10/dist-packages/multiprocess/pool.py", line 774, in get
    raise self._value
  File "/usr/local/lib/python3.10/dist-packages/multiprocess/pool.py", line 540, in _handle_tasks
    put(task)
  File "/usr/local/lib/python3.10/dist-packages/multiprocess/connection.py", line 209, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/local/lib/python3.10/dist-packages/multiprocess/reduction.py", line 54, in dumps
    cls(buf, protocol, *args, **kwds).dump(obj)
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 418, in dump
    StockPickler.dump(self, obj)
  File "/usr/lib/python3.10/pickle.py", line 487, in dump
    self.save(obj)
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/usr/lib/python3.10/pickle.py", line 902, in save_tuple
    save(element)
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/usr/lib/python3.10/pickle.py", line 887, in save_tuple
    save(element)
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 1212, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.10/pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.10/pickle.py", line 998, in _batch_setitems
    save(v)
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 1453, in save_instancemethod0
    pickler.save_reduce(MethodType, (obj.__func__, obj.__self__), obj=obj)
  File "/usr/lib/python3.10/pickle.py", line 692, in save_reduce
    save(args)
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/usr/lib/python3.10/pickle.py", line 887, in save_tuple
    save(element)
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.10/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.10/pickle.py", line 717, in save_reduce
    save(state)
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 1212, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.10/pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.10/pickle.py", line 998, in _batch_setitems
    save(v)
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.10/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.10/pickle.py", line 717, in save_reduce
    save(state)
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 1212, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.10/pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.10/pickle.py", line 998, in _batch_setitems
    save(v)
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.10/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.10/pickle.py", line 713, in save_reduce
    self._batch_setitems(dictitems)
  File "/usr/lib/python3.10/pickle.py", line 998, in _batch_setitems
    save(v)
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.10/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.10/pickle.py", line 717, in save_reduce
    save(state)
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 1212, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.10/pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.10/pickle.py", line 998, in _batch_setitems
    save(v)
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.10/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.10/pickle.py", line 713, in save_reduce
    self._batch_setitems(dictitems)
  File "/usr/lib/python3.10/pickle.py", line 998, in _batch_setitems
    save(v)
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.10/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.10/pickle.py", line 717, in save_reduce
    save(state)
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 1212, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.10/pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.10/pickle.py", line 998, in _batch_setitems
    save(v)
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.10/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.10/pickle.py", line 713, in save_reduce
    self._batch_setitems(dictitems)
  File "/usr/lib/python3.10/pickle.py", line 1003, in _batch_setitems
    save(v)
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.10/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.10/pickle.py", line 692, in save_reduce
    save(args)
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/usr/lib/python3.10/pickle.py", line 902, in save_tuple
    save(element)
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 1212, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.10/pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.10/pickle.py", line 998, in _batch_setitems
    save(v)
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.10/pickle.py", line 578, in save
    rv = reduce(self.proto)
TypeError: cannot pickle 'torch._C._distributed_c10d.ProcessGroup' object  
  

 dpo_trainer = DPOTrainer(
  File "/usr/local/lib/python3.10/dist-packages/trl/trainer/dpo_trainer.py", line 369, in __init__
            dpo_trainer = DPOTrainer(dpo_trainer = DPOTrainer(dpo_trainer = DPOTrainer(

      File "/usr/local/lib/python3.10/dist-packages/trl/trainer/dpo_trainer.py", line 369, in __init__
  File "/usr/local/lib/python3.10/dist-packages/trl/trainer/dpo_trainer.py", line 369, in __init__
dpo_trainer = DPOTrainer(  File "/usr/local/lib/python3.10/dist-packages/trl/trainer/dpo_trainer.py", line 369, in __init__

  File "/usr/local/lib/python3.10/dist-packages/trl/trainer/dpo_trainer.py", line 369, in __init__
    with PartialState().local_main_process_first():
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
                with PartialState().local_main_process_first():with PartialState().local_main_process_first():
with PartialState().local_main_process_first():with PartialState().local_main_process_first():
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter_

**Comment by younesbelkada** [comment]
the error says:

> TypeError: cannot pickle 'torch._C._distributed_c10d.ProcessGroup' object

When calling:

```python
with PartialState().local_main_process_first():
```

Not sure what is wrong here - can you try to update `torch` - also cc @muellerz are you familiar with this behaviour?

**Comment by imraviagrawal** [comment]
Finishing up today, will give it a try first thing tomorrow, will update you

**Comment by lewtun** [comment]
I think this is caused when DeepSpeed's `zero.Init()` is activated and `dataset_num_proc>1` in `DPOTrainer`. For example, here's how to reproduce using the `dpo.py` script:

**Step 1 - enable multiprocessing**

```diff
    trainer = DPOTrainer(
        model,
        model_ref,
        args=training_args,
        beta=args.beta,
        train_dataset=train_dataset,
        eval_dataset=eval_dataset,
        tokenizer=tokenizer,
        max_length=args.max_length,
        max_target_length=args.max_target_length,
        max_prompt_length=args.max_prompt_length,
        generate_during_eval=args.generate_during_eval,
        peft_config=get_peft_config(model_config),
+        dataset_num_proc=4,
    )
```

**Step 2 - run with zero3**

```
accelerate launch --config_file=examples/accelerate_configs/deepspeed_zero3.yaml examples/scripts/dpo.py \
    --model_name_or_path=gpt2 \
    --per_device_train_batch_size 4 \
    --max_steps 1000 \
    --learning_rate 1e-3 \
    --gradient_accumulation_steps 1 \
    --logging_steps 10 \
    --eval_steps 500 \
    --output_dir="dpo_anthropic_hh" \
    --warmup_steps 150 \
    --report_to wandb \
    --bf16 \
    --logging_first_step \
    --no_remove_unused_columns
```

<details>
  <summary>Stack trace</summary>

```
Traceback (most recent call last):
  File "/fsx/lewis/git/hf/trl/examples/scripts/dpo.py", line 170, in <module>
    trainer = DPOTrainer(
  File "/fsx/lewis/git/hf/trl/trl/trainer/dpo_trainer.py", line 375, in __init__
    train_dataset = train_dataset.map(self.tokenize_row, num_proc=self.dataset_num_proc)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 592, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 557, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3185, in map
    for rank, done, content in iflatmap_unordered(
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/datasets/utils/py_utils.py", line 654, in iflatmap_unordered
    [async_result.get(timeout=0.05) for async_result in async_results]
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/datasets/utils/py_utils.py", line 654, in <listcomp>
    [async_result.get(timeout=0.05) for async_result in async_results]
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/multiprocess/pool.py", line 774, in get
    raise self._value
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/multiprocess/pool.py", line 540, in _handle_tasks
    put(task)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/multiprocess/connection.py", line 209, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/multiprocess/reduction.py", line 54, in dumps
    cls(buf, protocol, *args, **kwds).dump(obj)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/dill/_dill.py", line 418, in dump
    StockPickler.dump(self, obj)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 487, in dump
    self.save(obj)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 902, in save_tuple
    save(element)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 887, in save_tuple
    save(element)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/dill/_dill.py", line 1212, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 998, in _batch_setitems
    save(v)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/dill/_dill.py", line 1453, in save_instancemethod0
    pickler.save_reduce(MethodType, (obj.__func__, obj.__self__), obj=obj)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 692, in save_reduce
    save(args)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 887, in save_tuple
    save(element)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 717, in save_reduce
    save(state)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/dill/_dill.py", line 1212, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 998, in _batch_setitems
    save(v)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 717, in save_reduce
    save(state)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/dill/_dill.py", line 1212, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 998, in _batch_setitems
    save(v)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 713, in save_reduce
    self._batch_setitems(dictitems)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 998, in _batch_setitems
    save(v)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 717, in save_reduce
    save(state)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/dill/_dill.py", line 1212, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 998, in _batch_setitems
    save(v)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 713, in save_reduce
    self._batch_setitems(dictitems)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 998, in _batch_setitems
    save(v)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 717, in save_reduce
    save(state)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/dill/_dill.py", line 1212, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 998, in _batch_setitems
    save(v)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 713, in save_reduce
    self._batch_setitems(dictitems)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 1003, in _batch_setitems
    save(v)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 692, in save_reduce
    save(args)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 902, in save_tuple
    save(element)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/dill/_dill.py", line 1212, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 998, in _batch_setitems
    save(v)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/dill/_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/pickle.py", line 578, in save
    rv = reduce(self.proto)
TypeError: cannot pickle 'torch._C._distributed_c10d.ProcessGroup' object
```
</details>

AFAICT the issue is that `tokenize_row()` isn't hashable when `zero.Init()` is activated, but I'm not sure why this is the case. Generally this happens when a function is non-deterministic but I don't see any obvious part of the code where that is the case.

In particular, switching off `zero_init:false` in the `accelerate` config runs without problem, but that's not desirable since we want to be able to shard large models.

**Comment by iseesaw** [comment]
I encountered this problem as well. Have you found a solution?

**Comment by voidmagic** [comment]
Same issue
