### ISSUE TITLE
Questions about peft_module_casting_to_bf16

### ISSUE THREAD

**Issue by Mr-KenLee** [huggingface/trl#1398]
I am trying to train a model using LoRA+Int4 quantization. In order to generate intermediate results at the same time, we made a simple modification to Seq2SeqTrainer and imitated SFTTrainer for model initialization. The rough code is as follows:

```python
# Merging and quantization
if model_args.use_peft_lora:

    if model_args.use_8bit_quantization or model_args.use_4bit_quantization:
        prepare_model_kwargs = {
            "use_gradient_checkpointing": training_args.gradient_checkpointing,
            'gradient_checkpointing_kwargs': training_args.gradient_checkpointing_kwargs
        }
        model = prepare_model_for_kbit_training(model, **prepare_model_kwargs)

    # Build peft
    model = get_peft_model(model, peft_config)

    if training_args.bf16 and model_args.use_4bit_quantization:
        peft_module_casting_to_bf16(model)
```

However, we encountered a strange issue: when we use LoRA+quantization, if we add `peft_module_casting_to_bf16`, the model will have a type mismatch when calling `generate`.
We conducted an experiment with a simple piece of code:
```python
from peft import LoftQConfig, LoraConfig, get_peft_model, LoraModel, prepare_model_for_kbit_training
from transformers import AutoModelForCausalLM, BitsAndBytesConfig, AutoTokenizer
import torch
from trl.trainer.utils import peft_module_casting_to_bf16

model = AutoModelForCausalLM.from_pretrained("Baichuan2-7B-Chat",
                                                  trust_remote_code=True,
                                                  quantization_config=BitsAndBytesConfig(
                                                        load_in_4bit=True,
                                                        bnb_4bit_quant_type="nf4",  # Quantization data type setting
                                                        bnb_4bit_compute_dtype=torch.bfloat16  # Quantization data computation format
                                                  ),
                                                  device_map="auto",
                                                  torch_dtype=torch.bfloat16
                                                  )  # don't quantize here

tokenizer = AutoTokenizer.from_pretrained("Baichuan2-7B-Chat", trust_remote_code=True)


# LoRA
lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    target_modules=["W_pack"],
    lora_dropout=0.1,
    bias="none",
    task_type="CAUSAL_LM"
)

prepare_model_kwargs = {
                "use_gradient_checkpointing": False,
                'gradient_checkpointing_kwargs': {}
            }

model = prepare_model_for_kbit_training(model, **prepare_model_kwargs)
model = get_peft_model(model, lora_config)

# Critical code
peft_module_casting_to_bf16(model)

sentence = ["example text"]

outputs = tokenizer(
                sentence,
                add_special_tokens=False,
                truncation=True,
                padding=False,
                max_length=512,
                return_overflowing_tokens=False,
                return_length=False,
                return_tensors='pt'
            ).to("cuda")

generations = model.generate(**outputs)
```

The error is as follows:
```
Traceback (most recent call last):
  File "/mnt/DataDrive/liyiyang/toy.py", line 61, in <module>
    generations = model.generate(**outputs)
  File "/home/ubuntu/users/qisiya/anaconda3/envs/llm/lib/python3.10/site-packages/peft/peft_model.py", line 1148, in generate
    outputs = self.base_model.generate(*args, **kwargs)
  File "/home/ubuntu/users/qisiya/anaconda3/envs/llm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/users/qisiya/anaconda3/envs/llm/lib/python3.10/site-packages/transformers/generation/utils.py", line 1525, in generate
    return self.sample(
  File "/home/ubuntu/users/qisiya/anaconda3/envs/llm/lib/python3.10/site-packages/transformers/generation/utils.py", line 2622, in sample
    outputs = self(
  File "/home/ubuntu/users/qisiya/anaconda3/envs/llm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/users/qisiya/anaconda3/envs/llm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/users/qisiya/anaconda3/envs/llm/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/ubuntu/users/qisiya/.cache/huggingface/modules/transformers_modules/Baichuan2-7B-Chat/modeling_baichuan.py", line 686, in forward
    outputs = self.model(
  File "/home/ubuntu/users/qisiya/anaconda3/envs/llm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/users/qisiya/anaconda3/envs/llm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/users/qisiya/.cache/huggingface/modules/transformers_modules/Baichuan2-7B-Chat/modeling_baichuan.py", line 461, in forward
    layer_outputs = decoder_layer(
  File "/home/ubuntu/users/qisiya/anaconda3/envs/llm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/users/qisiya/anaconda3/envs/llm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/users/qisiya/anaconda3/envs/llm/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/ubuntu/users/qisiya/.cache/huggingface/modules/transformers_modules/Baichuan2-7B-Chat/modeling_baichuan.py", line 273, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/ubuntu/users/qisiya/anaconda3/envs/llm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/users/qisiya/anaconda3/envs/llm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/users/qisiya/anaconda3/envs/llm/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/ubuntu/users/qisiya/.cache/huggingface/modules/transformers_modules/Baichuan2-7B-Chat/modeling_baichuan.py", line 234, in forward
    attn_output = F.scaled_dot_product_attention(query_states, key_states, value_states, attn_mask = attention_mask)
RuntimeError: Expected attn_mask dtype to be bool or to match query dtype, but got attn_mask.dtype: c10::BFloat16 and query.dtype: float instead.
```

What could be the reason for this? Did I do something wrong?
Also, what is the purpose of `peft_module_casting_to_bf16` in SFTTrainer?

**Comment by Mr-KenLee** [comment]
I seem to find out the reason. peft_module_casting_to_bf16 converts Layer Norm to float32, which results in an error.

**Comment by younesbelkada** [comment]
yes that method is used to ensure training stability, to use `generate` after calling `peft_module_casting_to_bf16` you can wrap generate under `torch.amp.autocast()` context manager
