### ISSUE TITLE
Errors loading DDPO model finetuned with LORA after saving locally

### ISSUE THREAD

**Issue by skavulya** [huggingface/trl#1404]
I am experiencing problems loading the DDPO model saved locally using `trainer.save_pretrained` after finetuning with LoRA. There are errors about missing keys.

```
Traceback (most recent call last):
  File "ddpo_eval.py", line 6, in <module>
    pipeline = DefaultDDPOStableDiffusionPipeline(
  File "/trl/models/modeling_sd_base.py", line 533, in __init__
    self.sd_pipeline = StableDiffusionPipeline.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/pipeline_utils.py", line 1286, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/pipeline_utils.py", line 531, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 662, in from_pretrained
    raise ValueError(
ValueError: Cannot load <class 'diffusers.models.unets.unet_2d_condition.UNet2DConditionModel'> from save/models/ddpo_aesthetic/unet because the following keys are missing: 
 up_blocks.2.attentions.2.transformer_blocks.0.attn2.to_out.0.bias, down_blocks.0.attentions.1.transformer_blocks.0.attn1.to_k.weight, down_blocks.2.attentions.0.transformer_blocks.0.attn1.to_out.0.bias, mid_block.attentions.0.transformer_blocks.0.attn2.to_q.weight, up_blocks.2.attentions.1.transformer_blocks.0.attn2.to_k.weight, up_blocks.3.attentions.2.transformer_blocks.0.attn2.to_out.0.weight, up_blocks.3.attentions.0.transformer_blocks.0.attn1.to_out.0.bias, up_blocks.2.attentions.2.transformer_blocks.0.attn2.to_v.weight, down_blocks.2.attentions.0.transformer_blocks.0.attn1.to_q.weight, up_blocks.1.attentions.0.transformer_blocks.0.attn2.to_v.weight, down_blocks.0.attentions.1.transformer_blocks.0.attn1.to_v.weight, up_blocks.1.attentions.2.transformer_blocks.0.attn1.to_k.weight, 
``` 
The failure occurs when I create the pipeline using `pipeline = DefaultDDPOStableDiffusionPipeline("./ddpo_aesthetic")`

I am able to load the model without errors if I use:
```
pipeline = DefaultDDPOStableDiffusionPipeline(
    "runwayml/stable-diffusion-v1-5",
)
pipeline.sd_pipeline.load_lora_weights("./ddpo_aesthetic")

```
**Environment**
torch: 2.2.0a0
transformers: 4.38.2
peft: 0.9.0
trl: git commit from March 7th 2024 - 22b4f548f4954319ece6f17cab226a26e2db65be

**Reproduction steps**

1. Added `trainer.save_pretrained("./ddpo_aesthetic")` to `ddpo.py` to save model locally instead of pushing to hub.
2. Finetuned model using: 
```
python examples/scripts/ddpo.py \
    --num_epochs=200 \
    --train_gradient_accumulation_steps=1 \
    --sample_num_steps=50 \
    --sample_batch_size=6 \
    --train_batch_size=3 \
    --sample_num_batches_per_epoch=4 \
    --per_prompt_stat_tracking=True \
    --per_prompt_stat_tracking_buffer_size=32 \
    --tracker_project_name="stable_diffusion_training" \
    --log_with="tensorboard"
```

3. Evaluated the model
```
import torch
from trl import DefaultDDPOStableDiffusionPipeline

torch.manual_seed(42)
pipeline = DefaultDDPOStableDiffusionPipeline(
    "ddpo_aesthetic",
)
device = torch.device("cuda")

# memory optimization
pipeline.vae.to(device, torch.float16)
pipeline.text_encoder.to(device, torch.float16)
pipeline.unet.to(device, torch.float16)

prompts = ["cat", "bat", "lion", "squirrel", "crab", "starfish", "whale", "sponge", "plankton"]
results = pipeline(prompts)

for prompt, image in zip(prompts, results.images):
    image.save(f"{prompt}.png")
```

**Comment by shashankg7** [comment]
Hi, I am facing the same error. Did you manage to resolve it? Also, just confirming pipeline.sd_pipeline.load_lora_weights("./ddpo_aesthetic") and trainer.save_pretrained("./ddpo_aesthetic") will save and load the fine-tuned model, right?
