### ISSUE TITLE
a problem of install trl

### ISSUE THREAD

**Issue by chenin-wang** [huggingface/trl#1461]
when install from source on window 11: 
`pip install git+https://github.com/huggingface/trl.git`

 error happened.
```
Collecting git+https://github.com/huggingface/trl.git
  Cloning https://github.com/huggingface/trl.git to c:\users\xxxxxx\appdata\local\temp\pip-req-build-313omp8t
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/trl.git 'C:\Users\xxxxxxx\AppData\Local\Temp\pip-req-build-313omp8t'
  Resolved https://github.com/huggingface/trl.git to commit 5095e7f94882bf9b18e72fef9dfc4032a6b019c7
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "<string>", line 85, in <module>
      OSError: [WinError 1314] 客户端没有所需的特权。: 'C:\\Users\\xxxxx\\AppData\\Local\\Temp\\pip-req-build-313omp8t\\examples/scripts' -> 'C:\\Users\\xxxxxx\\AppData\\Local\\Temp\\pip-req-build-313omp8t\\trl/commands/scripts'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\xxxxxx\.conda\envs\ai\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\xxxxxx\.conda\envs\ai\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\xxxxxx\.conda\envs\ai\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\xxxxx\AppData\Local\Temp\pip-build-env-b0j2kri2\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\xxxxxx\AppData\Local\Temp\pip-build-env-b0j2kri2\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\xxxxxx\AppData\Local\Temp\pip-build-env-b0j2kri2\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\xxxxx\AppData\Local\Temp\pip-build-env-b0j2kri2\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 123, in <module>
      FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'C:\\Users\\xxxxx\\AppData\\Local\\Temp\\pip-req-build-313omp8t\\trl/commands/scripts'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

C:\\Users\\xxxxx\\AppData\\Local\\Temp\\pip-req-build-313omp8t **\\trl/** commands/scripts'

the path is not right ，I found something to do with this file. 

https://github.com/huggingface/trl/blob/5095e7f94882bf9b18e72fef9dfc4032a6b019c7/setup.py#L85

**Comment by chenin-wang** [comment]
Run cmd as an administrator, and `pip install git+https://github.com/huggingface/trl.git` solve it.
