### ISSUE TITLE
dpo cli command error

### ISSUE THREAD

**Issue by Galaxy-Husky** [huggingface/trl#1513]
Hi, 
I tried a cli command as follows: 
https://github.com/huggingface/trl/blob/9a28b3fd0505aa38798f0122ab0ff3bb795384dd/tests/test_cli.py#L35

But I got the following error message: 
```
Traceback (most recent call last):
  File "/home/ping/mambaforge/envs/torch221/lib/python3.11/site-packages/trl/commands/scripts/dpo.py", line 147, in <module>
    trainer = DPOTrainer(
              ^^^^^^^^^^^
  File "/home/ping/mambaforge/envs/torch221/lib/python3.11/site-packages/trl/trainer/dpo_trainer.py", line 379, in __init__
    train_dataset = train_dataset.map(self.tokenize_row, num_proc=self.dataset_num_proc)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ping/mambaforge/envs/torch221/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 593, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ping/mambaforge/envs/torch221/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 558, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ping/mambaforge/envs/torch221/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3105, in map
    for rank, done, content in Dataset._map_single(**dataset_kwargs):
  File "/home/ping/mambaforge/envs/torch221/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3458, in _map_single
    example = apply_function_on_filtered_inputs(example, i, offset=offset)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ping/mambaforge/envs/torch221/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3361, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ping/mambaforge/envs/torch221/lib/python3.11/site-packages/trl/trainer/dpo_trainer.py", line 628, in tokenize_row
    raise ValueError(f"chosen should be an str but got {type(chosen)}")
ValueError: chosen should be an str but got <class 'list'>
Traceback (most recent call last):
  File "/home/ping/mambaforge/envs/torch221/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ping/mambaforge/envs/torch221/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/ping/mambaforge/envs/torch221/lib/python3.11/site-packages/accelerate/commands/launch.py", line 1023, in launch_command
    simple_launcher(args)
  File "/home/ping/mambaforge/envs/torch221/lib/python3.11/site-packages/accelerate/commands/launch.py", line 643, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/ping/mambaforge/envs/torch221/bin/python3.11', '/home/ping/mambaforge/envs/torch221/lib/python3.11/site-packages/trl/commands/scripts/dpo.py', '--max_steps', '1', '--output_dir', 'tmp-sft', '--model_name_or_path', 'HuggingFaceM4/tiny-random-LlamaForCausalLM', '--dataset_name', 'trl-internal-testing/hh-rlhf-trl-style', '--learning_rate', '1e-4', '--lr_scheduler_type', 'cosine', '--sanity_check']' returned non-zero exit status 1.
[18:45:18] TRL - DPO failed on ! See the logs above for further details.                                                                                                                                     cli.py:66
Traceback (most recent call last):
  File "/home/ping/mambaforge/envs/torch221/lib/python3.11/site-packages/trl/commands/cli.py", line 57, in main
    subprocess.run(
  File "/home/ping/mambaforge/envs/torch221/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['accelerate', 'launch', '/home/ping/mambaforge/envs/torch221/lib/python3.11/site-packages/trl/commands/scripts/dpo.py', '--max_steps', '1', '--output_dir', 'tmp-sft', '--model_name_or_path', 'HuggingFaceM4/tiny-random-LlamaForCausalLM', '--dataset_name', 'trl-internal-testing/hh-rlhf-trl-style', '--learning_rate', '1e-4', '--lr_scheduler_type', 'cosine', '--sanity_check']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ping/mambaforge/envs/torch221/bin/trl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ping/mambaforge/envs/torch221/lib/python3.11/site-packages/trl/commands/cli.py", line 67, in main
    raise ValueError("TRL CLI failed! Check the traceback above..") from exc
ValueError: TRL CLI failed! Check the traceback above..
```

**Comment by younesbelkada** [comment]
Hi @Galaxy-Husky 
Thanks for the issue, I think this is the wrong dataset format, can you try for example with this one: https://huggingface.co/datasets/trl-internal-testing/Anthropic-hh-rlhf-processed ?

**Comment by Galaxy-Husky** [comment]
> Hi @Galaxy-Husky Thanks for the issue, I think this is the wrong dataset format, can you try for example with this one: https://huggingface.co/datasets/trl-internal-testing/Anthropic-hh-rlhf-processed ?

Thank you for your prompt reply! 
It works with the version 0.8.1. But It appears to be much smaller than the original dataset, which is Anthropic/hh-rlhf.
Is there a dataset of the same size as the original one?

**Comment by Yuancheng-Xu** [comment]
@Galaxy-Husky Here? https://huggingface.co/datasets/trl-internal-testing/hh-rlhf-trl-style

**Comment by Galaxy-Husky** [comment]
> @Galaxy-Husky Here? https://huggingface.co/datasets/trl-internal-testing/hh-rlhf-trl-style

Thank you for your reply! But the version 0.8.1 only accepts this https://huggingface.co/datasets/trl-internal-testing/Anthropic-hh-rlhf-processed, which is different from trl-internal-testing/hh-rlhf-trl-style in format.
