### ISSUE TITLE
ImportError: cannot import name 'SFTScriptArguments' from 'trl.commands.cli_utils' & --report_to flag

### ISSUE THREAD

**Issue by alielfilali01** [huggingface/trl#1669]
I'm trying to test TRL using CLI and here my current script :
my file `run_trl.sh` :
```bash
pip install -U transformers trl peft bitsandbytes
git clone https://github.com/huggingface/trl
cd trl

accelerate launch --config_file examples/accelerate_configs/multi_gpu.yaml --num_processes=4 \
    examples/scripts/sft.py \
    --model_name google/gemma-7b \
    --dataset_name timdettmers/openassistant-guanaco \
    --per_device_train_batch_size 2 \
    --gradient_accumulation_steps 1 \
    --learning_rate 2e-4 \
    --save_steps 20_000 \
    --use_peft \
    --lora_r 16 \
    --lora_alpha 32 \
    --lora_target_modules q_proj k_proj v_proj o_proj \
    --load_in_4bit \
    --output_dir gemma-finetuned-openassistant
```
I simply run `bash run_trl.sh` and i expect it to work fine, create a folder named `gemma-finetuned-openassistant` and save the adapter there. But it did not and i recieve the following error that i couldn't figure out unfortunately :
```
...
Requirement already satisfied: python-dateutil>=2.8.2 in /home/user/miniconda/lib/python3.9/site-packages (from pandas->datasets->trl) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/user/miniconda/lib/python3.9/site-packages (from pandas->datasets->trl) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /home/user/miniconda/lib/python3.9/site-packages (from pandas->datasets->trl) (2024.1)
Requirement already satisfied: six>=1.5 in /home/user/miniconda/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas->datasets->trl) (1.16.0)
Requirement already satisfied: mpmath>=0.19 in /home/user/miniconda/lib/python3.9/site-packages (from sympy->torch>=1.4.0->trl) (1.3.0)
fatal: destination path 'trl' already exists and is not an empty directory.
Traceback (most recent call last):
  File "/data/Kabour/trl/examples/scripts/sft.py", line 54, in <module>
    from trl.commands.cli_utils import init_zero_verbose, SFTScriptArguments, TrlParser
ImportError: cannot import name 'SFTScriptArguments' from 'trl.commands.cli_utils' (/home/user/miniconda/lib/python3.9/site-packages/trl/commands/cli_utils.py)
Traceback (most recent call last):
  File "/data/Kabour/trl/examples/scripts/sft.py", line 54, in <module>
    from trl.commands.cli_utils import init_zero_verbose, SFTScriptArguments, TrlParser
ImportError: cannot import name 'SFTScriptArguments' from 'trl.commands.cli_utils' (/home/user/miniconda/lib/python3.9/site-packages/trl/commands/cli_utils.py)
Traceback (most recent call last):
  File "/data/Kabour/trl/examples/scripts/sft.py", line 54, in <module>
    from trl.commands.cli_utils import init_zero_verbose, SFTScriptArguments, TrlParser
ImportError: cannot import name 'SFTScriptArguments' from 'trl.commands.cli_utils' (/home/user/miniconda/lib/python3.9/site-packages/trl/commands/cli_utils.py)
Traceback (most recent call last):
  File "/data/Kabour/trl/examples/scripts/sft.py", line 54, in <module>
    from trl.commands.cli_utils import init_zero_verbose, SFTScriptArguments, TrlParser
ImportError: cannot import name 'SFTScriptArguments' from 'trl.commands.cli_utils' (/home/user/miniconda/lib/python3.9/site-packages/trl/commands/cli_utils.py)
E0526 17:35:20.329638 140047894131520 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 0 (pid: 2299) of binary: /home/user/miniconda/bin/python
Traceback (most recent call last):
  File "/home/user/miniconda/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/user/miniconda/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
  File "/home/user/miniconda/lib/python3.9/site-packages/accelerate/commands/launch.py", line 1073, in launch_command
    multi_gpu_launcher(args)
  File "/home/user/miniconda/lib/python3.9/site-packages/accelerate/commands/launch.py", line 718, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/user/miniconda/lib/python3.9/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/home/user/miniconda/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/user/miniconda/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
examples/scripts/sft.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-05-26_17:35:20
  host      : r-thinkai-morocco-kya-second-workspace-gdm3hz15-217ae-wb7mh
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 2300)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-05-26_17:35:20
  host      : r-thinkai-morocco-kya-second-workspace-gdm3hz15-217ae-wb7mh
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 2301)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-05-26_17:35:20
  host      : r-thinkai-morocco-kya-second-workspace-gdm3hz15-217ae-wb7mh
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 2302)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-05-26_17:35:20
  host      : r-thinkai-morocco-kya-second-workspace-gdm3hz15-217ae-wb7mh
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2299)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```
I checked for the `SFTScriptArguments` class and as expected it is in the correct file which means that no installation issues occurred

On a side note, i want to inquire also about the possibility to log to `wandb` using something like `--report_to` wandb, tensorboard ... I checked the docs for the available args and this [file](https://github.com/huggingface/trl/blob/main/trl/trainer/model_config.py) but couldn't find any

**Comment by younesbelkada** [comment]
Hi @alielfilali01 
Thanks for the issue ! This is because this commit: https://github.com/huggingface/trl/commit/f30daa4225c2769130c443e21df39b91632f63a7#diff-2080432f96831a8a873745b0f379e5d84422661b7bcba422ba45db53a3a86b8c is not included in your TRL version. I will make a patch release soon, meanwhile you should install TRL from source `pip install -U git+https://github.com/huggingface/trl.git`
