### ISSUE TITLE
DPO with FSDP,  AssertionError: Non-root FSDP

### ISSUE THREAD

**Issue by qZhang88** [huggingface/trl#1704]
Running DPO with FSDP

FSDP config
``` 
compute_environment: LOCAL_MACHINE
debug: false
distributed_type: FSDP
downcast_bf16: 'no'
fsdp_config:
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_backward_prefetch: BACKWARD_PRE
  fsdp_cpu_ram_efficient_loading: true
  fsdp_forward_prefetch: false 
  fsdp_offload_params: true
  fsdp_sharding_strategy: FULL_SHARD
  fsdp_state_dict_type: SHARDED_STATE_DICT
  fsdp_sync_module_states: true
  fsdp_use_orig_params: false
machine_rank: 0
num_machines: 1
num_processes: 2
main_training_function: main
mixed_precision: bf16
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

```bash
[rank0]: Traceback (most recent call last):
[rank0]:   File "/ws/alpha_llms/alignment/DPO/run_dpo.py", line 270, in <module>
[rank0]:     main()
[rank0]:   File "/ws/alpha_llms/alignment/DPO/run_dpo.py", line 261, in main
[rank0]:     trainer.train()
[rank0]:   File "/root/miniconda3/lib/python3.12/site-packages/transformers/trainer.py", line 1885, in train
[rank0]:     return inner_training_loop(
[rank0]:            ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/lib/python3.12/site-packages/transformers/trainer.py", line 2215, in _inner_training_loop
[rank0]:     with self.accelerator.accumulate(model):
[rank0]:   File "/root/miniconda3/lib/python3.12/contextlib.py", line 137, in __enter__
[rank0]:     return next(self.gen)
[rank0]:            ^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/lib/python3.12/site-packages/accelerate/accelerator.py", line 1057, in accumulate
[rank0]:     cm_stack.enter_context(contextlib.nullcontext() if self.sync_gradients else self.no_sync(m))
[rank0]:   File "/root/miniconda3/lib/python3.12/contextlib.py", line 526, in enter_context
[rank0]:     result = _enter(cm)
[rank0]:              ^^^^^^^^^^
[rank0]:   File "/root/miniconda3/lib/python3.12/contextlib.py", line 137, in __enter__
[rank0]:     return next(self.gen)
[rank0]:            ^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/lib/python3.12/site-packages/accelerate/accelerator.py", line 947, in no_sync
[rank0]:     with context():
[rank0]:   File "/root/miniconda3/lib/python3.12/contextlib.py", line 137, in __enter__
[rank0]:     return next(self.gen)
[rank0]:            ^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/lib/python3.12/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 1048, in no_sync
[rank0]:     _lazy_init(self, self)
[rank0]:   File "/root/miniconda3/lib/python3.12/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 138, in _lazy_init
[rank0]:     _share_state_and_init_handle_attrs(state, root_module)
[rank0]:   File "/root/miniconda3/lib/python3.12/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 207, in _share_state_and_init_handle_attrs
[rank0]:     _p_assert(
[rank0]:   File "/root/miniconda3/lib/python3.12/site-packages/torch/distributed/utils.py", line 146, in _p_assert
[rank0]:     raise AssertionError(s)
**[rank0]: AssertionError: Non-root FSDP instance's `_is_root` should not have been set yet or should have been set to `False`**
```

**Comment by qZhang88** [comment]
weird, update transformers from 4.41.0 tp 4.41.2, the error is gone

**Comment by qZhang88** [comment]
weird, update transformers from 4.41.0 tp 4.41.2, the error is gone
