### ISSUE TITLE
Getting "KeyError: None" when passing conversational dataset 

### ISSUE THREAD

**Issue by Kkordik** [huggingface/trl#1777]
So I am trying to create a script to train llama3-8b model on a conversational dataset. As it says in the [HF documentation](https://huggingface.co/docs/trl/en/sft_trainer#dataset-format-support): 

> If your dataset uses one of the above formats, you can directly pass it to the trainer without pre-processing. The [SFTTrainer](https://huggingface.co/docs/trl/v0.9.4/en/sft_trainer#trl.SFTTrainer) will then format the dataset for you using the defined format from the model’s tokenizer with the [apply_chat_template](https://huggingface.co/docs/transformers/main/en/chat_templating#templates-for-chat-models) method.

The dataset I am using is:
[Kkordik/persona-based-chat-messages](https://huggingface.co/datasets/Kkordik/persona-based-chat-messages)

Here is my code:

```python
def train(dataset_id, model_id, max_seq_length):
    max_seq_length = int(max_seq_length)

    bnb_config = None
    # # BitsAndBytesConfig int-4 config
    # bnb_config = BitsAndBytesConfig(
    #     load_in_4bit=True, bnb_4bit_use_double_quant=True, bnb_4bit_quant_type="nf4", bnb_4bit_compute_dtype=torch.bfloat16
    # )
     
    # LoRA config based on QLoRA paper & Sebastian Raschka experiment
    peft_config = LoraConfig(
            lora_alpha=128,
            lora_dropout=0.05,
            r=256,
            bias="none",
            target_modules="all-linear",
            task_type="CAUSAL_LM",
    )
    # SFTConfig for setting max_seq_length and packing
    sft_config = SFTConfig(
        output_dir="test-zerogpu-fine-tune", # directory to save and repository id
        num_train_epochs=3,                  # number of training epochs
        per_device_train_batch_size=3,       # batch size per device during training
        gradient_accumulation_steps=2,       # number of steps before performing a backward/update pass
        gradient_checkpointing=True,         # use gradient checkpointing to save memory
        optim="adamw_torch_fused",           # use fused adamw optimizer
        logging_steps=10,                    # log every 10 steps
        save_strategy="epoch",               # save checkpoint every epoch
        learning_rate=2e-4,                  # learning rate, based on QLoRA paper
        tf32=True,                           # use tf32 precision
        max_grad_norm=0.3,                   # max gradient norm based on QLoRA paper
        warmup_ratio=0.03,                   # warmup ratio based on QLoRA paper
        lr_scheduler_type="constant",        # use constant learning rate scheduler
        push_to_hub=True,                    # push model to hub
        report_to="tensorboard",             # report metrics to tensorboard
        max_seq_length=max_seq_length,  # max sequence length
        # packing=True                         # enable packing
    )

    # Load model and tokenizer
    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        device_map="auto",
        attn_implementation="flash_attention_2",
        torch_dtype=torch.bfloat16,
        quantization_config=bnb_config
    )
    tokenizer = AutoTokenizer.from_pretrained(model_id)
    tokenizer.padding_side = 'right' # to prevent warnings
     
    # set chat template to OAI chatML, remove if you start from a fine-tuned model
    model, tokenizer = setup_chat_format(model, tokenizer)

    # Load dataset
    desired_col = "messages"
    dataset = load_dataset(dataset_id, split="train")


    trainer = SFTTrainer(
        model=model,
        args=sft_config,
        train_dataset=dataset,
        peft_config=peft_config,
        tokenizer=tokenizer,
        dataset_kwargs={
            "add_special_tokens": False,  
            "append_concat_token": False, 
        }
    )

    return "ok"
```

I was following steps described in this article:
https://www.philschmid.de/fine-tune-llms-in-2024-with-trl

But than had to update the code to use `SFTConfig`

And I am getting strange for me error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/spaces/zero/wrappers.py", line 216, in thread_wrapper
    res = future.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/user/app/app.py", line 84, in train
    trainer = SFTTrainer(
  File "/usr/local/lib/python3.10/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/trl/trainer/sft_trainer.py", line 362, in __init__
    train_dataset = self._prepare_dataset(
  File "/usr/local/lib/python3.10/site-packages/trl/trainer/sft_trainer.py", line 508, in _prepare_dataset
    return self._prepare_non_packed_dataloader(
  File "/usr/local/lib/python3.10/site-packages/trl/trainer/sft_trainer.py", line 576, in _prepare_non_packed_dataloader
    tokenized_dataset = dataset.map(
  File "/usr/local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 602, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3156, in map
    for rank, done, content in Dataset._map_single(**dataset_kwargs):
  File "/usr/local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3547, in _map_single
    batch = apply_function_on_filtered_inputs(
  File "/usr/local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3416, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
  File "/usr/local/lib/python3.10/site-packages/trl/trainer/sft_trainer.py", line 547, in tokenize
    element[dataset_text_field] if not use_formatting_func else formatting_func(element),
  File "/usr/local/lib/python3.10/site-packages/datasets/formatting/formatting.py", line 271, in __getitem__
    value = self.data[key]
KeyError: None
```

I could not find anything that could solve my problem and I don't even understand what causes the problem, is it dataset problem or something in args, idk :/

Please help!

**Comment by Kkordik** [comment]
Looks like I had to add, "dataset_text_field="messages"". Please correct me if it is wrong solution.
