### ISSUE TITLE
Phi-3 SFT training and padding tokens

### ISSUE THREAD

**Issue by DavidePaglieri** [huggingface/trl#1802]
Hi, I'm trying to perform SFT training with Phi-3-vision, I followed the example with llava here https://github.com/huggingface/trl/blob/main/examples/scripts/vsft_llava.py. That however didn't work out of the box, as described in #1801 due to some problems with the batch size/how Phi wants the inputs. 

Thus I modified the script to try to make it work, however I encounter the error:
`/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [13,0,0] Assertion 't >= 0 && t < n_classes' failed.`

Upon inspection and after having added some debug prints, it looks like Phi adds some `tokens with value -1`, which are not handled correctly by the SFT trainer.

This is the code I used:
```
from contextlib import nullcontext

from trl.commands.cli_utils import init_zero_verbose, SFTScriptArguments, TrlParser

import torch
from accelerate import Accelerator
from datasets import load_dataset

from tqdm import tqdm

from transformers import AutoTokenizer, AutoProcessor, LlavaForConditionalGeneration, AutoModelForCausalLM

from trl import (
    ModelConfig,
    RichProgressCallback,
    SFTConfig,
    SFTTrainer,
    get_peft_config,
    get_quantization_config,
    get_kbit_device_map,
)

tqdm.pandas()

if __name__ == "__main__":
    parser = TrlParser((SFTScriptArguments, SFTConfig, ModelConfig))
    sft_script_args, training_args, model_config = parser.parse_args_and_config()
    training_args.gradient_checkpointing_kwargs = dict(use_reentrant=False)

    ################
    # Model, Tokenizer & Processor
    ################
    torch_dtype = (
        model_config.torch_dtype
        if model_config.torch_dtype in ["auto", None]
        else getattr(torch, model_config.torch_dtype)
    )
    quantization_config = get_quantization_config(model_config)
    model_kwargs = dict(
        revision=model_config.model_revision,
        trust_remote_code=model_config.trust_remote_code,
        attn_implementation=model_config.attn_implementation,
        torch_dtype=torch_dtype,
        device_map=get_kbit_device_map() if quantization_config is not None else None,
        quantization_config=quantization_config,
    )
    tokenizer = AutoTokenizer.from_pretrained(model_config.model_name_or_path, use_fast=True, trust_remote_code=True)
    processor = AutoProcessor.from_pretrained(model_config.model_name_or_path, trust_remote_code=True)
    processor.tokenizer = tokenizer

    model = AutoModelForCausalLM.from_pretrained(model_config.model_name_or_path, device_map="auto", trust_remote_code=True, _attn_implementation='flash_attention_2')

    class VLMDataCollator:
        def __init__(self, processor):
            self.processor = processor

        def __call__(self, examples):
            texts = []
            images = []
            for example in examples:

                question = example["messages"][0]["content"][0]["text"]
                answer = example["messages"][1]["content"][0]["text"]
                image = example["images"][0]
                
                if question is None or answer is None:
                    continue
                
                messages = [
                    {
                        "role": "user",
                        "content": question +" <|image_1|>"
                    },
                    {
                        "role": "assistant",
                        "content": answer
                    }
                ]
                
                text = self.processor.tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
                texts.append(text)
                images.append(image)
                
                break

            batch = self.processor(text=texts[0], images=images, return_tensors="pt", padding=True)

            labels = batch["input_ids"].clone()
            if self.processor.tokenizer.pad_token_id is not None:
                labels[labels == self.processor.tokenizer.pad_token_id] = -100
            batch["labels"] = labels
            
            max_label_value = torch.max(labels)
            min_label_value = torch.min(labels)
            print(f"Batch max label value: {max_label_value}")
            print(f"Batch min label value: {min_label_value}")
            print("Batch input ids shape:", batch["input_ids"].shape)
            print("Batch labels shape:", batch["labels"].shape)
            print("Batch labels values:", batch["labels"])
            print("Batch input ids values:", batch["input_ids"])


            return batch


    data_collator = VLMDataCollator(processor)

    ################
    # Dataset
    ################
    raw_datasets = load_dataset(sft_script_args.dataset_name)
    train_dataset = raw_datasets[sft_script_args.dataset_train_split]
    eval_dataset = raw_datasets[sft_script_args.dataset_test_split]

    ################
    # Optional rich context managers
    ###############
    init_context = nullcontext() 
    save_context = (
        nullcontext()
    )

    ################
    # Training
    ################
    with init_context:
        trainer = SFTTrainer(
            model=model,
            args=training_args,
            train_dataset=train_dataset,
            eval_dataset=eval_dataset,
            dataset_text_field="text",  # need a dummy field
            tokenizer=tokenizer,
            peft_config=get_peft_config(model_config),
            callbacks=None,
            data_collator=data_collator,
            dataset_kwargs={"skip_prepare_dataset": True},
        )

    trainer.train()

    with save_context:
        trainer.save_model(training_args.output_dir)
        trainer.push_to_hub()
        if Accelerator().is_main_process:
            processor.push_to_hub(training_args.hub_model_id)
```

To run:
```
python vsft_phi.py \
    --dataset_name="HuggingFaceH4/llava-instruct-mix-vsft" \
    --model_name_or_path="microsoft/Phi-3-vision-128k-instruct" \
    --output_dir="data/vsft-llava-1.5-7b-hf" \
    --report_to="wandb" \
    --learning_rate=1.4e-5 \
    --per_device_train_batch_size=8 \
    --gradient_accumulation_steps=1 \
    --output_dir="data/vsft-llava-1.5-7b-hf" \
    --logging_steps=5 \
    --num_train_epochs=1 \
    --push_to_hub \
    --remove_unused_columns=False \
    --torch_dtype=float16 \
    --fp16=True 
```

And this is the full output:

```
Batch max label value: 32010
Batch min label value: -1
Batch input ids shape: torch.Size([1, 1959])
Batch labels shape: torch.Size([1, 1959])
Batch labels values: tensor([[    1, 32010, 29871,  ..., 32007, 29871,    13]])
Batch input ids values: tensor([[    1, 32010, 29871,  ..., 32007, 29871,    13]])
Batch max label value: 32010
Batch min label value: -1
Batch input ids shape: torch.Size([1, 2535])
Batch labels shape: torch.Size([1, 2535])
Batch labels values: tensor([[    1, 32010, 29871,  ..., 32007, 29871,    13]])
Batch input ids values: tensor([[    1, 32010, 29871,  ..., 32007, 29871,    13]])
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [13,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [14,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [15,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [16,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [17,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [18,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [19,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [20,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [21,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [22,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [23,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [24,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [25,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [26,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [27,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [28,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [29,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [30,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [31,0,0] Assertion `t >= 0 && t < n_classes` failed.
Traceback (most recent call last):
  File "/root/fmrl/vsft_phi.py", line 140, in <module>
    trainer.train()
  File "/root/container-venv/lib/python3.10/site-packages/trl/trainer/sft_trainer.py", line 440, in train
    output = super().train(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/transformers/trainer.py", line 1850, in train
    return inner_training_loop(
  File "/root/.local/lib/python3.10/site-packages/transformers/trainer.py", line 2203, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/root/.local/lib/python3.10/site-packages/transformers/trainer.py", line 3138, in training_step
    loss = self.compute_loss(model, inputs)
  File "/root/.local/lib/python3.10/site-packages/transformers/trainer.py", line 3161, in compute_loss
    outputs = model(**inputs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1536, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/accelerate/utils/operations.py", line 822, in forward
    return model_forward(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/accelerate/utils/operations.py", line 810, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/microsoft/Phi-3-vision-128k-instruct/7b92b8c62807f5a98a9fa47cdfd4144f11fbd112/modeling_phi3_v.py", line 1330, in forward
    loss = loss_fct(shift_logits, shift_labels)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1536, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/loss.py", line 1185, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/functional.py", line 3086, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

I'm using:
```
transformers == 4.40.2
trl == 0.9.4
```

**Comment by DavidePaglieri** [comment]
Hi @qgallouedec, are there any plans to support Phi-3 and other VLMs more broadly? The problem arises because Phi-3 has inputs tokens corresponding to the image size equal to -1, for example:

`[[1, 32010, 13, -1, -1, -1, -1,  [.......] -1, -1, -1, -1, 13, 32001]]`

However the transformers Trainer doesn't expect any negative tokens other than the -100 padding token at the moment. 

Llava on the other hand doesn't have any -1 tokens, instead it uses specific tokens that say when the image starts and when it ends, something like:

`[[1, 733, 16289, 28793, 28705, 32000, 28705, 28792, 28748, 16289, 28793]]`

Where `32000, 28705` represent the image.

Would it be possible to create a trainer that works with Phi and other VLMs as well?

**Comment by DavidePaglieri** [comment]
By the way, the solution to the above is simply setting the labels to -100 instead of -1 in the collator, something like `labels[labels <0] = -100 ` will work. The problem remaining is what if we want to finetune the vision model as well? This would likely prevent it from happening.

**Comment by qgallouedec** [comment]
Thank you for your question. Currently, Phi3 support is not a priority.
But I've been looking into it, and the main thing is to modify the collate function to adapt it to the specific functioning of Phi3 :

```python
from try.trainer.utils import pad

def collate_fn(examples):
    # update the "messages" key of every example
    # from
    # [
    #     {"content": [{"text": "Who is the author of this book?\n", "type": "text"}, {"type": "image"}], "role": "user"},
    #     {"content": [{"text": "Paul M. Franklin", "type": "text"}], "role": "assistant"},
    #     {"content": [{"text": "What is the title of this book?", "type": "text"}], "role": "user"},
    # ],
    # to
    # [
    #     {"content": "Who is the author of this book?\n<|image_1|>"", "role": "user"},
    #     {"content": "Paul M. Franklin", "role": "assistant"},
    #     {"content": "What is the title of this book?", "role": "user"},
    # ]
    for batch_idx, example in enumerate(examples):
        for j, message in enumerate(example["messages"]):
            s = ""
            for text_or_image in message["content"]:
                if text_or_image["type"] == "image":
                    s += "<|image_1|>"
                else:
                    s += text_or_image["text"]
            examples[batch_idx]["messages"][j] = {"content": s, "role": message["role"]}

    # Get the texts and images, and apply the chat template
    texts = [processor.apply_chat_template(example["messages"], tokenize=False) for example in examples]
    images = [example["images"][0] for example in examples]

    # Tokenize the texts and process the images
    batch = [processor(text, image, return_tensors="pt") for text, image in zip(texts, images)]

    # pad and collate
    batch = {
        "input_ids": pad([item["input_ids"] for item in batch], padding_value=processor.tokenizer.pad_token_id),
        "attention_mask": pad([item["attention_mask"] for item in batch], padding_value=0),
        "pixel_values": pad([item["pixel_values"][0] for item in batch], padding_value=0),
        "image_sizes": torch.cat([item["image_sizes"] for item in batch]),
    }

    # The labels are the input_ids, and we mask the padding tokens in the loss computation
    labels = batch["input_ids"].clone()
    labels[labels == processor.tokenizer.pad_token_id] = -100
    batch["labels"] = labels

    return batch
```

Note that there's still a problem (`cu_seqlens_q must have shape (batch_size + 1)`), which I can't solve at the moment, but we invite all contributors to share their script if they manage to get it working.

**Comment by GoGoJoestar** [comment]
I noticed that your labels are the same as input_ids，which contain -1 for the place of image tokens. Maybe you can set these labels to -100, or only set the answer's labels not equal -100. Calculate loss on image token’s label, -1, is meaningless because they are just placeholder.

**Comment by DavidePaglieri** [comment]
Yes that's what I did.

**Comment by qgallouedec** [comment]
Good! Can you share your collate function by any chance?
