### ISSUE TITLE
running rloo.py  got.  RuntimeError: CUDA error: device-side assert triggered  

### ISSUE THREAD

**Issue by tsbiosky** [huggingface/trl#1821]
try to running rloo.py under  examples/scripts/   with Qwen as  Policy model

python  rloo.py \
    --learning_rate 3e-6 \
    --num_ppo_epochs 1 \
    --num_mini_batches 1 \
    --output_dir /workspace/my_folder/rloo_test \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --total_episodes 10000 \
    --model_name_or_path /workspace/my_folder/Qwen/Qwen1.5-0.5B-Chat/ \
    --reward_model_path  EleutherAI/pythia-1b-deduped \
    --non_eos_penalty

../aten/src/ATen/native/cuda/Indexing.cu:1290: indexSelectLargeIndex: block: [121,0,0], thread: [94,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1290: indexSelectLargeIndex: block: [121,0,0], thread: [95,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Traceback (most recent call last):
  File "/workspace/user_code/rloo.py", line 151, in <module>
    trainer.train()
  File "/data/miniconda3/envs/rloo/lib/python3.10/site-packages/trl/trainer/rloo_trainer.py", line 282, in train
    _, score, _ = get_reward(
  File "/data/miniconda3/envs/rloo/lib/python3.10/site-packages/trl/trainer/utils.py", line 1035, in get_reward
    output = lm_backbone(
  File "/data/miniconda3/envs/rloo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/miniconda3/envs/rloo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/miniconda3/envs/rloo/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 939, in forward
    attention_mask = _prepare_4d_causal_attention_mask_for_sdpa(
  File "/data/miniconda3/envs/rloo/lib/python3.10/site-packages/transformers/modeling_attn_mask_utils.py", line 372, in _prepare_4d_causal_attention_mask_for_sdpa
    ignore_causal_mask = AttentionMaskConverter._ignore_causal_mask_sdpa(
  File "/data/miniconda3/envs/rloo/lib/python3.10/site-packages/transformers/modeling_attn_mask_utils.py", line 279, in _ignore_causal_mask_sdpa
    elif (is_training or not is_tracing) and torch.all(attention_mask == 1):
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by vwxyzjn** [comment]
The problem is 

```
--model_name_or_path /workspace/my_folder/Qwen/Qwen1.5-0.5B-Chat/
--reward_model_path EleutherAI/pythia-1b-deduped
```

The models have to use the same tokenizers.
