### ISSUE TITLE
CUDA error in PPO Trainer

### ISSUE THREAD

**Issue by neil-tan** [huggingface/trl#1867]
The following script is taken from the PPO trainer documentation page. It is modified to GPT2 as the base model and `OpenAssistant/reward-model-deberta-v3-large-v2` as the reward model.

transformers 4.42.3
trl 0.9.6

The error message:

```shell


...

../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [259,0,0], thread: [30,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [259,0,0], thread: [31,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
 19%|███████████████████████████                                                                                                                     | 3/16 [00:12<00:54,  4.20s/it]
epoch:   0%|                                                                                                                                                 | 0/10 [00:12<?, ?it/s]
Traceback (most recent call last):
  File "/home/neil/code/nmod/chatbot/rlhf_minimal.py", line 99, in <module>
    stats = ppo_trainer.step(query_tensors, response_tensors, rewards)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neil/.pyenv/versions/3.11.0/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)

...

 File "/home/neil/.pyenv/versions/3.11.0/envs/nmod/lib/python3.11/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 1421, in forward
    transformer_outputs = self.transformer(
                          ^^^^^^^^^^^^^^^^^
  File "/home/neil/.pyenv/versions/3.11.0/envs/nmod/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neil/.pyenv/versions/3.11.0/envs/nmod/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neil/.pyenv/versions/3.11.0/envs/nmod/lib/python3.11/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 1144, in forward
    attention_mask = _prepare_4d_causal_attention_mask_for_sdpa(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neil/.pyenv/versions/3.11.0/envs/nmod/lib/python3.11/site-packages/transformers/modeling_attn_mask_utils.py", line 372, in _prepare_4d_causal_attention_mask_for_sdpa
    ignore_causal_mask = AttentionMaskConverter._ignore_causal_mask_sdpa(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neil/.pyenv/versions/3.11.0/envs/nmod/lib/python3.11/site-packages/transformers/modeling_attn_mask_utils.py", line 279, in _ignore_causal_mask_sdpa
    elif (is_training or not is_tracing) and torch.all(attention_mask == 1):
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

The training script:

```python
from datasets import load_dataset
from trl import PPOConfig
from transformers import pipeline
from trl import PPOTrainer
from trl import AutoModelForCausalLMWithValueHead, PPOConfig, PPOTrainer, create_reference_model
import torch
from tqdm import tqdm
from transformers import AutoTokenizer
from transformers import set_seed

set_seed(42)
torch.manual_seed(42)

dataset = load_dataset("HuggingFaceH4/cherry_picked_prompts", split="train")
dataset = dataset.rename_column("prompt", "query")
dataset = dataset.remove_columns(["meta", "completion"])

model = AutoModelForCausalLMWithValueHead.from_pretrained("gpt2")
tokenizer = AutoTokenizer.from_pretrained("gpt2")
tokenizer.pad_token = tokenizer.eos_token

def tokenize(sample):
    sample["input_ids"] = tokenizer(sample["query"])['input_ids']
    return sample

def custom_collate_fn(data):
    input_ids = [torch.tensor(d["input_ids"]) for d in data]
    input_ids = torch.stack(input_ids)
    
    query = [d["query"] for d in data]
    result = {"query": query, "input_ids": input_ids}
    return result
    

dataset = dataset.map(tokenize, batched=False)

config = PPOConfig(
    batch_size=1,
    mini_batch_size=1,
    learning_rate=1.41e-5,
)

ppo_trainer = PPOTrainer(
    model=model,
    config=config,
    dataset=dataset,
    tokenizer=tokenizer,
    data_collator=custom_collate_fn,
)

generation_kwargs = {
    "min_length": -1,
    "max_length": 1024,
    "top_k": 0.0,
    "top_p": 1.0,
    "do_sample": True,
    "pad_token_id": tokenizer.eos_token_id,
}

reward_model = pipeline("text-classification", model="OpenAssistant/reward-model-deberta-v3-large-v2", device="cuda")

epochs = 10
for epoch in tqdm(range(epochs), "epoch: "):
    for batch in tqdm(ppo_trainer.dataloader): 
        query_tensors = batch["input_ids"]
        query_tensors = [query_tensors[i] for i in range(query_tensors.shape[0])]
    
        #### Get response from SFTModel
        
        response_tensors = ppo_trainer.generate(query_tensors, **generation_kwargs)
        batch["response"] = [tokenizer.decode(r.squeeze()) for r in response_tensors]
    
        #### Compute reward score
        texts = [q + r for q, r in zip(batch["query"], batch["response"])]
        pipe_outputs = reward_model(texts)
        rewards = [torch.tensor(output["score"]) for output in pipe_outputs]
        
        #
        q_shapes = [t.shape for t in query_tensors]
        r_shape = [t.shape for t in response_tensors]
    
        #### Run PPO step
        stats = ppo_trainer.step(query_tensors, response_tensors, rewards)
        ppo_trainer.log_stats(stats, batch, rewards)

#### Save model
ppo_trainer.save_pretrained("my_ppo_model")

```

**Comment by qgallouedec** [comment]
Thanks for reporting, sorry for the late reply.
The reason is that the max number of generated token is too high for this model:

```python
    "max_length": 1024,
```

GPT-2 can only handle 1024 tokens, and the input (prompt + generation) must to fit in this window.

The solution is to decrease this value. Eg:

```python
    "max_length": 512,
```
