### ISSUE TITLE
[Bug][OnlineDPO] Far too many checkpoints are saved 

### ISSUE THREAD

**Issue by edbeeching** [huggingface/trl#1889]
There is a bug with the `OnlineDPOTrainer` and using `--save_strategy=steps` , I trained a model with `--save_steps=200` , for the first 1800 steps the checkpointing was correct. After that it saved a checkpoint every 2 steps, causing me to write 12TB of data to disc on the HF cluster.

Command to replicate (on a 8 GPU node)
```
accelerate launch --config_file examples/accelerate_configs/deepspeed_zero3.yaml \
    examples/scripts/online_dpo.py \
    --dataset_name=trl-internal-testing/tldr-preference-sft-trl-style \
    --learning_rate=3e-6 \
    --output_dir=data/online_dpo/EleutherAI_pythia-1b \
    --per_device_train_batch_size=16 \
    --gradient_accumulation_steps=4 \
    --total_episodes=1000000 \
    --local_rollout_forward_batch_size=8 \
    --model_name_or_path=cleanrl/EleutherAI_pythia-1b-deduped__sft__tldr \
    --reward_model_path=cleanrl/EleutherAI_pythia-1b-deduped__reward__tldr \
    --non_eos_penalty \
    --stop_token=eos \
    --response_length=53 \
    --save_strategy=steps \
    --save_steps=200 \
    --num_epochs=1 \
    --num_total_batches=1 \
    --beta=0.1 \
    --push_to_hub

```

**Comment by lewtun** [comment]
There's a deeper issue with being able to save checkpoints on `main`. Setting `save_steps=1` in the OP command gives:

```
Traceback (most recent call last):
  File "/fsx/lewis/git/hf/trl/examples/scripts/online_dpo.py", line 133, in <module>
    trainer.train()
  File "/fsx/lewis/git/hf/trl/trl/trainer/online_dpo_trainer.py", line 514, in train
    self._save_checkpoint(model, trial=None, metrics=metrics)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/transformers/trainer.py", line 2660, in _save_checkpoint
    self._save_optimizer_and_scheduler(output_dir)
  File "/fsx/lewis/miniconda3/envs/trl/lib/python3.10/site-packages/transformers/trainer.py", line 2746, in _save_optimizer_and_scheduler
    inspect.signature(self.model_wrapped.save_checkpoint).parameters.keys()
AttributeError: 'OnlineDPOTrainer' object has no attribute 'model_wrapped'
```

**Comment by lewtun** [comment]
I can reproduce the checkpointing issue with a smaller set of steps:

```
accelerate launch --config_file examples/accelerate_configs/deepspeed_zero3.yaml     examples/scripts/online_dpo.py     --dataset_name=trl-internal-testing/tldr-preference-sft-trl-style     --learning_rate=3e-6     --output_dir=data/online_dpo/EleutherAI_pythia-1b     --per_device_train_batch_size=16     --gradient_accumulation_steps=4     --total_episodes=10000     --local_rollout_forward_batch_size=8     --model_name_or_path=cleanrl/EleutherAI_pythia-1b-deduped__sft__tldr     --reward_model_path=cleanrl/EleutherAI_pythia-1b-deduped__reward__tldr     --non_eos_penalty     --stop_token=eos     --response_length=53     --save_strategy=steps     --save_steps=4     --num_epochs=1     --num_total_batches=1     --beta=0.1
```

What seems to be happening is that `self.state.global_step` is being incremented incorrectly, so e.g. in the above example we expect to have

```
num_steps = total_episodes / (num_gpus * per_device_train_batch_size * gradient_accumulation_steps) = 1000 / (8 * 16 * 4) = 20
```

and thus checkpoints should be saved at `global_step = 4, 8, ... , 20`. Instead we find checkpoints saved at `global_step = 4, 8, ..., 20, 22, 24, ..., 40`
