### ISSUE TITLE
Error in PPOv2

### ISSUE THREAD

**Issue by ZhichaoWang970201** [huggingface/trl#1953]
I met the following error in PPOv2. Would you mind providing me some hints on why that happens?

Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/bigmodel_dpo_exps/Zhichao_PPO_trl/trl/examples/scripts/ppo/ppo_tldr-ultrafeedback.py", line 138, in <module>
  File "/home/ec2-user/SageMaker/bigmodel_dpo_exps/Zhichao_PPO_trl/trl/examples/scripts/ppo/ppo_tldr-ultrafeedback.py", line 138, in <module>
    trainer.train()
  File "/home/ec2-user/SageMaker/bigmodel_dpo_exps/Zhichao_PPO_trl/trl/trl/trainer/ppov2_trainer.py", line 535, in train
        trainer.train()trainer.train()

  File "/home/ec2-user/SageMaker/bigmodel_dpo_exps/Zhichao_PPO_trl/trl/trl/trainer/ppov2_trainer.py", line 535, in train
  File "/home/ec2-user/SageMaker/bigmodel_dpo_exps/Zhichao_PPO_trl/trl/trl/trainer/ppov2_trainer.py", line 535, in train
Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/bigmodel_dpo_exps/Zhichao_PPO_trl/trl/examples/scripts/ppo/ppo_tldr-ultrafeedback.py", line 138, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/bigmodel_dpo_exps/Zhichao_PPO_trl/trl/examples/scripts/ppo/ppo_tldr-ultrafeedback.py", line 138, in <module>
  File "/home/ec2-user/SageMaker/bigmodel_dpo_exps/Zhichao_PPO_trl/trl/examples/scripts/ppo/ppo_tldr-ultrafeedback.py", line 138, in <module>
  File "/home/ec2-user/SageMaker/bigmodel_dpo_exps/Zhichao_PPO_trl/trl/examples/scripts/ppo/ppo_tldr-ultrafeedback.py", line 138, in <module>
    self._save_checkpoint(model, trial=None, metrics=metrics)
  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/transformers/trainer.py", line 2886, in _save_checkpoint
    self._save_checkpoint(model, trial=None, metrics=metrics)    
self._save_checkpoint(model, trial=None, metrics=metrics)  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/transformers/trainer.py", line 2886, in _save_checkpoint

  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/transformers/trainer.py", line 2886, in _save_checkpoint
    trainer.train()Traceback (most recent call last):

  File "/home/ec2-user/SageMaker/bigmodel_dpo_exps/Zhichao_PPO_trl/trl/trl/trainer/ppov2_trainer.py", line 535, in train
  File "/home/ec2-user/SageMaker/bigmodel_dpo_exps/Zhichao_PPO_trl/trl/examples/scripts/ppo/ppo_tldr-ultrafeedback.py", line 138, in <module>
        trainer.train()trainer.train()

    trainer.train()  File "/home/ec2-user/SageMaker/bigmodel_dpo_exps/Zhichao_PPO_trl/trl/trl/trainer/ppov2_trainer.py", line 535, in train
  File "/home/ec2-user/SageMaker/bigmodel_dpo_exps/Zhichao_PPO_trl/trl/trl/trainer/ppov2_trainer.py", line 535, in train

  File "/home/ec2-user/SageMaker/bigmodel_dpo_exps/Zhichao_PPO_trl/trl/trl/trainer/ppov2_trainer.py", line 535, in train
    trainer.train()
  File "/home/ec2-user/SageMaker/bigmodel_dpo_exps/Zhichao_PPO_trl/trl/trl/trainer/ppov2_trainer.py", line 535, in train
    self._save_checkpoint(model, trial=None, metrics=metrics)
  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/transformers/trainer.py", line 2886, in _save_checkpoint
        self._save_checkpoint(model, trial=None, metrics=metrics)self._save_checkpoint(model, trial=None, metrics=metrics)    

self._save_checkpoint(model, trial=None, metrics=metrics)  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/transformers/trainer.py", line 2886, in _save_checkpoint
  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/transformers/trainer.py", line 2886, in _save_checkpoint

  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/transformers/trainer.py", line 2886, in _save_checkpoint
    self._save_checkpoint(model, trial=None, metrics=metrics)
  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/transformers/trainer.py", line 2886, in _save_checkpoint
        self.save_model(output_dir, _internal_call=True)self.save_model(output_dir, _internal_call=True)    

self.save_model(output_dir, _internal_call=True)  File "/home/ec2-user/SageMaker/bigmodel_dpo_exps/Zhichao_PPO_trl/trl/trl/trainer/ppov2_trainer.py", line 230, in save_model
  File "/home/ec2-user/SageMaker/bigmodel_dpo_exps/Zhichao_PPO_trl/trl/trl/trainer/ppov2_trainer.py", line 230, in save_model

  File "/home/ec2-user/SageMaker/bigmodel_dpo_exps/Zhichao_PPO_trl/trl/trl/trainer/ppov2_trainer.py", line 230, in save_model
        state_dict = self.accelerator.get_state_dict(self.backup_model)state_dict = self.accelerator.get_state_dict(self.backup_model)
    
state_dict = self.accelerator.get_state_dict(self.backup_model)  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/accelerate/accelerator.py", line 3287, in get_state_dict

  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/accelerate/accelerator.py", line 3287, in get_state_dict
  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/accelerate/accelerator.py", line 3287, in get_state_dict
            self.save_model(output_dir, _internal_call=True)self.save_model(output_dir, _internal_call=True)    self.save_model(output_dir, _internal_call=True)

self.save_model(output_dir, _internal_call=True)
  File "/home/ec2-user/SageMaker/bigmodel_dpo_exps/Zhichao_PPO_trl/trl/trl/trainer/ppov2_trainer.py", line 230, in save_model

  File "/home/ec2-user/SageMaker/bigmodel_dpo_exps/Zhichao_PPO_trl/trl/trl/trainer/ppov2_trainer.py", line 230, in save_model
  File "/home/ec2-user/SageMaker/bigmodel_dpo_exps/Zhichao_PPO_trl/trl/trl/trainer/ppov2_trainer.py", line 230, in save_model
  File "/home/ec2-user/SageMaker/bigmodel_dpo_exps/Zhichao_PPO_trl/trl/trl/trainer/ppov2_trainer.py", line 230, in save_model
    self.save_model(output_dir, _internal_call=True)
  File "/home/ec2-user/SageMaker/bigmodel_dpo_exps/Zhichao_PPO_trl/trl/trl/trainer/ppov2_trainer.py", line 230, in save_model
    state_dict = self.accelerator.get_state_dict(self.backup_model)
        state_dict = self.accelerator.get_state_dict(self.backup_model)    state_dict = self.accelerator.get_state_dict(self.backup_model)  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/accelerate/accelerator.py", line 3287, in get_state_dict

state_dict = self.accelerator.get_state_dict(self.backup_model)
  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/accelerate/accelerator.py", line 3287, in get_state_dict

  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/accelerate/accelerator.py", line 3287, in get_state_dict
  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/accelerate/accelerator.py", line 3287, in get_state_dict
    state_dict = self.accelerator.get_state_dict(self.backup_model)
  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/accelerate/accelerator.py", line 3287, in get_state_dict
            state_dict = clone_tensors_for_torch_save(self.unwrap_model(model).state_dict())state_dict = clone_tensors_for_torch_save(self.unwrap_model(model).state_dict())state_dict = clone_tensors_for_torch_save(self.unwrap_model(model).state_dict())

AttributeErrorAttributeErrorAttributeError: : : 'NoneType' object has no attribute 'state_dict''NoneType' object has no attribute 'state_dict''NoneType' object has no attribute 'state_dict'

                    state_dict = clone_tensors_for_torch_save(self.unwrap_model(model).state_dict())state_dict = clone_tensors_for_torch_save(self.unwrap_model(model).state_dict())state_dict = clone_tensors_for_torch_save(self.unwrap_model(model).state_dict())state_dict = clone_tensors_for_torch_save(self.unwrap_model(model).state_dict())state_dict = clone_tensors_for_torch_save(self.unwrap_model(model).state_dict())

AttributeErrorAttributeErrorAttributeError: : AttributeErrorAttributeError: 'NoneType' object has no attribute 'state_dict''NoneType' object has no attribute 'state_dict': : 'NoneType' object has no attribute 'state_dict''NoneType' object has no attribute 'state_dict''NoneType' object has no attribute 'state_dict'

**Comment by qgallouedec** [comment]
Hi, thanks for sharing this feedback. Unfortunately, it's very hard for us to address it because it doesn't follow [the guidelines for reporting a bug](https://github.com/huggingface/trl/blob/main/CONTRIBUTING.md#did-you-find-a-bug). If the problem persists, I invite you to open a new issue with everything we need to work on it: package versions, minimal code to reproduce it, dataset and model links, etc.
