### ISSUE TITLE
DDPO job with Accelerator fails in a multi-gpu node

### ISSUE THREAD

**Issue by shashankg7** [huggingface/trl#2090]
### System Info

- `transformers` version: 4.44.2
- Platform: Linux-5.15.0-1068-aws-x86_64-with-glibc2.31
- Python version: 3.9.19
- Huggingface_hub version: 0.24.7
- Safetensors version: 0.4.5
- Accelerate version: 0.34.2
- Accelerate config:    not found
- PyTorch version (GPU?): 2.4.1+cu121 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using distributed or parallel set-up in script?: Yes, trying in a multiGPU node

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

I am trying to run the DDPO script: https://github.com/huggingface/trl/blob/main/examples/scripts/ddpo.py, on a slurm single node with 4 GPUs using the following job script:

```
#!/bin/bash

#SBATCH --job-name=multigpu
#SBATCH --output=O-%x.%j
#SBATCH --error=E-%x.%j
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1         # number of MP tasks
#SBATCH --gres=gpu:4                # number of GPUs per node
#SBATCH --cpus-per-task=64        # number of cores per tasks
#SBATCH --time=01:59:00             # maximum execution time (HH:MM:SS)

######################
### Set enviroment ###
######################
source /data/home/shashankgupta/miniconda3/etc/profile.d/conda.sh 
conda activate vqdiffuser
export GPUS_PER_NODE=4
######################

export ACCELERATE_DIR="${ACCELERATE_DIR:-/accelerate}"

accelerate launch --num_processes $GPUS_PER_NODE --multi_gpu ddpo.py --num_epochs=200 --train_gradient_accumulation_steps=1 --sample_num_steps=50 --sample_batch_size=6  --train_batch_size=3  --sample_num_batches_per_epoch=4 --train_learning_rate=3e-4 --per_prompt_stat_tracking=True  --mixed_precision=no --per_prompt_stat_tracking_buffer_size=64 --tracker_project_name="stable_diffusion_training" --log_with="wandb"
```

I am getting the following error message across different ranks (pasting from a single rank):

```
[rank3]:   File "/opt/hpcaas/.mounts/fs-074514506a8464fcb/home/shashankgupta/RLHF_Compositionality/ddpo.py", line 208, in <module>
[rank3]:     trainer.train()
[rank3]:   File "/data/home/shashankgupta/miniconda3/envs/vqdiffuser/lib/python3.9/site-packages/trl/trainer/ddpo_trainer.py", line 605, in train
[rank3]:     global_step = self.step(epoch, global_step)
[rank3]:   File "/data/home/shashankgupta/miniconda3/envs/vqdiffuser/lib/python3.9/site-packages/trl/trainer/ddpo_trainer.py", line 267, in step
[rank3]:     self.image_samples_callback(prompt_image_data, global_step, self.accelerator.trackers[0])
[rank3]: IndexError: list index out of range
[rank1]: Traceback (most recent call last):
[rank1]:   File "/opt/hpcaas/.mounts/fs-074514506a8464fcb/home/shashankgupta/RLHF_Compositionality/ddpo.py", line 208, in <module>
[rank1]:     trainer.train()
[rank1]:   File "/data/home/shashankgupta/miniconda3/envs/vqdiffuser/lib/python3.9/site-packages/trl/trainer/ddpo_trainer.py", line 605, in train
[rank1]:     global_step = self.step(epoch, global_step)
[rank1]:   File "/data/home/shashankgupta/miniconda3/envs/vqdiffuser/lib/python3.9/site-packages/trl/trainer/ddpo_trainer.py", line 267, in step
[rank1]:     self.image_samples_callback(prompt_image_data, global_step, self.accelerator.trackers[0])
[rank1]: IndexError: list index out of range
[rank2]: Traceback (most recent call last):
[rank2]:   File "/opt/hpcaas/.mounts/fs-074514506a8464fcb/home/shashankgupta/RLHF_Compositionality/ddpo.py", line 208, in <module>
[rank2]:     trainer.train()
[rank2]:   File "/data/home/shashankgupta/miniconda3/envs/vqdiffuser/lib/python3.9/site-packages/trl/trainer/ddpo_trainer.py", line 605, in train
[rank2]:     global_step = self.step(epoch, global_step)
[rank2]:   File "/data/home/shashankgupta/miniconda3/envs/vqdiffuser/lib/python3.9/site-packages/trl/trainer/ddpo_trainer.py", line 267, in step
[rank2]:     self.image_samples_callback(prompt_image_data, global_step, self.accelerator.trackers[0])
[rank2]: IndexError: list index out of range
```

### Expected behavior

The example script works with a single GPU.

**Comment by TongLiu-github** [comment]
I meet the similar error when working well with a single GPU but failing with more than 1. Did you solve this problem?

**Comment by shashankg7** [comment]
Removed the logging part "self.image_samples_callback(prompt_image_data, global_step, self.accelerator.trackers[0])", and the code worked.
