### ISSUE TITLE
TypeError: DPOTrainer.__init__() got an unexpected keyword argument 'processing_class'

### ISSUE THREAD

**Issue by zhang-tuo-pdf** [huggingface/trl#2226]
### System Info

I am using trl version 0.11.3 by pip installation. I want to reproduce the example code on the huggingface tutorial (https://huggingface.co/docs/trl/main/en/dpo_trainer), but I encounter the error that: TypeError: DPOTrainer.__init__() got an unexpected keyword argument 'processing_class'

This is my code:
```
import torch
from datasets import load_dataset
from transformers import AutoModelForCausalLM, AutoTokenizer

from trl import (
    DPOConfig,
    DPOScriptArguments,
    DPOTrainer,
    ModelConfig,
    TrlParser,
    get_kbit_device_map,
    get_peft_config,
    get_quantization_config,
)

def dpo_training():
    model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen2-0.5B-Instruct", cache_dir='/vault/ultraz/llm_models')
    tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen2-0.5B-Instruct", cache_dir='/vault/ultraz/llm_models')
    preference_example = {"prompt": "The sky is", "chosen": " blue.", "rejected": " green."}
    training_args = DPOConfig(output_dir="Qwen2-0.5B-DPO", logging_steps=10)
    trainer = DPOTrainer(model=model, args=training_args, processing_class=tokenizer, train_dataset=preference_example)
    trainer.train()

if __name__ == "__main__":
    dpo_training()
```

I run it by typing the following command in my terminal:
```
CUDA_VISIBLE_DEVICES=0 accelerate launch dpo_trainer.py
```

I checked the document that DPOTrainer has the argument named "processing_class". Could any one help me to have a look? Also, could I directly pass the raw text data into the DPOTrainer as the training data? Thank you very much!

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

This is my code:
```
import torch
from datasets import load_dataset
from transformers import AutoModelForCausalLM, AutoTokenizer

from trl import (
    DPOConfig,
    DPOScriptArguments,
    DPOTrainer,
    ModelConfig,
    TrlParser,
    get_kbit_device_map,
    get_peft_config,
    get_quantization_config,
)

def dpo_training():
    model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen2-0.5B-Instruct", cache_dir='/vault/ultraz/llm_models')
    tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen2-0.5B-Instruct", cache_dir='/vault/ultraz/llm_models')
    preference_example = {"prompt": "The sky is", "chosen": " blue.", "rejected": " green."}
    training_args = DPOConfig(output_dir="Qwen2-0.5B-DPO", logging_steps=10)
    trainer = DPOTrainer(model=model, args=training_args, processing_class=tokenizer, train_dataset=preference_example)
    trainer.train()

if __name__ == "__main__":
    dpo_training()
```

I run it by typing the following command in my terminal:
```
CUDA_VISIBLE_DEVICES=0 accelerate launch dpo_trainer.py
```

### Expected behavior

```
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `1`
        `--num_machines` was set to a value of `1`
        `--mixed_precision` was set to a value of `'no'`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Traceback (most recent call last):
  File "/vault/ultraz/DPO_FL/dpo_trainer.py", line 25, in <module>
    dpo_training()
  File "/vault/ultraz/DPO_FL/dpo_trainer.py", line 21, in dpo_training
    trainer = DPOTrainer(model=model, args=training_args, processing_class=tokenizer, train_dataset=preference_example)
  File "/home/ultraz/.conda/envs/pretext/lib/python3.10/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
TypeError: DPOTrainer.__init__() got an unexpected keyword argument 'processing_class'
Traceback (most recent call last):
  File "/home/ultraz/.conda/envs/pretext/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/ultraz/.conda/envs/pretext/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
  File "/home/ultraz/.conda/envs/pretext/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1057, in launch_command
    simple_launcher(args)
  File "/home/ultraz/.conda/envs/pretext/lib/python3.10/site-packages/accelerate/commands/launch.py", line 673, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/ultraz/.conda/envs/pretext/bin/python', 'dpo_trainer.py']' returned non-zero exit status 1.
```

**Comment by qgallouedec** [comment]
You're referring to the dev version of the doc (main) while you have v0.11.3 installed. In general, you should either:

Use the doc associated with you version: https://huggingface.co/docs/trl/v0.11.3/en/dpo_trainer
or
Install the dev version `pip install git+https //github.com/huggingface/trl`

Regarding the example code, if you decide to keep v0.11, then make the following modification 

```diff
-     trainer = DPOTrainer(model=model, args=training_args, processing_class=tokenizer, train_dataset=preference_example)
+ -     trainer = DPOTrainer(model=model, args=training_args, tokenizer =tokenizer, train_dataset=preference_example)
```

**Comment by qgallouedec** [comment]
Duplicate #2207 #2218

**Comment by zhang-tuo-pdf** [comment]
Thank you so much! I made the changes based on your suggestions and keep using v0.11. However, I got another error when I am passing the raw text with explicit prompt format into the DPO trainer. The error shows "'dict' object has no attribute 'map'". My code is below:

```
import torch
from datasets import load_dataset
from transformers import AutoModelForCausalLM, AutoTokenizer

from trl import (
    DPOConfig,
    DPOScriptArguments,
    DPOTrainer,
    ModelConfig,
    TrlParser,
    get_kbit_device_map,
    get_peft_config,
    get_quantization_config,
)

def dpo_training():
    model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen2-0.5B-Instruct", cache_dir='/vault/ultraz/llm_models')
    tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen2-0.5B-Instruct", cache_dir='/vault/ultraz/llm_models')
    preference_example = {
        "prompt": [
            "hello",
            "how are you",
            "What is your name?",
            "What is your name?",
            "Which is the best programming language?",
            "Which is the best programming language?",
            "Which is the best programming language?",
        ],
        "chosen": [
            "hi nice to meet you",
            "I am fine",
            "My name is Mary",
            "My name is Mary",
            "Python",
            "Python",
            "Java",
        ],
        "rejected": [
            "leave me alone",
            "I am not fine",
            "Whats it to you?",
            "I dont have a name",
            "Javascript",
            "C++",
            "C++",
        ],
    }
    training_args = DPOConfig(output_dir="Qwen2-0.5B-DPO", logging_steps=10)
    trainer = DPOTrainer(model=model, args=training_args, tokenizer=tokenizer, train_dataset=preference_example)
    trainer.train()

if __name__ == "__main__":
    dpo_training()
```

And then the error message is below:
```
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `1`
        `--num_machines` was set to a value of `1`
        `--mixed_precision` was set to a value of `'no'`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
/home/ultraz/.conda/envs/pretext/lib/python3.10/site-packages/trl/trainer/dpo_trainer.py:660: UserWarning: `max_length` is not set in the DPOConfig's init it will default to `512` by default, but you should do it yourself in the future.
  warnings.warn(
/home/ultraz/.conda/envs/pretext/lib/python3.10/site-packages/trl/trainer/dpo_trainer.py:673: UserWarning: `max_prompt_length` is not set in the DPOConfig's init it will default to `128` by default, but you should do it yourself in the future.
  warnings.warn(
/home/ultraz/.conda/envs/pretext/lib/python3.10/site-packages/trl/trainer/dpo_trainer.py:708: UserWarning: When using DPODataCollatorWithPadding, you should set `remove_unused_columns=False` in your TrainingArguments we have set it for you, but you should do it yourself in the future.
  warnings.warn(
Traceback (most recent call last):
  File "/vault/ultraz/DPO_FL/dpo_trainer.py", line 53, in <module>
    dpo_training()
  File "/vault/ultraz/DPO_FL/dpo_trainer.py", line 49, in dpo_training
    trainer = DPOTrainer(model=model, args=training_args, tokenizer=tokenizer, train_dataset=preference_example)
  File "/home/ultraz/.conda/envs/pretext/lib/python3.10/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "/home/ultraz/.conda/envs/pretext/lib/python3.10/site-packages/trl/trainer/dpo_trainer.py", line 804, in __init__
    train_dataset = train_dataset.map(
AttributeError: 'dict' object has no attribute 'map'
Traceback (most recent call last):
  File "/home/ultraz/.conda/envs/pretext/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/ultraz/.conda/envs/pretext/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
  File "/home/ultraz/.conda/envs/pretext/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1057, in launch_command
    simple_launcher(args)
  File "/home/ultraz/.conda/envs/pretext/lib/python3.10/site-packages/accelerate/commands/launch.py", line 673, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/ultraz/.conda/envs/pretext/bin/python', 'dpo_trainer.py']' returned non-zero exit status 1.
```

**Comment by qgallouedec** [comment]
This is another thing, please open another issue next time.
`preference_example` is an dict, but `train_dataset` is expected to be a `datasets.Dataset` you need to convert it into a dataset via the `datasets.Dataset.from_dict(preference_example)`.
