### ISSUE TITLE
online DPO evaluation

### ISSUE THREAD

**Issue by woshizouguo** [huggingface/trl#2228]
### System Info

trl=0.11.2

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

for [online dpo code](https://github.com/huggingface/trl/blob/47d08a962679ba0f6ca1b94c0902479525235512/examples/scripts/dpo_online.py#L16-L15)

If I add `--eval_steps=5` and `--eval_strategy=steps`, it shows error:
```
  File "/mnt/task_runtime/trl/examples/scripts/dpo_online.py", line 120, in <module>
    trainer.train()
  File "/opt/miniconda/lib/python3.9/site-packages/transformers/trainer.py", line 1938, in train
    return inner_training_loop(
  File "/opt/miniconda/lib/python3.9/site-packages/transformers/trainer.py", line 2356, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, grad_norm, model, trial, epoch, ignore_keys_for_eval)
  File "/mnt/task_runtime/trl/trl/trainer/online_dpo_trainer.py", line 555, in _maybe_log_save_evaluate
    metrics = self._evaluate(trial, ignore_keys_for_eval)
  File "/opt/miniconda/lib/python3.9/site-packages/transformers/trainer.py", line 2761, in _evaluate
    metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)
  File "/opt/miniconda/lib/python3.9/site-packages/transformers/trainer.py", line 3666, in evaluate
    output = eval_loop(
  File "/opt/miniconda/lib/python3.9/site-packages/transformers/trainer.py", line 3857, in evaluation_loop
    losses, logits, labels = self.prediction_step(model, inputs, prediction_loss_only, ignore_keys=ignore_keys)
  File "/opt/miniconda/lib/python3.9/site-packages/transformers/trainer.py", line 4085, in prediction_step
    outputs = model(**inputs)
  File "/opt/miniconda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/miniconda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/miniconda/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 186, in forward
    outputs = self.parallel_apply(replicas, inputs, module_kwargs)
  File "/opt/miniconda/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 201, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/opt/miniconda/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 109, in parallel_apply
    output.reraise()
  File "/opt/miniconda/lib/python3.9/site-packages/torch/_utils.py", line 706, in reraise
    raise exception
TypeError: Caught TypeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/opt/miniconda/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 84, in _worker
    output = module(*input, **kwargs)
  File "/opt/miniconda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/miniconda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: forward() got an unexpected keyword argument 'prompt'
```

### Expected behavior

The eval is not using the correct input dataset.

**Comment by kashif** [comment]
@wenxindongwork  I suspect we will need to have our own `prediction_step` method as we use our own datacollator instead of the default one, and the tests didn't catch this bug since the `eval_steps` in the tests were > the `max_steps` so it never ran the evaluation...

**Comment by suanflower** [comment]
same　ｅｒｒｏｒ

**Comment by Hjhirp** [comment]
I am also getting same error!

**Comment by albertvillanova** [comment]
Hey @woshizouguo, sorry for the very long delay on this — catching up on the backlog. 

This is a real bug and still present on current main: `OnlineDPOTrainer` (now under `trl.experimental.online_dpo`, see https://github.com/huggingface/trl/blob/51c6d3ca31fb4cc80ff719c0844bbdfcd0feeefb/trl/experimental/online_dpo/online_dpo_trainer.py) defaults `remove_unused_columns=False` and ships its own `DPODataCollatorWithPadding` (https://github.com/huggingface/trl/blob/51c6d3ca31fb4cc80ff719c0844bbdfcd0feeefb/trl/experimental/utils.py#L51-L128), but doesn't override `prediction_step` — so HF Trainer's default eval path ends up calling `model(**inputs)` with the raw `prompt` column still attached.

@qgallouedec had taken a stab at fixing it in #2476 and let it go stale; need to revive that work. Tracking #2464 as a duplicate. Keeping this open.

**Comment by he-yufeng** [comment]
I reproduced this on current `main` and am reviving the fix with a narrower current-code approach: split OnlineDPO loss computation from the training-only backward pass, then add a `prediction_step` that reuses the same loss under `no_grad`. I am also adding a regression that calls `trainer.evaluate()` and verifies it returns `eval_loss` without creating gradients.

**Comment by behroozazarkhalili** [comment]
Opened PR #6950 for this issue. It fixes OnlineDPOTrainer, NashMDTrainer and XPOTrainer, since the two subclasses override `training_step` rather than inheriting it.

The root cause is that `Trainer.prediction_step` gates on `has_labels or loss_without_labels`, and for these trainers `label_names` is `["labels"]` while an evaluation batch carries only prompts, so both terms are False and `compute_loss` is never reached. That also means renaming `training_step` to `compute_loss` is not sufficient on current transformers.

Credit to the earlier attempts by @kashif (#2231), @qgallouedec (#2476) and @mukund1985 (#6122), all closed for inactivity rather than on technical grounds.
