### ISSUE TITLE
PPOv2Trainer using reward function, reward_model has no attribute 'modules'

### ISSUE THREAD

**Issue by j-murel** [huggingface/trl#2273]
### System Info

```
Package            Version
------------------ -----------
accelerate         1.0.0
aiohappyeyeballs   2.4.3
aiohttp            3.10.10
aiosignal          1.3.1
attrs              24.2.0
Brotli             1.0.9
certifi            2024.8.30
charset-normalizer 3.3.2
contourpy          1.3.0
cycler             0.12.1
datasets           3.0.2
dill               0.3.8
docstring_parser   0.16
filelock           3.13.1
fonttools          4.54.1
frozenlist         1.5.0
fsspec             2024.9.0
huggingface-hub    0.25.2
idna               3.7
Jinja2             3.1.4
kiwisolver         1.4.7
lxml               5.3.0
markdown-it-py     3.0.0
MarkupSafe         2.1.3
matplotlib         3.9.2
mdurl              0.1.2
mkl_fft            1.3.10
mkl_random         1.2.7
mkl-service        2.4.0
mpmath             1.3.0
multidict          6.1.0
multiprocess       0.70.16
networkx           3.3
numpy              1.26.4
packaging          24.1
pandas             2.2.3
pillow             10.4.0
pip                24.2
propcache          0.2.0
psutil             6.0.0
pyarrow            17.0.0
Pygments           2.18.0
pyparsing          3.1.4
PySocks            1.7.1
python-dateutil    2.9.0.post0
pytz               2024.2
PyYAML             6.0.2
regex              2024.9.11
requests           2.32.3
rich               13.9.3
safetensors        0.4.5
setuptools         75.1.0
shtab              1.7.1
six                1.16.0
sympy              1.13.2
tk                 0.1.0
tokenizers         0.20.1
torch              2.4.1
torchvision        0.19.1
tqdm               4.66.5
transformers       4.45.2
triton             3.0.0
trl                0.11.4
typing_extensions  4.11.0
tyro               0.8.14
tzdata             2024.2
urllib3            2.2.3
wheel              0.44.0
xxhash             3.5.0
yarl               1.16.0
```

### Information

- [X] The official example scripts
- [x] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

I am trying to use the trl library to improve a locally pre-trained custom BERT-based model for masked language modeling tasks. I do not have a pre-existing reward model, and so I am trying to use a reward function for RLHF. Here is my current script that loads my human-annotated data and fine-tunes the BERT model with reinforcement learning:

```
from transformers import BertTokenizer, BertForMaskedLM
from trl import PPOv2Trainer, PPOv2Config
import torch
from torch.utils.data import Dataset
import os
import json
import logging

cache_dir = 'dir/to/cached/models'
tokenizer_cache_path = os.path.join(cache_dir, 'bert_tokenizer')
model_cache_path = os.path.join(cache_dir, 'bert_model')
ref_policy_path = "dir/to/ref/policy/model"
tokenizer = BertTokenizer.from_pretrained(tokenizer_cache_path)
model = BertForMaskedLM.from_pretrained(model_cache_path)
ref_policy = BertForMaskedLM.from_pretrained(ref_policy_path)

hf_data_path = "path/to/json/hf/data.json"
with open(hf_data_path, 'r', encoding='utf-8') as f:
    hf_data = json.load(f)

# CUDA setup
print(f"CUDA available: {torch.cuda.is_available()}")
print(f"CUDA version: {torch.version.cuda}")
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(f"Using device {device}.")
model.to(device)
ref_policy.to(device)
print(f"Tokenizer type: {type(tokenizer)}")
print(f"Model type: {type(model)}")
print(f"Reference policy type: {type(ref_policy)}")


logging.basicConfig(level=logging.INFO)

def reward(prediction, label):
    if label == "GOOD FLAG.":
        return 1.0
    elif label == "BAD FLAG.":
        return -1.0
    elif label == "PLAUSIBLE FLAG.":
        return 0.5
    else:
        return 0.0
    
def preprocess_data(data_point):
    text = data_point["Text"]
    transmitted_word = data_point["Transmitted Word"]
    word_index = data_point["Word Index in Text"]
    
    inputs = tokenizer(text, return_tensors='pt')

    # check word_index valid in tokenized length
    if word_index >= inputs['input_ids'].shape[1]:
        raise ValueError(f"word_index {word_index} exceeds token count {inputs['input_ids'].shape[1]}")

    # flatten tensor index to set mask token
    mask_token_index = torch.tensor([word_index])
    inputs['input_ids'][0, mask_token_index.item()] = tokenizer.mask_token_id 

    correct_token = tokenizer.convert_tokens_to_ids([data_point["Transmitted Word"]])[0] 

    inputs = {key: tensor.to(device) for key, tensor in inputs.items()}

    return inputs, transmitted_word, data_point["Model-Suggested Alternative"], data_point["Label"], correct_token

ppo_config = PPOv2Config(
    learning_rate=3e-5,
    batch_size=16,
    mini_batch_size=16,
    num_ppo_epochs=100,
    output_dir='path/to/output/dir'
)

class HFDataset(Dataset):
    def __init__(self, hf_data):
        self.hf_data = hf_data

    def __len__(self):
        return len(self.hf_data)

    def __getitem__(self, idx):
        data_point = self.hf_data[idx]
        inputs, transmitted_word, predicted_word, label, correct_token = preprocess_data(data_point)
        return {
            'inputs': inputs,
            'transmitted_word': transmitted_word,
            'predicted_word': predicted_word,
            'label': label,
            'correct_token': correct_token,
        }

# add value head to model for RL
class BertForPPO(BertForMaskedLM):
    def __init__(self, config):
        super().__init__(config)
        self.value_head = torch.nn.Linear(config.hidden_size, 1)
    
    def forward(self, input_ids, attention_mask=None, labels=None):
        outputs = super().forward(input_ids, attention_mask, labels)
        value = self.value_head(outputs.last_hidden_state[:, 0, :]) 
        return outputs, value

policy_model = BertForPPO.from_pretrained(model_cache_path)
policy_model.to(device)

train_dataset = HFDataset(hf_data)

ppo_trainer = PPOv2Trainer(ppo_config, tokenizer=tokenizer, policy=policy_model, ref_policy=ref_policy, value_model=policy_model, reward_model=reward, train_dataset=train_dataset)

ppo_trainer.train()

model.save_pretrained("new_rlhf_model")
```

### Expected behavior

Ultimately, I expect the code to fine-tune my base model using the human-annotated data. I specifically expect the reward function to take in the predicted word ("Model-Suggested Alternative") and its label (e.g. "GOOD FLAG", "BAD FLAG", etc) and return a numerical value that rewards or punishes the model, from which the policy and value models would then adjust predictions. 

When I run the script, I receive this terminal error:
```
Traceback (most recent call last):
  File "path/to/above/script.py", line 115, in <module>
    ppo_trainer = PPOv2Trainer(ppo_config, tokenizer=tokenizer, policy=policy_model, ref_policy=ref_policy, value_model=policy_model, reward_model=reward, train_dataset=train_dataset)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path/to/env/lib/python3.12/site-packages/trl/trainer/ppov2_trainer.py", line 165, in __init__
    disable_dropout_in_model(module)
  File "path/to/env/lib/python3.12/site-packages/trl/trainer/utils.py", line 778, in disable_dropout_in_model
    for module in model.modules():
                  ^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'modules'
```

I assume this error is because the "disable_dropout_in_model" prevents users from loading a reward function, requiring they load a reward model. As mentioned, however, I do not have a reward model. Does PPOv2 allow for any work-arounds or ways I can use a reward function instead of a reward model? Do the tlr developers have any recommendations for alternative approaches for what I am trying to achieve in light of this error?

**Comment by qgallouedec** [comment]
PPO expect `reward_model` to be a model (torch module), not a function.
