### ISSUE TITLE
PPOConfig.__init__() got an unexpected keyword argument 'model_name'

### ISSUE THREAD

**Issue by chenyang399** [huggingface/trl#2314]
### System Info

i try to run the notebook gpt2-sentiment-control.ipynb. But when it runs the PPOconfig ,It reports the wrong keyword. And i check the PPOConfig.py file in trainer and it really do not have the keywords like model_name or steps.
![image](https://github.com/user-attachments/assets/33d9b12d-83d4-4525-902b-bb65fd26ee66)

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

just run the gpt2-sentiment-control.ipynb. and i got the problem

### Expected behavior

tell me how to run the gpt2-sentiment-control.ipynb successfully

**Comment by chenyang399** [comment]
i find the problem , its because someone update the ppotrainer and ppoconfig, but didn't update the notebook, we need to pip install trl==0.11.3 to restore a older version.

**Comment by chenyang399** [comment]
i hope the community to update the notebook

**Comment by ZNP8b** [comment]
I've had the same problem with SFTTrainer. And i found trl docs: https://huggingface.co/docs/trl/index
Here is PPO docs: https://huggingface.co/docs/trl/ppo_trainer#trl.PPOTrainer

There is 2 classes PPOtrainer and PPOconfig.
And i think updated version is expecting model_name inside PPOtrainer and not PPOconfig:

![image](https://github.com/user-attachments/assets/331e9c57-672c-4eba-a918-40d703f03bc4)

Same thing happened with SFTtrainer:
old SFTtrainer:
```Python
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    dataset_text_field = "text", # keyword error
    max_seq_length = max_seq_length, # keyword error
    data_collator = DataCollatorForSeq2Seq(tokenizer = tokenizer), # keyword error
    dataset_num_proc = 2, # keyword error
    packing = False, # keyword error
    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 5,
        # num_train_epochs = 1, # Set this for 1 full training run.
        max_steps = 60,
        learning_rate = 2e-4,
        fp16 = not is_bfloat16_supported(),
        bf16 = is_bfloat16_supported(),
        logging_steps = 1,
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        output_dir = "outputs",
        report_to = "none", # Use this for WandB etc
    ),
)
```

Everything with keyword error is going inside TrainingArguments (now its SFTargs)

```Python
trainer = SFTTrainer(
  model=model,
  tokenizer=tokenizer,
  train_dataset=dataset,
  # dataset_text_field="text",
  # max_seq_length=max_seq_length,
  # dataset_num_proc=2,
  # packing=False,
  args=SFTConfig( # SFTConfig instead TrainingArguments
      dataset_text_field="text", # Here now
      max_seq_length=max_seq_length, # Here now
      dataset_num_proc=2, # Here now
      packing=False, # Here now
      per_device_train_batch_size=2,
      gradient_accumulation_steps=4,
      warmup_steps=50,
      num_train_epochs=20,
      # max_steps=5,
      learning_rate=1e-4,
      fp16=not is_bfloat16_supported(),
      bf16=is_bfloat16_supported(),
      logging_steps=1,
      optim="adamw_8bit",
      weight_decay=0.01,
      lr_scheduler_type="linear",
      seed=3407,
      output_dir="outputs",
      report_to="none",
      ),
  )
  ```
  
  Try moving model_name outside PPOConfig inside PPOTrainer

**Comment by qgallouedec** [comment]
Not sure to get your point.`model_name` is an argument of `PPOTrainer.create_model_card` (see your screenshot). Not `PPOConfig` nor `PPOTrainer`

**Comment by chenyang399** [comment]
thanks guys

**Comment by Debolena7** [comment]
All the notebooks are giving a lot of errors. `The` PPOTrainer class also has a lot of other arguments that are required to be passed. for example, 'processing_class' instead of 'tokenizer', 'policy', 'ref_policy', 'reward_model', 'value_model', 'train_dataset' and NO 'optimizer'. I resolved all of these by mentioning the correct arguments. But now i am stuck at a new error: 

```

Traceback (most recent call last):
  File "/u/student/2020/ai20resch11003/miniconda3/envs/rlhf_new/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 782, in convert_to_tensors
    tensor = as_tensor(value)
  File "/u/student/2020/ai20resch11003/miniconda3/envs/rlhf_new/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 738, in as_tensor
    return torch.tensor(value)
ValueError: too many dimensions 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/u/student/2020/ai20resch11003/RLHF_new/hf_example.py", line 235, in <module>
    for epoch, batch in tqdm(enumerate(ppo_trainer.dataloader)):
  File "/u/student/2020/ai20resch11003/miniconda3/envs/rlhf_new/lib/python3.9/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/u/student/2020/ai20resch11003/miniconda3/envs/rlhf_new/lib/python3.9/site-packages/accelerate/data_loader.py", line 552, in __iter__
    current_batch = next(dataloader_iter)
  File "/u/student/2020/ai20resch11003/miniconda3/envs/rlhf_new/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/u/student/2020/ai20resch11003/miniconda3/envs/rlhf_new/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 673, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/u/student/2020/ai20resch11003/miniconda3/envs/rlhf_new/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 55, in fetch
    return self.collate_fn(data)
  File "/u/student/2020/ai20resch11003/miniconda3/envs/rlhf_new/lib/python3.9/site-packages/transformers/data/data_collator.py", line 271, in __call__
    batch = pad_without_fast_tokenizer_warning(
  File "/u/student/2020/ai20resch11003/miniconda3/envs/rlhf_new/lib/python3.9/site-packages/transformers/data/data_collator.py", line 66, in pad_without_fast_tokenizer_warning
    padded = tokenizer.pad(*pad_args, **pad_kwargs)
  File "/u/student/2020/ai20resch11003/miniconda3/envs/rlhf_new/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 3548, in pad
    return BatchEncoding(batch_outputs, tensor_type=return_tensors)
  File "/u/student/2020/ai20resch11003/miniconda3/envs/rlhf_new/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 240, in __init__
    self.convert_to_tensors(tensor_type=tensor_type, prepend_batch_axis=prepend_batch_axis)
  File "/u/student/2020/ai20resch11003/miniconda3/envs/rlhf_new/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 798, in convert_to_tensors
    raise ValueError(
ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length. Perhaps your features (`filename` in this case) have excessive nesting (inputs type `list` where type `int` is expected).
```


I am trying this notebook: https://github.com/huggingface/trl/blob/main/examples/research_projects/toxicity/scripts/gpt-j-6b-toxicity.py 


please help :(

**Comment by vimukthi69** [comment]
> i find the problem , its because someone update the ppotrainer and ppoconfig, but didn't update the notebook, we need to pip install trl==0.11.3 to restore a older version.

Hi chenyang399,

For the TRL version 0.11.3 do you have the argument name for reward model in PPOTrainer ? at the moment I'm using reward_fn which throws me the error, PPOTrainer.__init__() got an unexpected keyword argument 'reward_fn'
