### ISSUE TITLE
Accelerator package version problem

### ISSUE THREAD

**Issue by littleshutong** [huggingface/trl#2335]
### System Info

accelerate==1.0.0
torch==2.5.1
transformers==4.46.0
deepspeed==0.15.3

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

Examples/scripts/ppo/ppo.py

Python script:
accelerate launch --config_file examples/accelerate_configs/deepspeed_zero3.yaml \
    examples/scripts/ppo/ppo.py \
    --dataset_name trl-internal-testing/descriptiveness-sentiment-trl-style \
    --dataset_train_split descriptiveness \
    --output_dir models/minimal/ppo \
    --num_ppo_epochs 1 \
    --num_mini_batches 1 \
    --learning_rate 3e-6 \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --total_episodes 10000 \
    --model_name_or_path EleutherAI/pythia-1b-deduped \
    --sft_model_path EleutherAI/pythia-1b-deduped \
    --reward_model_path EleutherAI/pythia-1b-deduped \
    --local_rollout_forward_batch_size 1 \
    --missing_eos_penalty 1.0

Error:

[rank0]: Traceback (most recent call last):
[rank0]:   File "/sfs/users/yy24/trl/examples/scripts/ppo/ppo.py", line 126, in <module>
[rank0]:     trainer = PPOTrainer(
[rank0]:   File "/sfs/users/yy24/trl/trl/trainer/ppo_trainer.py", line 141, in __init__
[rank0]:     accelerator = Accelerator(gradient_accumulation_steps=args.gradient_accumulation_steps)
[rank0]:   File "/sfs/users/yy24/miniforge3/envs/trl/lib/python3.9/site-packages/accelerate/accelerator.py", line 292, in __init__
[rank0]:     deepspeed_plugins = AcceleratorState().deepspeed_plugins
[rank0]:   File "/sfs/users/yy24/miniforge3/envs/trl/lib/python3.9/site-packages/accelerate/state.py", line 887, in __init__
[rank0]:     raise ValueError(
[rank0]: ValueError: Please make sure to properly initialize your accelerator via `accelerator = Accelerator()` before using any functionality from the `accelerate` library.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

### Expected behavior

The accelerate object initialized normally.

**Comment by littleshutong** [comment]
trl/trainer/ppo_trainer.py 
![image](https://github.com/user-attachments/assets/4f4ba132-f48a-48e2-8225-2f3c35b4df57)

However, it is necessary to consider passing the parameters over.

**Comment by ccs96307** [comment]
I encountered this issue previously and temporarily worked around it by adjusting the accelerate version to 0.34.2. Here are the versions I used:

- accelerate==0.34.2
- torch==2.5.1
- transformers==4.46.2
- deepspeed==0.15.4

**Comment by albertvillanova** [comment]
Duplicate of:
- #2329

**Comment by albertvillanova** [comment]
The root cause was a bug in `accelerate` 1.0-1.8:
```shell
pip install -U "accelerate>=1.9.0"
```
