### ISSUE TITLE
Multiple Errors with PPOTrainer. error in ppo_trainer.dataloader

### ISSUE THREAD

**Issue by Debolena7** [huggingface/trl#2340]
All the notebooks are giving a lot of errors. `The` PPOTrainer class also has a lot of other arguments that are required to be passed. for example, 'processing_class' instead of 'tokenizer', 'policy', 'ref_policy', 'reward_model', 'value_model', 'train_dataset' and NO 'optimizer'. I resolved all of these by mentioning the correct arguments. But now i am stuck at a new error: 

```

Traceback (most recent call last):
  File "/u/student/2020/ai20resch11003/miniconda3/envs/rlhf_new/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 782, in convert_to_tensors
    tensor = as_tensor(value)
  File "/u/student/2020/ai20resch11003/miniconda3/envs/rlhf_new/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 738, in as_tensor
    return torch.tensor(value)
ValueError: too many dimensions 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/u/student/2020/ai20resch11003/RLHF_new/hf_example.py", line 235, in <module>
    for epoch, batch in tqdm(enumerate(ppo_trainer.dataloader)):
  File "/u/student/2020/ai20resch11003/miniconda3/envs/rlhf_new/lib/python3.9/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/u/student/2020/ai20resch11003/miniconda3/envs/rlhf_new/lib/python3.9/site-packages/accelerate/data_loader.py", line 552, in __iter__
    current_batch = next(dataloader_iter)
  File "/u/student/2020/ai20resch11003/miniconda3/envs/rlhf_new/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/u/student/2020/ai20resch11003/miniconda3/envs/rlhf_new/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 673, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/u/student/2020/ai20resch11003/miniconda3/envs/rlhf_new/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 55, in fetch
    return self.collate_fn(data)
  File "/u/student/2020/ai20resch11003/miniconda3/envs/rlhf_new/lib/python3.9/site-packages/transformers/data/data_collator.py", line 271, in __call__
    batch = pad_without_fast_tokenizer_warning(
  File "/u/student/2020/ai20resch11003/miniconda3/envs/rlhf_new/lib/python3.9/site-packages/transformers/data/data_collator.py", line 66, in pad_without_fast_tokenizer_warning
    padded = tokenizer.pad(*pad_args, **pad_kwargs)
  File "/u/student/2020/ai20resch11003/miniconda3/envs/rlhf_new/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 3548, in pad
    return BatchEncoding(batch_outputs, tensor_type=return_tensors)
  File "/u/student/2020/ai20resch11003/miniconda3/envs/rlhf_new/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 240, in __init__
    self.convert_to_tensors(tensor_type=tensor_type, prepend_batch_axis=prepend_batch_axis)
  File "/u/student/2020/ai20resch11003/miniconda3/envs/rlhf_new/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 798, in convert_to_tensors
    raise ValueError(
ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length. Perhaps your features (`filename` in this case) have excessive nesting (inputs type `list` where type `int` is expected).
```

I am trying this notebook: https://github.com/huggingface/trl/blob/main/examples/research_projects/toxicity/scripts/gpt-j-6b-toxicity.py 

if these notebooks are outdated, please mention the correct 'trl' and 'transformers' package versions that are supposed to be installed before using these. that would help a lot. 

please help :(

**Comment by qgallouedec** [comment]
We know that a lot of notebooks/docs are outdated. Sorry for the inconvenience. 
It was a deliberate choice that has allowed us to move faster on the lib evolution. For more information, see https://github.com/huggingface/trl/pull/2174#issuecomment-2399843454. But you can be sure that it will soon be completely up to date. 
Most doc and notebooks should work with `trl==0.11`
I agree with you that the notebooks should mention it. Feel free to open a PR if you wan't to contribute

**Comment by Debolena7** [comment]
Thank you so much for your prompt reply. Changing the package trl version resolved the errors. I have been trying several code examples of rlhf from huggingface and also from youtube for a week now, and all had multiple issues. Was stuck for so many days.  Thanks again.

**Comment by ioana-ghiban-arm** [comment]
hi! I'm facing quite a few errors when attempting running the 'toxicity' example as well. Currently stuck on this error:
`TypeError: PPOTrainer.__init__() got multiple values for argument 'processing_class'`. Would immensely appreciate an updated end-to-end working demo of this. Thank you in advance.

**Comment by Debolena7** [comment]
> policy = model,
>                          ref_policy = ref_model,
>                          reward_model = rm_model,


I faced the same issue. So this error is basically caused because, the value model is not being passed in the 'PPOTrainer' arguments. So, by default, the value_model is None, which leads to the error. 

To solve it, you can either initialize a value model like: 
`value_model = AutoModelForSequenceClassification.from_pretrained("distilroberta-base")` and pass the value model into the 'PPOTrainer' , 
OR just simply use old `trl==0.11.0`

**Comment by Debolena7** [comment]
> hi! I'm facing quite a few errors when attempting running the 'toxicity' example as well. Currently stuck on this error: `TypeError: PPOTrainer.__init__() got multiple values for argument 'processing_class'`. Would immensely appreciate an updated end-to-end working demo of this. Thank you in advance.

@ioana-ghiban-arm
You can pass your model tokenizer into the 'processing_class' argument of PPOTrainer.
`tokenizer = AutoTokenizer.from_pretrained(model_id)`

```
ppo_trainer = PPOTrainer(config=config,
                         processing_class = tokenizer, .................)
```

**Comment by ioana-ghiban-arm** [comment]
@Debolena7 thank you for your help! you're right, I tried your suggestion and I think the execution got further. Now I'm getting the error I'd see when running a simplified version of the script. Do you perhaps have some troubleshooting steps for this error: `AttributeError: 'AutoModelForCausalLMWithValueHead' object has no attribute 'generation_config'`? 
TIA

**Comment by Debolena7** [comment]
it seems you have used something like: `model = AutoModelForCausalLMWithValueHead.from_pretrained(model_id)` which lead to the error.. you can use:
`from transformers import GenerationConfig `
`model.generation_config = GenerationConfig()` , after initialization. 
But i would suggest it is best to use an old trl==0.11.0. otherwise, you will encounter more errors.

**Comment by ioana-ghiban-arm** [comment]
thank you for your help. Indeed, changing to `trl==0.11` does get the training going. However, I'm seeing this warning: `UserWarning: The average ratio of batch (...) exceeds threshold 10.00. Skipping batch.` which as mentioned [here](https://github.com/huggingface/trl/issues/1031) _suggests that the updates to the policy are too large, which could lead to instability in the training_. The maintainer suggested using [ppo.py](https://github.com/huggingface/trl/blob/main/examples/scripts/ppo/ppo.py) instead, so I tried adapting that script to use the toxicity model and dataset. However, as that is an updated script I'm assuming it should be ran with the latest version of trl provided by the repo. That leads me to the error that this thread started with..

Any suggestion to help me stop going in circles and be able to run a first round of fine-tuning on this model would be greatly appreciated, thank you.

**Comment by ravitiwari96** [comment]
from copy import deepcopy

policy_model = model

ref_model = deepcopy(policy_model)

value_model = deepcopy(policy_model)


ppo_trainer = PPOTrainer(
    train_dataset, 
    value_model,    
    ppo_config,   
    policy_model,  
    ref_model   
   
)


When i am executing this code then i am getting following error 


<img width="805" height="305" alt="Image" src="https://github.com/user-attachments/assets/e9a59a7a-4d90-48b1-a15d-cda94c8ce4f7" />

**Comment by qgallouedec** [comment]
Hey @Debolena7, sorry for the very late follow-up, catching up on the backlog.

The script you referenced (`examples/research_projects/toxicity/scripts/gpt-j-6b-toxicity.py`) no longer exists on `main`: the whole `research_projects/` tree was removed, and the legacy PPOTrainer was relocated to `trl.experimental.ppo`. For an up-to-date PPO entrypoint, see `examples/scripts/ppo/ppo.py`.

As you already noted in-thread, pinning `trl==0.11` is the right move for the old script. Closing as outdated
