### ISSUE TITLE
AttributeError: 'DistributedDataParallel' object has no attribute 'policy' when saving model

### ISSUE THREAD

**Issue by AsiaLootus** [huggingface/trl#2375]
### System Info

- Platform: Linux-5.15.0-1053-nvidia-x86_64-with-glibc2.31
- Python version: 3.10.14
- PyTorch version: 2.5.1
- CUDA device(s): NVIDIA H100 80GB HBM3, NVIDIA H100 80GB HBM3, NVIDIA H100 80GB HBM3, NVIDIA H100 80GB HBM3, NVIDIA H100 80GB HBM3, NVIDIA H100 80GB HBM3, NVIDIA H100 80GB HBM3, NVIDIA H100 80GB HBM3
- Transformers version: 4.46.3
- Accelerate version: 1.1.1
- Accelerate config: not found
- Datasets version: 3.1.0
- HF Hub version: 0.26.2
- TRL version: 0.12.1
- bitsandbytes version: 0.44.1
- DeepSpeed version: 0.15.4
- Diffusers version: not installed
- Liger-Kernel version: not installed
- LLM-Blender version: not installed
- OpenAI version: not installed
- PEFT version: 0.13.2

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

```python

from datasets import load_dataset
from trl import create_reference_model
from transformers import pipeline, AutoTokenizer, AutoModelForCausalLM, DataCollatorForLanguageModeling, BitsAndBytesConfig,AutoModelForSeq2SeqLM, AutoModelForSequenceClassification
from datasets import load_dataset, DatasetDict
from trl.trainer.utils import SIMPLE_CHAT_TEMPLATE
from trl import PPOConfig
import torch

from trl import AutoModelForCausalLMWithValueHead, PPOConfig, PPOTrainer, PPOv2Trainer

def load_jsonl_dataset(jsonl_file_path, split='train'):
    dataset = load_dataset('json', data_files=jsonl_file_path, split=split)
    dataset_dict = DatasetDict({
        'train': dataset,
    })
    return dataset_dict[split]

tokenizer = AutoTokenizer.from_pretrained(
        "EleutherAI/pythia-1b-deduped",
        padding_side="left",
        #padding=True, 
        truncation=True
        #trust_remote_code=model_config["trust_remote_code"],
        #attn_implementation="flash_attention_2"
    )
#tokenizer.add_special_tokens({"pad_token": "[PAD]"})

tokenizer.pad_token = tokenizer.eos_token
if tokenizer.chat_template is None:
    tokenizer.chat_template = SIMPLE_CHAT_TEMPLATE


def maybe_insert_system_message(messages, tokenizer):
    # if messages[0]["role"] == "system":
    #     return
    chat_template = tokenizer.chat_template
    print(chat_template)
    if chat_template is None:
        chat_template = tokenizer.default_chat_template
    if "system" in chat_template or "<|im_start|>" in chat_template:
        messages.insert(0, {"role": "system", "content": ""})
        return
    
def check_format(example, role="user"):
    try:
        # example = json.loads(example)
        tokenizer.apply_chat_template(json.loads(example))
        return json.loads(example)
    except:
        return [{"role":role, "content": example}]

def apply_dpo_template(example, system=False):
    if all(k in example.keys() for k in ("chosen", "rejected")):
        if not system:
            prompt_messages = example["prompt"]
        else: 
            if np.isnan(example["system"]) or example["system"]=="":
                prompt_messages = example["prompt"]
            elif np.isnan(example["prompt"]) or example["prompt"]=="":
                prompt_messages = example["system"]
            else:
                prompt_messages = example["system"] +"\\n"+ example["prompt"]
        chosen_messages = example["chosen"]

        prompt_messages_cf = check_format(prompt_messages, role="user")
        chosen_messages_cf = check_format(chosen_messages, role="assistant")
        prompt_messages_cf.extend(chosen_messages_cf)

        example["input_ids"] = (tokenizer.apply_chat_template(prompt_messages_cf, tokenize=True))
    return example

dtype =  torch.bfloat16  
config = PPOConfig(
    #model_name="gpt2",
    bf16=True,
    learning_rate=1.41e-5,
    save_strategy="steps",
    save_steps=5,
    output_dir="ppo" # /run/determined/workdir/work/fastcloud-coe/checkpoint/alignment/
)


def tokenize(sample):
    sample["input_ids"] = tokenizer.encode(sample["query"])
    return sample

dataset = load_jsonl_dataset("dpo_v3.jsonl") # /run/determined/workdir/work/fastcloud-coe/data/dpo/clean/

eval_samples = 100
dataset = dataset.filter(
    lambda example: sum(len(example[col]) for col in ['system', 'prompt', 'chosen']) < 2000 
)

dataset = dataset.filter(
    lambda example: sum(len(example[col]) for col in ['system', 'prompt', 'chosen']) > 0 
)
dataset = dataset.map(apply_dpo_template, batched = False,) # ['score_chosen', 'messages', 'score_rejected']
dataset = dataset.remove_columns(["chosen", "rejected", "prompt", "system"])

eval_samples=100
train_dataset = dataset.select(range(len(dataset) - eval_samples))
eval_dataset = dataset.select(range(len(dataset) - eval_samples, len(dataset)))



value_model = AutoModelForSequenceClassification.from_pretrained(
    "EleutherAI/pythia-1b-deduped", num_labels=1, attn_implementation="flash_attention_2", torch_dtype=dtype
).to('cuda') # attn_implementation="flash_attention_2",
reward_model = AutoModelForSequenceClassification.from_pretrained(
    "EleutherAI/pythia-1b-deduped", num_labels=1, attn_implementation="flash_attention_2", torch_dtype=dtype
).to('cuda') # attn_implementation="flash_attention_2",
ref_policy = AutoModelForCausalLM.from_pretrained(
    "EleutherAI/pythia-1b-deduped", attn_implementation="flash_attention_2", torch_dtype=dtype
).to('cuda') # attn_implementation="flash_attention_2",
policy = AutoModelForCausalLM.from_pretrained(
    "EleutherAI/pythia-1b-deduped", attn_implementation="flash_attention_2", torch_dtype=dtype
).to('cuda') # attn_implementation="flash_attention_2",

ppo_trainer = PPOTrainer( # PPOTrainer(
    #model=model,
    policy=policy,
    ref_policy=ref_policy,
    reward_model=reward_model,
    value_model=value_model,
    config=config,
    train_dataset=train_dataset,#train_dataset,
    tokenizer=tokenizer,
    eval_dataset=eval_dataset
    # ref_policy=ref_model,
    # reward_model=rm_model,
    # value_model=ref_model
)

generation_kwargs = {
    "min_length": -1,
    "top_k": 0.0,
    "top_p": 1.0,
    "do_sample": True,
    "pad_token_id": tokenizer.eos_token_id,
}

ppo_trainer.train()
```

outputs:

```

Traceback (most recent call last): <none> [2024-11-19 17:47:00]
  File "/run/determined/workdir/main4.py", line 245, in <module> <none> [2024-11-19 17:47:00]
    ppo_trainer.train() <none> [2024-11-19 17:47:00]
  File "/run/determined/pythonuserbase/lib/python3.10/site-packages/trl/trainer/ppo_trainer.py", line 572, in train <none> [2024-11-19 17:47:00]
    self._save_checkpoint(model, trial=None) <none> [2024-11-19 17:47:00]
  File "/run/determined/pythonuserbase/lib/python3.10/site-packages/transformers/trainer.py", line 3097, in _save_checkpoint <none> [2024-11-19 17:47:00]
    self.save_model(output_dir, _internal_call=True) <none> [2024-11-19 17:47:00]
  File "/run/determined/pythonuserbase/lib/python3.10/site-packages/trl/trainer/ppo_trainer.py", line 262, in save_model <none> [2024-11-19 17:47:00]
    self.model = self.model.policy  # save only the policy <none> [2024-11-19 17:47:00]
  File "/run/determined/pythonuserbase/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1931, in __getattr__ <none> [2024-11-19 17:47:00]
    raise AttributeError( <none> [2024-11-19 17:47:00]
AttributeError: 'DistributedDataParallel' object has no attribute 'policy' 
```

### Expected behavior

I'm trying to perform a training process using the PPO Trainer.

The dataset used is a classic DPO with the columns: system, prompt, chosen, and rejected.

This training works, but this error occurs during the saving process.

Could you help me understand how to resolve it? Thank you!!

### Checklist

- [X] I have checked that my issue isn't already filed (see [open issues](https://github.com/huggingface/trl/issues?q=is%3Aissue))
- [X] I have included my system information
- [X] Any code provided is minimal, complete, and reproducible ([more on MREs](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))
- [X] Any code provided is properly formatted in code blocks, (no screenshot, [more on code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))
- [X] Any traceback provided is complete

**Comment by xiaoyuxin1002** [comment]
change line 262 in ppo_trainer.py to `self.model = self.model.module.policy  # save only the policy`

**Comment by Ugadot** [comment]
I am getting similar error when i try to use accelerate training on multiple GPU.  However when i use normal single GPU training i don't get this error. This happens when `null_ref_context` function is called. Any ideas on the source of this Error?

**Comment by marcellobullo** [comment]
> I am getting similar error when i try to use accelerate training on multiple GPU. However when i use normal single GPU training i don't get this error. This happens when `null_ref_context` function is called. Any ideas on the source of this Error?

Same here. Any updates? Thanks

**Comment by NandyZ** [comment]
hey,  I am getting similar error too. This error typically occurs when using DistributedDataParallel (DDP) to wrap the model and directly accessing the original model's attributes (such as policy) without going through the .module interface. DDP encapsulates the original model within the module attribute, causing direct access to the original attributes to fail.
So, you can change the code
```
# before
self.model, self.optimizer, self.dataloader = accelerator.prepare(self.model, self.optimizer, self.dataloader)

# after
ddp_model, self.optimizer, self.dataloader = accelerator.prepare(self.model, self.optimizer, self.dataloader)
self.model = ddp_model.module
```
I’ve fixed this error, you can give it a try too.

**Comment by guotong1988** [comment]
Which `trl` version has fixed the error?

**Comment by qgallouedec** [comment]
Hey @AsiaLootus, sorry for the very slow reply here, we're catching up on the PPO backlog.

This crash is fixed: the save step used to run `self.model = self.model.policy` unconditionally, which fails under DDP because the model is wrapped in `DistributedDataParallel`; it's now guarded so the policy is only unwrapped when it's actually present, see https://github.com/huggingface/trl/blob/7b4c3b3b208c8611ff23818e8483cd2a6eaecb35/trl/experimental/ppo/ppo_trainer.py#L598-L611 via #5151. @guotong1988 the fix first shipped in TRL v0.29.0, so upgrading should resolve it. One note: `PPOTrainer`/`PPOConfig` now live under the experimental namespace — import them as `from trl.experimental.ppo import PPOTrainer, PPOConfig`.
