### ISSUE TITLE
ValueError: Predictions and/or references don't match the expected format.

### ISSUE THREAD

**Issue by scarafoni** [huggingface/trl#2376]
### System Info

I am trying to evaluate my model trained locally on SFTTrainer, but it gives me this error when I try and use the metric prediction for BLEU:

```
raceback (most recent call last):
  File "c:\Users\dan\anaconda3\envs\autogengpu\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\dan\anaconda3\envs\autogengpu\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\dan\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\__main__.py", line 71, in <module>
    cli.main()
  File "c:\Users\dan\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy/..\debugpy\server\cli.py", line 501, in main
    run()
  File "c:\Users\dan\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy/..\debugpy\server\cli.py", line 351, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\dan\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 310, in run_path
    return _run_module_code(code, init_globals, run_name, pkg_name=pkg_name, script_name=fname)
  File "c:\Users\dan\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 127, in _run_module_code
    _run_code(code, mod_globals, init_globals, mod_name, mod_spec, pkg_name, script_name)
  File "c:\Users\dan\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 118, in _run_code
    exec(code, run_globals)
  File "C:\Users\dan\Documents\Seer_Intel\docs\24-11-14_query_optimizer_hfrl\sft.py", line 82, in <module>
    data = trainer.evaluate()
  File "c:\Users\dan\anaconda3\envs\autogengpu\lib\site-packages\transformers\trainer.py", line 3975, in evaluate
    output = eval_loop(
  File "c:\Users\dan\anaconda3\envs\autogengpu\lib\site-packages\transformers\trainer.py", line 4264, in evaluation_loop
    metrics = self.compute_metrics(
  File "C:\Users\dan\Documents\Seer_Intel\docs\24-11-14_query_optimizer_hfrl\sft.py", line 72, in compute_metrics
    return metric.compute(predictions=predictions, references=labels)
  File "c:\Users\dan\anaconda3\envs\autogengpu\lib\site-packages\evaluate\module.py", line 455, in compute
    self.add_batch(**inputs)
  File "c:\Users\dan\anaconda3\envs\autogengpu\lib\site-packages\evaluate\module.py", line 514, in add_batch
    self.selected_feature_format = self._infer_feature_from_batch(batch)
  File "c:\Users\dan\anaconda3\envs\autogengpu\lib\site-packages\evaluate\module.py", line 596, in _infer_feature_from_batch
    return self._infer_feature_from_example(example)
  File "c:\Users\dan\anaconda3\envs\autogengpu\lib\site-packages\evaluate\module.py", line 616, in _infer_feature_from_example
    raise ValueError(error_msg) from None
ValueError: Predictions and/or references don't match the expected format.
Expected format:
Feature option 0: {'predictions': Value(dtype='string', id='sequence'), 'references': Sequence(feature=Value(dtype='string', id='sequence'), length=-1, id='references')}
Feature option 1: {'predictions': Value(dtype='string', id='sequence'), 'references': Value(dtype='string', id='sequence')},
Input predictions: [48134 15680    35  3401  3069     5 22205  7192     7  3094     5 11581
     9     5  2214    22 40794 10915 38042 10831    36 21502 39210 12603
 30831    30 12586 10915 38042    31     5  2642    22   725   428  8475
  1053    72 47868   877 16038 30831 11873   352  1871     5   775     7
    10  2870  1440    22 40794  1215 39516 38042  1215 24457  1215 21502
 39210  1215  5404  7469     4 46795    72  3837  3069 22941     5  2214
  2870  2034  5320    75  2381     7  5997 15574   113    30  4160   118
  5275  2034    23  1589  8361    73 14856    73 45266 29788  1439    73
 23687    73 28400  1215 11802    73   863  5270  5275    73 16991   208
  4376   978   646  5607 46858 13339   706  5881   742    73  3570   111
  1599    75  2381     7  5997 15574     4  6195],
Input references: [    2 48134 15680    35  3401 16085     5 22205  7192     7  3094     5
 11581     9     5  2214    22 40794 10915 38042  6395    36 21502 39210
 12603 30831    30 12586 10915 38042    31     5  2642    22 31431   428
  8475  1053    36 47868   877 16038 18456 17161   352  1871     5   775
     7    10  2870  1440    22 40794  1215 39516 38042  1215 24457  1215
 21502 39210  1215  5404  7469     4 46795    72  3401  3069 22941     5
  2214  2870    22  6766    75  2381     7  5997 15574   113    30  4160
   118  5275  2034    23  1589  8361    73 14856    73 45266 29788  1439
    73 23687    73 28400  1215 11802    73   863  5270  5275    73 16991
   208  4376   978   646  5607 46858 13339   706  5881   742    73  3570
   111  1599    75  2381     7  5997 15574     4]
```

Here is the code:
```python
 model = AutoModelForCausalLM.from_pretrained('./sft_train/checkpoint-1000')
    tokenizer = AutoTokenizer.from_pretrained('./sft_train/checkpoint-1000')

    sft_config = SFTConfig(
        dataset_text_field="label",
        max_seq_length=128,
        output_dir="./sft_train",
        num_train_epochs=100,
        per_device_train_batch_size=64,
        use_cpu=False
    )
        
    metric = evaluate.load('sacrebleu')
    def compute_metrics(eval_pred):
        logits, labels = eval_pred
        labels = labels.astype(np.uint16)
        predictions = np.argmax(logits, axis=-1).astype(np.uint16)
        return metric.compute(predictions=predictions, references=labels)
        
    dataset = load_dataset("json", data_files="sft_data_test.jsonl", split="train")
    trainer = SFTTrainer(
        model,
        eval_dataset=dataset,
        args=sft_config,
        formatting_func=formatting_prompts_func,
        compute_metrics=compute_metrics
    )
    data = trainer.evaluate()
    print(data)
```
report of `trl env`:

```
- Platform: Windows-10-10.0.22631-SP0
- Python version: 3.10.15
- PyTorch version: 2.5.0+cu124
- CUDA device(s): NVIDIA GeForce RTX 4060 Laptop GPU
- Transformers version: 4.46.2
- Accelerate version: 1.1.1
- Accelerate config: not found
- Datasets version: 3.1.0
- HF Hub version: 0.26.2
- TRL version: 0.12.1
- bitsandbytes version: 0.44.1
- DeepSpeed version: not installed
- Diffusers version: not installed
- Liger-Kernel version: not installed
- LLM-Blender version: not installed
- OpenAI version: not installed
- PEFT version: not installed
```

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

```python
from datasets import load_dataset
from trl import SFTConfig, SFTTrainer
import sys
from transformers import AutoTokenizer, AutoModelForCausalLM
import evaluate
import numpy as np

def formatting_prompts_func(example):
    output_texts = []
    for i in range(len(example['text'])):
        text = f"### Question: {example['text'][i]}\n ### Answer: {example['label'][i]} End ###"
        output_texts.append(text)
    return output_texts

if False:
    dataset = load_dataset("json", data_files="sft_data_train.jsonl", split="train")
    # dataset = dataset.map(lambda x: {"text": x["text"]+x["label"]})
    
    dataset_val = load_dataset("json", data_files="sft_data_val.jsonl", split="train")
    # dataset_val = dataset.map(lambda x: {"text": x["text"]+x["label"]})

    sft_config = SFTConfig(
        dataset_text_field="label",
        max_seq_length=128,
        output_dir="./sft_train",
        num_train_epochs=100,
        per_device_train_batch_size=64,
        use_cpu=False
    )
    
    model = AutoModelForCausalLM.from_pretrained(
        "facebook/opt-350m",
        device_map="auto",
    )
    model.to('cuda:0')
    
    trainer = SFTTrainer(
        model,
        train_dataset=dataset,
        eval_dataset=dataset_val,
        args=sft_config,
        formatting_func=formatting_prompts_func
    )
    trainer.train()

else:
    model = AutoModelForCausalLM.from_pretrained('./sft_train/checkpoint-1000')
    tokenizer = AutoTokenizer.from_pretrained('./sft_train/checkpoint-1000')

    input = '### Question: Please analyze the song \"Gaucho\" by Steely Dan from the album \"Gaucho\" and determine its genre. Save the results to a file named gaucho_lyrics.txt. \n ### Answer: '
    inputs = tokenizer.encode(input, return_tensors="pt")
    
    outputs = model.generate(inputs, max_length=128, stop_strings=['End ###'], tokenizer=tokenizer)
    print(input)
    print('--------')
    print(tokenizer.decode(outputs[0]).split('### Answer: ')[1].split('End ###')[0])
    
    sft_config = SFTConfig(
        dataset_text_field="label",
        max_seq_length=128,
        output_dir="./sft_train",
        num_train_epochs=100,
        per_device_train_batch_size=64,
        use_cpu=False
    )
        
    metric = evaluate.load('sacrebleu')
    def compute_metrics(eval_pred):
        logits, labels = eval_pred
        labels = labels.astype(np.uint16)
        predictions = np.argmax(logits, axis=-1).astype(np.uint16)
        return metric.compute(predictions=predictions, references=labels)
        
    dataset = load_dataset("json", data_files="sft_data_test.jsonl", split="train")
    trainer = SFTTrainer(
        model,
        eval_dataset=dataset,
        args=sft_config,
        formatting_func=formatting_prompts_func,
        compute_metrics=compute_metrics
    )
    data = trainer.evaluate()
    print(data)

outputs:

```
### Answer:
--------
 Find the genre of the song Gaucho by Steely Dan on the album Gaucho and save the results to gaucho_lyrics.txt
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13/13 [00:23<00:00,  4.03s/it]
PS C:\Users\dan\Documents\Seer_Intel\docs\24-11-14_query_optimizer_hfrl> trl env
Traceback (most recent call last):                                                                                                                                    
  File "c:\Users\dan\anaconda3\envs\autogen\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\dan\anaconda3\envs\autogen\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\dan\anaconda3\envs\autogen\Scripts\trl.exe\__main__.py", line 7, in <module>
  File "c:\Users\dan\anaconda3\envs\autogen\lib\site-packages\trl\commands\cli.py", line 38, in main
    raise ValueError(
ValueError: Please use one of the supported commands, got env - supported commands are ['sft', 'dpo', 'chat', 'kto']
PS C:\Users\dan\Documents\Seer_Intel\docs\24-11-14_query_optimizer_hfrl> ^C
PS C:\Users\dan\Documents\Seer_Intel\docs\24-11-14_query_optimizer_hfrl>
PS C:\Users\dan\Documents\Seer_Intel\docs\24-11-14_query_optimizer_hfrl>  C:; cd 'C:\Users\dan\Documents\Seer_Intel\docs\24-11-14_query_optimizer_hfrl'; & 'c:\Users\dan\anaconda3\envs\autogengpu\python.exe' 'c:\Users\dan\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher' '65186' '--' 'C:\Users\dan\Documents\Seer_Intel\docs\24-11-14_query_optimizer_hfrl\sft.py' 
### Answer:
--------
 Find the genre of the song Gaucho by Steely Dan on the album Gaucho and save the results to gaucho_lyrics.txt
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13/13 [00:23<00:00,  4.00s/it]Traceback (most recent call last):
  File "c:\Users\dan\anaconda3\envs\autogengpu\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\dan\anaconda3\envs\autogengpu\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\dan\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\__main__.py", line 71, in <module>
    cli.main()
  File "c:\Users\dan\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy/..\debugpy\server\cli.py", line 501, in main
    run()
  File "c:\Users\dan\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy/..\debugpy\server\cli.py", line 351, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\dan\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 310, in run_path
    return _run_module_code(code, init_globals, run_name, pkg_name=pkg_name, script_name=fname)
  File "c:\Users\dan\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 127, in _run_module_code
    _run_code(code, mod_globals, init_globals, mod_name, mod_spec, pkg_name, script_name)
  File "c:\Users\dan\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 118, in _run_code
    exec(code, run_globals)
  File "C:\Users\dan\Documents\Seer_Intel\docs\24-11-14_query_optimizer_hfrl\sft.py", line 82, in <module>
    data = trainer.evaluate()
  File "c:\Users\dan\anaconda3\envs\autogengpu\lib\site-packages\transformers\trainer.py", line 3975, in evaluate
    output = eval_loop(
  File "c:\Users\dan\anaconda3\envs\autogengpu\lib\site-packages\transformers\trainer.py", line 4264, in evaluation_loop
    metrics = self.compute_metrics(
  File "C:\Users\dan\Documents\Seer_Intel\docs\24-11-14_query_optimizer_hfrl\sft.py", line 72, in compute_metrics
    return metric.compute(predictions=predictions, references=labels)
  File "c:\Users\dan\anaconda3\envs\autogengpu\lib\site-packages\evaluate\module.py", line 455, in compute
    self.add_batch(**inputs)
  File "c:\Users\dan\anaconda3\envs\autogengpu\lib\site-packages\evaluate\module.py", line 514, in add_batch
    self.selected_feature_format = self._infer_feature_from_batch(batch)
  File "c:\Users\dan\anaconda3\envs\autogengpu\lib\site-packages\evaluate\module.py", line 596, in _infer_feature_from_batch
    return self._infer_feature_from_example(example)
  File "c:\Users\dan\anaconda3\envs\autogengpu\lib\site-packages\evaluate\module.py", line 616, in _infer_feature_from_example
    raise ValueError(error_msg) from None
ValueError: Predictions and/or references don't match the expected format.
Expected format:
Feature option 0: {'predictions': Value(dtype='string', id='sequence'), 'references': Sequence(feature=Value(dtype='string', id='sequence'), length=-1, id='references')}
Feature option 1: {'predictions': Value(dtype='string', id='sequence'), 'references': Value(dtype='string', id='sequence')},
Input predictions: [48134 15680    35  3401  3069     5 22205  7192     7  3094     5 11581
     9     5  2214    22 40794 10915 38042 10831    36 21502 39210 12603
 30831    30 12586 10915 38042    31     5  2642    22   725   428  8475
  1053    72 47868   877 16038 30831 11873   352  1871     5   775     7
    10  2870  1440    22 40794  1215 39516 38042  1215 24457  1215 21502
 39210  1215  5404  7469     4 46795    72  3837  3069 22941     5  2214
  2870  2034  5320    75  2381     7  5997 15574   113    30  4160   118
  5275  2034    23  1589  8361    73 14856    73 45266 29788  1439    73
 23687    73 28400  1215 11802    73   863  5270  5275    73 16991   208
  4376   978   646  5607 46858 13339   706  5881   742    73  3570   111
  1599    75  2381     7  5997 15574     4  6195],
Input references: [    2 48134 15680    35  3401 16085     5 22205  7192     7  3094     5
 11581     9     5  2214    22 40794 10915 38042  6395    36 21502 39210
 12603 30831    30 12586 10915 38042    31     5  2642    22 31431   428
  8475  1053    36 47868   877 16038 18456 17161   352  1871     5   775
     7    10  2870  1440    22 40794  1215 39516 38042  1215 24457  1215
 21502 39210  1215  5404  7469     4 46795    72  3401  3069 22941     5
  2214  2870    22  6766    75  2381     7  5997 15574   113    30  4160
   118  5275  2034    23  1589  8361    73 14856    73 45266 29788  1439
    73 23687    73 28400  1215 11802    73   863  5270  5275    73 16991
   208  4376   978   646  5607 46858 13339   706  5881   742    73  3570
   111  1599    75  2381     7  5997 15574     4]
100%|██████████| 13/13 [00:39<00:00,  3.06s/it]
```


### Expected behavior

It should just print out the metrics (BLEU) for this evaluation dataset

### Checklist

- [X] I have checked that my issue isn't already filed (see [open issues](https://github.com/huggingface/trl/issues?q=is%3Aissue))
- [X] I have included my system information
- [X] Any code provided is minimal, complete, and reproducible ([more on MREs](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))
- [X] Any code provided is properly formatted in code blocks, (no screenshot, [more on code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))
- [X] Any traceback provided is complete

**Comment by qgallouedec** [comment]
It seems like the issue lies in how the inputs to the metric computation are being handled. Specifically, the metric expects strings (decoded text), but your code is providing tokens (numerical IDs). You can resolve this by decoding both predictions and labels using the tokenizer before passing them to the metric.

```diff
  def compute_metrics(eval_pred):
      logits, labels = eval_pred
      labels = labels.astype(np.uint16)
      predictions = np.argmax(logits, axis=-1).astype(np.uint16)
+     predictions = tokenizer.batch_decode(predictions)
+     labels = tokenizer.batch_decode(labels)
      return metric.compute(predictions=predictions, references=labels)
```

**Comment by scarafoni** [comment]
thank you. it's working now.

**Comment by scarafoni** [comment]
issue resolved
