### ISSUE TITLE
chat_template is not supported ?

### ISSUE THREAD

**Issue by MohamedAliRashad** [huggingface/trl#2385]
### System Info

- Platform: Linux-6.5.0-35-generic-x86_64-with-glibc2.35
- Python version: 3.10.12
- PyTorch version: 2.1.0+cu118
- CUDA device(s): NVIDIA RTX 2000 Ada Generation
- Transformers version: 4.46.3
- Accelerate version: 1.1.1
- Accelerate config: not found
- Datasets version: 3.1.0
- HF Hub version: 0.26.2
- TRL version: 0.12.1
- bitsandbytes version: not installed
- DeepSpeed version: not installed
- Diffusers version: not installed
- Liger-Kernel version: not installed
- LLM-Blender version: not installed
- OpenAI version: 1.54.5
- PEFT version: not installed

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

```python
from trl import DPOConfig, DPOTrainer

ds = ds.map(
    lambda x: {
        "system": [{"role": "user", "content": x["system"]}],
        "prompt": [{"role": "user", "content": x["prompt"]}],
        "chosen": [{"role": "assistant", "content": x["chosen"]}],
        "rejected": [{"role": "user", "content": x["rejected"]}],
    }
)
ds = ds.train_test_split(test_size=0.1, seed=42)
print(ds)

training_args = DPOConfig(
    output_dir=str(Path(__file__).parent / f"aligning-logs"),
    max_steps=10_000,
    overwrite_output_dir=True,
    eval_strategy="steps",
    save_strategy="steps",
    report_to="none",
    save_steps=100,
    eval_steps=100,
    gradient_checkpointing=True,  # Great for memory saving
    gradient_checkpointing_kwargs={"use_reentrant": False},  # To remove the warning
    per_device_train_batch_size=1,
    gradient_accumulation_steps=1,
    per_device_eval_batch_size=1,
    save_total_limit=2,
    bf16=True,
    logging_steps=5,
    dataloader_num_workers=8,  # Use multiple processes for data loading
    dataloader_pin_memory=True,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    ddp_find_unused_parameters=False,  # Don't know what this does
)
trainer = DPOTrainer(
    model=model,
    processing_class=tokenizer,
    train_dataset=ds["train"],
    eval_dataset=ds["test"],
    args=training_args,
    # data_collator=data_collator,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=3)],
)
```

outputs:

```
Traceback (most recent call last):
  File "/workspace/dpo_qwen_pro.py", line 131, in <module>
    trainer = DPOTrainer(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/deprecation.py", line 165, in wrapped_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/trl/trainer/dpo_trainer.py", line 599, in __init__
    train_dataset = train_dataset.map(
  File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py", line 560, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py", line 3055, in map
    for rank, done, content in Dataset._map_single(**dataset_kwargs):
  File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py", line 3428, in _map_single
    example = apply_function_on_filtered_inputs(example, i, offset=offset)
  File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py", line 3320, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/trl/data_utils.py", line 186, in maybe_apply_chat_template
    return apply_chat_template(example, tokenizer)
  File "/usr/local/lib/python3.10/dist-packages/trl/data_utils.py", line 119, in apply_chat_template
    raise ValueError(error_message.format(prompt, prompt_rejected))
ValueError: The chat template applied to the prompt + completion does not start with the chat template applied to the prompt alone. This can indicate that the chat template is not supported by TRL.
```

### Expected behavior

Work

### Checklist

- [X] I have checked that my issue isn't already filed (see [open issues](https://github.com/huggingface/trl/issues?q=is%3Aissue))
- [X] I have included my system information
- [X] Any code provided is minimal, complete, and reproducible ([more on MREs](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))
- [X] Any code provided is properly formatted in code blocks, (no screenshot, [more on code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))
- [X] Any traceback provided is complete

**Comment by qgallouedec** [comment]
Thanks for reporting. It likely comes from the chat template. Can you share it?

**Comment by qgallouedec** [comment]
The further explain the error, we expect that

```python
formatted_prompt = tokenizer.apply_chat_template(prompt)
formatted_prompt_completion = tokenizer.apply_chat_template(prompt + completion)
assert formatted_prompt_completion.startswith(formatted_prompt)
```

**Comment by qgallouedec** [comment]
It may come from here in you example:


```diff
  ds = ds.map(
      lambda x: {
          "system": [{"role": "user", "content": x["system"]}],
          "prompt": [{"role": "user", "content": x["prompt"]}],
          "chosen": [{"role": "assistant", "content": x["chosen"]}],
-         "rejected": [{"role": "user", "content": x["rejected"]}],
+         "rejected": [{"role": "assistant", "content": x["rejected"]}],
      }
  )
```
