### ISSUE TITLE
"input_ids" not found in rloo trainer

### ISSUE THREAD

**Issue by scarafoni** [huggingface/trl#2434]
### System Info

- Platform: Linux-5.15.0-126-generic-x86_64-with-glibc2.35
- Python version: 3.10.15
- PyTorch version: 2.5.1
- CUDA device(s): NVIDIA GeForce RTX 3090
- Transformers version: 4.46.3
- Accelerate version: 1.1.1
- Accelerate config: not found
- Datasets version: 3.1.0
- HF Hub version: 0.26.3
- TRL version: 0.12.1
- bitsandbytes version: not installed
- DeepSpeed version: not installed
- Diffusers version: not installed
- Liger-Kernel version: not installed
- LLM-Blender version: not installed
- OpenAI version: not installed
- PEFT version: not installed

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

```python
from trl import RLOOConfig, RLOOTrainer, apply_chat_template
from datasets import Dataset, DatasetDict
from datasets import load_dataset
from transformers import (
    AutoModelForCausalLM,
    AutoModelForSequenceClassification,
    AutoTokenizer,
)

tokenizer = AutoTokenizer.from_pretrained("reward_train_test/checkpoint-75")
reward_model = AutoModelForSequenceClassification.from_pretrained(
    "reward_train_test/checkpoint-75", num_labels=1
)

# chat = [
#   {"role": "user", "content": "Hello, how are you?"},
#   {"role": "assistant", "content": "I'm doing great. How can I help you today?"},
#   {"role": "user", "content": "I'd like to show off how chat templating works!"},
# ]
# result = tokenizer.apply_chat_template(chat, tokenize=False)

ref_policy = AutoModelForCausalLM.from_pretrained("reward_train_test/checkpoint-75")
policy = AutoModelForCausalLM.from_pretrained("reward_train_test/checkpoint-75")

# dataset = load_dataset("json", data_files="processed_finetuning_small_rloo.jsonl")
# dataset = load_dataset("trl-lib/ultrafeedback-prompt")
dataset = load_dataset('json', data_files={'train': 'processed_finetuning_small_rloo.jsonl', 'test': 'processed_finetuning_small_rloo.jsonl'})

tokenizer2 = AutoTokenizer.from_pretrained("reward_train_test/checkpoint-75")
tokenizer.chat_template = tokenizer2.chat_template
dataset = dataset.map(apply_chat_template, fn_kwargs={"tokenizer": tokenizer})
dataset = dataset.map(lambda x: tokenizer(x["prompt"]), remove_columns="prompt")

training_args = RLOOConfig(output_dir="./rloo_test")
trainer = RLOOTrainer(
    config=training_args,
    tokenizer=tokenizer,
    policy=policy,
    ref_policy=ref_policy,
    reward_model=reward_model,
    train_dataset=dataset['train'],
    eval_dataset=dataset['test']
)
trainer.train()
```

outputs:

```
Generating train split: 4 examples [00:00, 1133.83 examples/s]                                                                                                           
Generating test split: 4 examples [00:00, 2192.53 examples/s]                                                                                                            
Map: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 100.09 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 932.84 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 240.37 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 643.94 examples/s]
===training policy===                                                                                                                                                    
  0%|                                                                                                                                              | 0/2 [00:00<?, ?it/s]
From v4.47 onwards, when a model cache is to be returned, `generate` will return a `Cache` instance instead by default (as opposed to the legacy tuple of tuples format).
 If you want to keep returning the legacy format, please set `return_legacy_cache=True`.                                                                                 
{'eps': 1, 'objective/kl': 5.4356842041015625, 'objective/entropy': 39.955928802490234, 'objective/non_score_reward': -0.2717842161655426, 'objective/rlhf_reward': -9.04
520034790039, 'objective/scores': -8.773416519165039, 'policy/approxkl_avg': 66790.4140625, 'policy/clipfrac_avg': 0.46875, 'loss/policy_avg': 6.624532222747803, 'loss/v
alue_avg': 0.0, 'val/clipfrac_avg': 0.0, 'policy/entropy_avg': 0.6693519353866577, 'val/ratio': 1.7471365928649902, 'val/ratio_var': 0.2629108130931854, 'val/num_eos_tok
ens': 0, 'lr': 5e-05, 'episode': 8, 'epoch': 2.0}                                                                                                                        
5it [00:04,  1.24it/s]                                                                                                                                                   
Traceback (most recent call last):                                                                                                                                       
  File "/root/symphonyai/docs/24-11-14_query_optimizer_hfrl/rloo.py", line 44, in <module>                                                                               
    trainer.train()                                                                                                                                                      
  File "/opt/conda/envs/autogen/lib/python3.10/site-packages/trl/trainer/rloo_trainer.py", line 494, in train                                                            
    self.generate_completions(sampling=True)                                                                                                                             
  File "/opt/conda/envs/autogen/lib/python3.10/site-packages/trl/trainer/rloo_trainer.py", line 516, in generate_completions                                             
    query = batch["input_ids"]                                                                                                                                           
TypeError: 'NoneType' object is not subscriptable
5it [00:16,  3.32s/it]
```

### Expected behavior

it should train the RLOOTrainer as per normal

### Checklist

- [X] I have checked that my issue isn't already filed (see [open issues](https://github.com/huggingface/trl/issues?q=is%3Aissue))
- [X] I have included my system information
- [X] Any code provided is minimal, complete, and reproducible ([more on MREs](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))
- [X] Any code provided is properly formatted in code blocks, (no screenshot, [more on code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))
- [X] Any traceback provided is complete

**Comment by scarafoni** [comment]
another update- the issue is occurring on this line in rloo_trainer.py

```python
        self.eval_dataloader = DataLoader(
            self.eval_dataset,
            batch_size=args.per_device_eval_batch_size,
            collate_fn=DataCollatorWithPadding(self.processing_class),
            drop_last=True,
        )  # no need to shuffle eval dataset
```
The dataloader is of length 0 but the dataset is not

**Comment by scarafoni** [comment]
I solved the problem- the code was being run on a dummy test set and the dataloader was estimating the length to be 0 because there were not enough samples in it
