### ISSUE TITLE
RAM requirement for simple SFT example

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [huggingface/trl#2460]
How much RAM should this simple fine-tuning example take?
Is it the size of the dataset plus the size of the model? Because for me, it tries to use 32GB+ RAM 
The memory explosion happens at 
https://github.com/huggingface/transformers/blob/5fcf6286bff90a2ba3b7a4b45fdf8542ea404dbe/src/transformers/trainer.py#L3721

 ```py
from trl import SFTConfig, SFTTrainer
from datasets import load_dataset

dataset = load_dataset("trl-lib/Capybara", split="train")

training_args = SFTConfig(output_dir="Qwen/Qwen2.5-0.5B-SFT")
trainer = SFTTrainer(
    args=training_args,
    model="Qwen/Qwen2.5-0.5B",
    train_dataset=dataset,
)
trainer.train()
 ```

**Comment by qgallouedec** [comment]
The dataset is not loaded in RAM (only the current batch).
The training should be rather light in terms of RAM, as the weights and gradient are on the GPU. You'll still need enough RAM to load the model though.
When I run the experiment, I see that it requires less than 2GB of RAM.

**Comment by Kallinteris-Andreas** [comment]
What CPU do you have (exact model)
and does DRAM usage explode when you run `CUDA_VISIBLE_DEVICES="" python test.py`

by current best guess is that it is a BF16 related issue (as my r5 4600h does not natively support it)

**Comment by Kallinteris-Andreas** [comment]
GPU does not work for me (works for my other RL projects)
```sh
$ PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True py test.py
[2024-12-11 16:34:26,123] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cuda (auto detect)
No ROCm runtime is found, using ROCM_HOME='/opt/rocm'
  0%|                                                                                                             | 0/3 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/master-andreas/job/trl-test/test.py", line 16, in <module>
    trainer.train()
  File "/home/master-andreas/job/trl-test/transformers-kalli/src/transformers/trainer.py", line 2164, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/master-andreas/job/trl-test/transformers-kalli/src/transformers/trainer.py", line 2522, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/master-andreas/job/trl-test/transformers-kalli/src/transformers/trainer.py", line 3667, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/master-andreas/job/trl-test/transformers-kalli/src/transformers/trainer.py", line 3721, in compute_loss
    outputs = model(**inputs)
              ^^^^^^^^^^^^^^^
  File "/home/master-andreas/job/trl-test/test_env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/master-andreas/job/trl-test/test_env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/master-andreas/job/trl-test/transformers-kalli/src/transformers/models/qwen2/modeling_qwen2.py", line 1140, in forward
    outputs = self.model(
              ^^^^^^^^^^^
  File "/home/master-andreas/job/trl-test/test_env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/master-andreas/job/trl-test/test_env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/master-andreas/job/trl-test/transformers-kalli/src/transformers/models/qwen2/modeling_qwen2.py", line 870, in forward
    layer_outputs = decoder_layer(
                    ^^^^^^^^^^^^^^
  File "/home/master-andreas/job/trl-test/test_env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/master-andreas/job/trl-test/test_env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/master-andreas/job/trl-test/transformers-kalli/src/transformers/models/qwen2/modeling_qwen2.py", line 613, in forward
    hidden_states = self.mlp(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/master-andreas/job/trl-test/test_env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/master-andreas/job/trl-test/test_env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/master-andreas/job/trl-test/transformers-kalli/src/transformers/models/qwen2/modeling_qwen2.py", line 223, in forward
    return self.down_proj(self.act_fn(self.gate_proj(hidden_state)) * self.up_proj(hidden_state))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/master-andreas/job/trl-test/test_env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/master-andreas/job/trl-test/test_env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/master-andreas/job/trl-test/test_env/lib/python3.12/site-packages/torch/nn/modules/activation.py", line 432, in forward
    return F.silu(input, inplace=self.inplace)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/master-andreas/job/trl-test/test_env/lib/python3.12/site-packages/torch/nn/functional.py", line 2380, in silu
    return torch._C._nn.silu(input)
           ^^^^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 38.00 MiB. GPU 0 has a total capacity of 3.63 GiB of which 11.31 MiB is free. Including non-PyTorch memory, this process has 3.55 GiB memory in use. Of the allocated memory 3.47 GiB is allocated by PyTorch, and 8.16 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
  0%|          | 0/3 [00:00<?, ?it/s]
```

**Comment by Kallinteris-Andreas** [comment]
Here is the dram usage per value of `max_seq_lenght`

max_seq_length -> max RAM usage observed (rounded up)
4 -> 10GB DRAM
32 -> 9GB DRAM
128 -> 11GB DRAM
512 -> 18GB DRAM
1024 (default) -> 32GB+ DRAM

using `max_seq_length=128` seems to require 28 hours on my CPU which is an improvement from not running at all.
I am not sure what `max_seq_length` actually does, I am assuming it limits the context length used during fine-tuning the docstring mentions something about `ConstantLengthDataset` but I have not found it what it is.

**Comment by qgallouedec** [comment]
>  I am assuming it limits the context length used during fine-tuning

Yes, that's what it does.

> mentions something about ConstantLengthDataset but I have not found it what it is.

This is a special dataset setting where all data have the same length. Not relevant for this issue though

**Comment by Kallinteris-Andreas** [comment]
How much time does it take to run this simple example on your hardware?
```py
from trl import SFTConfig, SFTTrainer
from datasets import load_dataset

dataset = load_dataset("trl-lib/Capybara", split="train")

training_args = SFTConfig(output_dir="Qwen/Qwen2.5-0.5B-SFT", max_seq_length=128)
trainer = SFTTrainer(
    args=training_args,
    model="Qwen/Qwen2.5-0.5B",
    train_dataset=dataset,
)
trainer.train()
```

**Comment by Kallinteris-Andreas** [comment]
Closing, as it appears to be the natural requirement of SFT
