### ISSUE TITLE
Input_ids not automatically convert to device 

### ISSUE THREAD

**Issue by Naowak** [huggingface/trl#502]
Hi, when trying to run and tweak a little bit the examples from the doc with a MacBook m1 I met some problems. 

I had the following error : 
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[8], line 26
     21 query_tensor = tokenizer.encode(query_txt, return_tensors="pt")
     23 while True:
     24 
     25     # get model response
---> 26     response_tensor  = respond_to_batch(model, query_tensor)
     28     # create a ppo trainer
     29     ppo_trainer = PPOTrainer(ppo_config, model, model_ref, tokenizer)

File [/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/trl/core.py:212](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/trl/core.py:212), in respond_to_batch(model, queries, txt_len, top_k, top_p)
    209 input_ids = queries
    210 for i in range(txt_len):
    211     # Get Logits
--> 212     outputs = model(input_ids)
    213     next_token_logits = outputs[0][:, -1, :]
    214     next_token_logits = top_k_top_p_filtering(next_token_logits, top_k=top_k, top_p=top_p)

File [/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/modules/module.py:1501](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/modules/module.py:1501), in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

File [/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/trl/models/modeling_value_head.py:161](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/trl/models/modeling_value_head.py:161), in AutoModelForCausalLMWithValueHead.forward(self, input_ids, past_key_values, attention_mask, **kwargs)
    143 r"""
    144 Applies a forward pass to the wrapped model and returns the logits of the value head.
    145 
   (...)
    157         Additional keyword arguments, that are passed to the wrapped model.
    158 """
    159 kwargs["output_hidden_states"] = True  # this had already been set in the LORA [/](https://file+.vscode-resource.vscode-cdn.net/) PEFT examples
--> 161 base_model_output = self.pretrained_model(
    162     input_ids=input_ids,
    163     past_key_values=past_key_values,
    164     attention_mask=attention_mask,
    165     **kwargs,
    166 )
    168 last_hidden_state = base_model_output.hidden_states[-1]
    169 lm_logits = base_model_output.logits

File [/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/modules/module.py:1501](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/modules/module.py:1501), in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

File [/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/models/gpt2/modeling_gpt2.py:1080](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/models/gpt2/modeling_gpt2.py:1080), in GPT2LMHeadModel.forward(self, input_ids, past_key_values, attention_mask, token_type_ids, position_ids, head_mask, inputs_embeds, encoder_hidden_states, encoder_attention_mask, labels, use_cache, output_attentions, output_hidden_states, return_dict)
   1072 r"""
   1073 labels (`torch.LongTensor` of shape `(batch_size, sequence_length)`, *optional*):
   1074     Labels for language modeling. Note that the labels **are shifted** inside the model, i.e. you can set
   1075     `labels = input_ids` Indices are selected in `[-100, 0, ..., config.vocab_size]` All labels set to `-100`
   1076     are ignored (masked), the loss is only computed for labels in `[0, ..., config.vocab_size]`
   1077 """
   1078 return_dict = return_dict if return_dict is not None else self.config.use_return_dict
-> 1080 transformer_outputs = self.transformer(
   1081     input_ids,
   1082     past_key_values=past_key_values,
   1083     attention_mask=attention_mask,
   1084     token_type_ids=token_type_ids,
   1085     position_ids=position_ids,
   1086     head_mask=head_mask,
   1087     inputs_embeds=inputs_embeds,
   1088     encoder_hidden_states=encoder_hidden_states,
   1089     encoder_attention_mask=encoder_attention_mask,
   1090     use_cache=use_cache,
   1091     output_attentions=output_attentions,
   1092     output_hidden_states=output_hidden_states,
   1093     return_dict=return_dict,
   1094 )
   1095 hidden_states = transformer_outputs[0]
   1097 # Set device for model parallelism

File [/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/modules/module.py:1501](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/modules/module.py:1501), in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

File [/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/models/gpt2/modeling_gpt2.py:846](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/models/gpt2/modeling_gpt2.py:846), in GPT2Model.forward(self, input_ids, past_key_values, attention_mask, token_type_ids, position_ids, head_mask, inputs_embeds, encoder_hidden_states, encoder_attention_mask, use_cache, output_attentions, output_hidden_states, return_dict)
    843 head_mask = self.get_head_mask(head_mask, self.config.n_layer)
    845 if inputs_embeds is None:
--> 846     inputs_embeds = self.wte(input_ids)
    847 position_embeds = self.wpe(position_ids)
    848 hidden_states = inputs_embeds + position_embeds

File [/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/modules/module.py:1501](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/modules/module.py:1501), in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

File [/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/modules/sparse.py:162](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/modules/sparse.py:162), in Embedding.forward(self, input)
    161 def forward(self, input: Tensor) -> Tensor:
--> 162     return F.embedding(
    163         input, self.weight, self.padding_idx, self.max_norm,
    164         self.norm_type, self.scale_grad_by_freq, self.sparse)

File [/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/functional.py:2210](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/functional.py:2210), in embedding(input, weight, padding_idx, max_norm, norm_type, scale_grad_by_freq, sparse)
   2204     # Note [embedding_renorm set_grad_enabled]
   2205     # XXX: equivalent to
   2206     # with torch.no_grad():
   2207     #   torch.embedding_renorm_
   2208     # remove once script supports set_grad_enabled
   2209     _no_grad_embedding_renorm_(weight, input, max_norm, norm_type)
-> 2210 return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)

RuntimeError: Placeholder storage has not been allocated on MPS device!
```

Here is the code I ran to get this error : 
```
# imports
import torch
from transformers import AutoTokenizer
from trl import PPOTrainer, PPOConfig, AutoModelForCausalLMWithValueHead, create_reference_model
from trl.core import respond_to_batch

# get models
model = AutoModelForCausalLMWithValueHead.from_pretrained('gpt2')
model_ref = create_reference_model(model)

tokenizer = AutoTokenizer.from_pretrained('gpt2')
tokenizer.pad_token = tokenizer.eos_token

# initialize trainer
ppo_config = PPOConfig(
    batch_size=1,
)

# create a ppo trainer
ppo_trainer = PPOTrainer(ppo_config, model, model_ref, tokenizer)

# encode a query
query_txt = "This morning I went to the "
query_tensor = tokenizer.encode(query_txt, return_tensors="pt").to("mps:0")

while True:

    # get model response
    response_tensor  = respond_to_batch(model, query_tensor)

    # define a reward for response
    # (this could be any reward such as human feedback or output from another model)
    reward = [torch.tensor(1.0)]

    # train model for one step with ppo
    train_stats = ppo_trainer.step([query_tensor[0]], [response_tensor[0]], reward)
```

The funny thing is that if the PPOTrainer is create after the respond_to_batch, it works on the first iteration of the loop but not the second : 
```
# imports
import torch
from transformers import AutoTokenizer
from trl import PPOTrainer, PPOConfig, AutoModelForCausalLMWithValueHead, create_reference_model
from trl.core import respond_to_batch

# get models
model = AutoModelForCausalLMWithValueHead.from_pretrained('gpt2')
model_ref = create_reference_model(model)

tokenizer = AutoTokenizer.from_pretrained('gpt2')
tokenizer.pad_token = tokenizer.eos_token

# initialize trainer
ppo_config = PPOConfig(
    batch_size=1,
)

# encode a query
query_txt = "This morning I went to the "
query_tensor = tokenizer.encode(query_txt, return_tensors="pt")

while True:

    print('hello')

    # get model response
    response_tensor  = respond_to_batch(model, query_tensor)

    # create a ppo trainer
    ppo_trainer = PPOTrainer(ppo_config, model, model_ref, tokenizer)

    # define a reward for response
    # (this could be any reward such as human feedback or output from another model)
    reward = [torch.tensor(1.0)]

    # train model for one step with ppo
    train_stats = ppo_trainer.step([query_tensor[0]], [response_tensor[0]], reward)
```

I figured out that inputs_ids where on device `cpu` and the model on `mps:0`.
So I updated the PPOTrainer example like this :
`query_tensor = tokenizer.encode(query_txt, return_tensors="pt")`
to 
`query_tensor = tokenizer.encode(query_txt, return_tensors="pt").to("mps:0")`

It fixes my issue and now everything works as expected with the PPOTrainer, but the issue persist with the SFTTrainer example, and I didn't test the RewardTrainer.

I investigate a little bit, but I didn't find a relevant place to make a modification in the package so that the input_ids are converted  automatically.

I hope everything I said was clear :)
Have a good day and thanks for maintaining this package !

**Comment by younesbelkada** [comment]
Hi @Naowak 
Thanks for the message ! 
Just to make sure I have the entire context, how do you run the script? `python xxxx.py` or with something else? Can you try to run the script with `accelerate launch xxxx.py` after making sure you have selected MPS when running `accelerate config`

**Comment by Naowak** [comment]
I ran the script in a notebook in vscode. I just change `facebook/opt-350m` to `gpt2` : 

```
# imports
from datasets import load_dataset
from trl import SFTTrainer

# get dataset
dataset = load_dataset("imdb", split="train")

# get trainer
trainer = SFTTrainer(
    "facebook/opt-350m",
    train_dataset=dataset,
    dataset_text_field="text",
    max_seq_length=512,
)

# train
trainer.train()
```


_____

Ok so I made that config with `accelerate config` (no everywhere) : 
```
------------------------------------------------------------------------------------------------------------------------In which compute environment are you running?
This machine
------------------------------------------------------------------------------------------------------------------------Which type of machine are you using?
No distributed training
Do you want to run your training on CPU only (even if a GPU / Apple Silicon device is available)? [yes/NO]:
Do you wish to optimize your script with torch dynamo?[yes/NO]:
------------------------------------------------------------------------------------------------------------------------Do you wish to use FP16 or BF16 (mixed precision)?
no
accelerate configuration saved at /Users/naowak/.cache/huggingface/accelerate/default_config.yaml
```

I created a file called `sfftrainer.py` and copy the script from above in it. And get :

```
$ accelerate launch sfttrainer.py
Found cached dataset imdb (/Users/naowak/.cache/huggingface/datasets/imdb/plain_text/1.0.0/d613c88cf8fa3bab83b4ded3713f1f74830d1100e171db75bbddb80b3345c9c0)
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/trl/trainer/sft_trainer.py:117: UserWarning: You passed a model_id to the SFTTrainer. This will automatically create an `AutoModelForCausalLM` or a `PeftModel` (if you passed a `peft_config`) for you.
  warnings.warn(
Using pad_token, but it is not set yet.
Loading cached processed dataset at /Users/naowak/.cache/huggingface/datasets/imdb/plain_text/1.0.0/d613c88cf8fa3bab83b4ded3713f1f74830d1100e171db75bbddb80b3345c9c0/cache-6625bfcc4ca80be1.arrow
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
  0%|                                                                                          | 0/9375 [00:00<?, ?it/s]You're using a GPT2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
Traceback (most recent call last):
  File "/Users/naowak/Work/BattleFieldAgents/api/sfttrainer.py", line 17, in <module>
    trainer.train()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/trainer.py", line 1645, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/trainer.py", line 1938, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/trainer.py", line 2759, in training_step
    loss = self.compute_loss(model, inputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/trainer.py", line 2784, in compute_loss
    outputs = model(**inputs)
              ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 1080, in forward
    transformer_outputs = self.transformer(
                          ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 846, in forward
    inputs_embeds = self.wte(input_ids)
                    ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
           ^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/functional.py", line 2211, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Placeholder storage has not been allocated on MPS device!
  0%|                                                                                          | 0/9375 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/accelerate/commands/launch.py", line 941, in launch_command
    simple_launcher(args)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/accelerate/commands/launch.py", line 603, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/python', 'sfttrainer.py']' returned non-zero exit status 1.
```

It seems to be the same error. :/

**Comment by younesbelkada** [comment]
what version of transformers are you using?

**Comment by Naowak** [comment]
```
Python 3.11.4 (v3.11.4:d2340ef257, Jun  6 2023, 19:15:51) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import transformers
>>> transformers.__version__
'4.30.2'
```

Version `4.30.2`
