### ISSUE TITLE
Support for Falcon-7B

### ISSUE THREAD

**Issue by DakeZhang1998** [huggingface/trl#514]
Just to confirm, trl does not support newer models like Falcon-7B, right? I tried to load the Falcon-7B using `AutoModelForCausalLMWithValueHead.from_pretrained()`, but it throws an error in the PPOTrainer.
```
Traceback (most recent call last):
  File "/lustre07/scratch/dake1/DeepLearningTrack/RL_BM25/old/train.py", line 85, in <module>
    ppo_trainer = PPOTrainer(config, model, None, tokenizer, dataset=dataset, data_collator=collator) 
         File "/lustre06/project/6003284/dake1/ENVs/pytorch2/lib/python3.11/site-packages/trl/trainer/ppo_trainer.py", line 185, in __init__ raise ValueError(
ValueErrorValueError: : ValueErrormodel must be a PreTrainedModelWrapper, got <class 'transformers_modules.mpt-30b-instruct.modeling_mpt.MPTForCausalLM'> - supported architectures are: (<class 'trl.models.modeling_value_head.AutoModelForCausalLMWithValueHead'>, <class 'trl.models.modeling_value_head.AutoModelForSeq2SeqLMWithValueHead'>)
```
Thanks!

**Comment by younesbelkada** [comment]
Hi @DakeZhang1998 
Thanks for the issue, I think it should be supported out of the box if you load the `AutoModelForCausalLM` outside the declaration of `AutoModelForCausalLMWithValueHead`. Can you share the small snippet where you load the model? Thanks!

**Comment by lvwerra** [comment]
In general, we support all decoder and encoder-decoder models that are supported in `transformers`. It looks like you are not loading Falcon-7B but `transformers_modules.mpt-30b-instruct.modeling_mpt.MPTForCausalLM`. Can you share the full code causing the issue or the script you used?

**Comment by DakeZhang1998** [comment]
Sorry for the wrong traceback in my initial post.
I tried to load Falcon-7B using the following code derived from one of your examples.
```
model = AutoModelForCausalLMWithValueHead.from_pretrained(config.model_name, cache_dir='../../huggingface/',
                                                          trust_remote_code=True, device_map='auto')
ref_model = AutoModelForCausalLMWithValueHead.from_pretrained(config.model_name, cache_dir='../../huggingface/',
                                                              trust_remote_code=True, device_map='auto')
tokenizer = AutoTokenizer.from_pretrained(config.model_name, cache_dir='../../huggingface/')
# GPT-2 tokenizer has a pad token, but it is not eos_token by default. We need to set it to eos_token.
# only for this model.
tokenizer.pad_token = tokenizer.eos_token

# We then build the PPOTrainer, passing the model, the reference model, the tokenizer
ppo_trainer = PPOTrainer(config, model, ref_model, tokenizer, dataset=dataset, data_collator=collator)
```
I used a cloud machine with two A100 GPUs to do naive pipeline parallelism because one GPU does not have enough memory to fully fine-tune 7B models.
And I got the following error:
```
Traceback (most recent call last):
  File "/project/6003284/dake1/DeepLearningTrack/RL_BM25/old/train.py", line 86, in <module>
Traceback (most recent call last):
  File "/project/6003284/dake1/DeepLearningTrack/RL_BM25/old/train.py", line 86, in <module>
    ppo_trainer = PPOTrainer(config, model, ref_model, tokenizer, dataset=dataset, data_collator=collator)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/6003284/dake1/DeepLearningTrack/env/py3.11/lib/python3.11/site-packages/trl/trainer/ppo_trainer.py", line 293, in __init__
    ) = self.accelerator.prepare(
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/6003284/dake1/DeepLearningTrack/env/py3.11/lib/python3.11/site-packages/accelerate/accelerator.py", line 1182, in prepare
    result = tuple(
             ^^^^^^
  File "/project/6003284/dake1/DeepLearningTrack/env/py3.11/lib/python3.11/site-packages/accelerate/accelerator.py", line 1183, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/6003284/dake1/DeepLearningTrack/env/py3.11/lib/python3.11/site-packages/accelerate/accelerator.py", line 1022, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/6003284/dake1/DeepLearningTrack/env/py3.11/lib/python3.11/site-packages/accelerate/accelerator.py", line 1275, in prepare_model
    ppo_trainer = PPOTrainer(config, model, ref_model, tokenizer, dataset=dataset, data_collator=collator)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/6003284/dake1/DeepLearningTrack/env/py3.11/lib/python3.11/site-packages/trl/trainer/ppo_trainer.py", line 293, in __init__
    model = torch.nn.parallel.DistributedDataParallel(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/6003284/dake1/DeepLearningTrack/env/py3.11/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 603, in __init__
    ) = self.accelerator.prepare(
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/6003284/dake1/DeepLearningTrack/env/py3.11/lib/python3.11/site-packages/accelerate/accelerator.py", line 1182, in prepare
    self._log_and_throw(
  File "/project/6003284/dake1/DeepLearningTrack/env/py3.11/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 769, in _log_and_throw
    raise err_type(err_msg)
ValueError: DistributedDataParallel device_ids and output_device arguments only work with single-device/multiple-device GPU modules or CPU modules, but got device_ids [1], output_device 1, and module parameters {device(type='cuda', index=0), device(type='cuda', index=1)}.
    result = tuple(
             ^^^^^^
  File "/project/6003284/dake1/DeepLearningTrack/env/py3.11/lib/python3.11/site-packages/accelerate/accelerator.py", line 1183, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/6003284/dake1/DeepLearningTrack/env/py3.11/lib/python3.11/site-packages/accelerate/accelerator.py", line 1022, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/6003284/dake1/DeepLearningTrack/env/py3.11/lib/python3.11/site-packages/accelerate/accelerator.py", line 1275, in prepare_model
    model = torch.nn.parallel.DistributedDataParallel(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/6003284/dake1/DeepLearningTrack/env/py3.11/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 603, in __init__
    self._log_and_throw(
  File "/project/6003284/dake1/DeepLearningTrack/env/py3.11/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 769, in _log_and_throw
    raise err_type(err_msg)
ValueError: DistributedDataParallel device_ids and output_device arguments only work with single-device/multiple-device GPU modules or CPU modules, but got device_ids [0], output_device 0, and module parameters {device(type='cuda', index=0), device(type='cuda', index=1)}.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 36678) of binary: /project/6003284/dake1/DeepLearningTrack/env/py3.11/bin/python
Traceback (most recent call last):
  File "/project/6003284/dake1/DeepLearningTrack/env/py3.11/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/project/6003284/dake1/DeepLearningTrack/env/py3.11/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/project/6003284/dake1/DeepLearningTrack/env/py3.11/lib/python3.11/site-packages/accelerate/commands/launch.py", line 932, in launch_command
    multi_gpu_launcher(args)
  File "/project/6003284/dake1/DeepLearningTrack/env/py3.11/lib/python3.11/site-packages/accelerate/commands/launch.py", line 627, in multi_gpu_launcher
    distrib_run.run(args)
  File "/project/6003284/dake1/DeepLearningTrack/env/py3.11/lib/python3.11/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/project/6003284/dake1/DeepLearningTrack/env/py3.11/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/6003284/dake1/DeepLearningTrack/env/py3.11/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-07-13_21:19:47
  host      : gra1342.graham.sharcnet
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 36679)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-13_21:19:47
  host      : gra1342.graham.sharcnet
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 36678)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```
Not sure whether it is caused by Falcon-7B or that I use this framework wrongly. (PS: Is there a way to only print those error messages once? I searched around and haven't found a way to do so.)
Thanks!
