### ISSUE TITLE
peft 0.3 not working

### ISSUE THREAD

**Issue by jsnyderTC** [huggingface/trl#580]
I was working off [this example](https://huggingface.co/blog/llama2#fine-tuning-with-peft) and found that the code there was not working with an environment i already have established.

Specifically, the code

```
python trl/examples/scripts/sft_trainer.py \
    --model_name meta-llama/Llama-2-7b-hf \
    --dataset_name timdettmers/openassistant-guanaco \
    --load_in_4bit \
    --use_peft \
    --batch_size 4 \
    --gradient_accumulation_steps 2
```

Yielded the traceback

```
Traceback (most recent call last):
  File "/.../trl/./examples/scripts/sft_trainer.py", line 115, in <module>
    trainer = SFTTrainer(
  File "/.../anaconda3/envs/huggingfaceLLM/lib/python3.10/site-packages/trl/trainer/sft_trainer.py", line 143, $
    model = get_peft_model(model, peft_config)
  File "/.../anaconda3/envs/huggingfaceLLM/lib/python3.10/site-packages/peft/mapping.py", line 120, in get_peft$
    return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](model, peft_config)
  File "/.../anaconda3/envs/huggingfaceLLM/lib/python3.10/site-packages/peft/peft_model.py", line 662, in __ini$
    super().__init__(model, peft_config, adapter_name)
  File "/.../anaconda3/envs/huggingfaceLLM/lib/python3.10/site-packages/peft/peft_model.py", line 99, in __init$
    self.base_model = PEFT_TYPE_TO_MODEL_MAPPING[peft_config.peft_type](
  File "/.../anaconda3/envs/huggingfaceLLM/lib/python3.10/site-packages/peft/tuners/lora.py", line 154, in __in$
    self.add_adapter(adapter_name, self.peft_config[adapter_name])
  File "/.../anaconda3/envs/huggingfaceLLM/lib/python3.10/site-packages/peft/tuners/lora.py", line 161, in add_$
    self._find_and_replace(adapter_name)
  File "/.../anaconda3/envs/huggingfaceLLM/lib/python3.10/site-packages/peft/tuners/lora.py", line 250, in _fin$
    new_module = Linear(adapter_name, in_features, out_features, bias=bias, **kwargs)
  File "/.../anaconda3/envs/huggingfaceLLM/lib/python3.10/site-packages/peft/tuners/lora.py", line 520, in __in$
    self.update_layer(adapter_name, r, lora_alpha, lora_dropout, init_lora_weights)
  File "/.../anaconda3/envs/huggingfaceLLM/lib/python3.10/site-packages/peft/tuners/lora.py", line 447, in upda$
    if lora_dropout > 0.0:
TypeError: '>' not supported between instances of 'NoneType' and 'float'
```

I created a new environment and everything worked fine.  I saw the requirements.txt lists peft >=0.3, which was satisfied by my non working environment.  Just wanted to report this.

```
# Non working env
# datasets                 2.12.0
# torch                    2.0.1+cu118
# tqdm                     4.65.0
# transformers             4.29.2
# accelerate               0.19.0
# peft                     0.3.0

# Working env
# datasets                 2.14.0
# torch                    2.0.1
# tqdm                     4.65.0
# transformers             4.31.0
# accelerate               0.21.0
# peft                     0.4.0
```

**Comment by younesbelkada** [comment]
Indeed, maybe we should bump the peft required version to 0.4.0, wdyt @lvwerra ?

**Comment by lvwerra** [comment]
Happy to bump it - I trust your knowledge on PEFT. Since it's a fast evolving library i think we probably have to do that semi-regularly.
