### ISSUE TITLE
Mlflow support for PPOConfig (PPO Trainer)

### ISSUE THREAD

**Issue by ghtaro** [huggingface/trl#658]
Hi,

I am working on a small project to use trl for SFT/RLHF.
On my environment, I usually track the training status via mlflow for all the projects.
Looking at https://github.com/huggingface/trl/blob/c83fad65128873e506fc19d0d49210030b1d7665/trl/trainer/ppo_config.py#L119, mlflow is not yet supported...

Is there any workaround to use mlflow in trl PPO?

Thank you very much for your help.

**Comment by younesbelkada** [comment]
We use `accelerate`'s Accelerator under the hood to track the experiments, according to the official documentation, MlFlow seems to be supported: https://huggingface.co/docs/accelerate/usage_guides/tracking can you try to follow the instructions on the documentation and let us know if this works ? ( I think `log_with="all"`) should do the trick

**Comment by ghtaro** [comment]
Hi @younesbelkada , thank you very much for your quick suggestion.

I am using a customized version of trl/examples/stack_llama/scripts/rl_training.py (probably a bit old version).

I ran the py file with `log_with="mlflow"` and got the following warning (training itself went well but without any experiment tracking).

```
lib/python3.10/site-packages/accelerate/accelerator.py:377: UserWarning: `log_with=mlflow` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
```

I also ran that with `log_with=all`, and got the other error.

```
Traceback (most recent call last):
  File "/Workspace/Repos/toshiya.imoto@japan-d2.com/trl/examples/stack_llama/scripts/rl_training.py", line 293, in <module>
    ppo_trainer = PPOTrainer(
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-6e885779-c44e-41f8-aa58-fe760d7b15f0/lib/python3.10/site-packages/trl/trainer/ppo_trainer.py", line 198, in __init__
    self.accelerator.init_trackers(
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-6e885779-c44e-41f8-aa58-fe760d7b15f0/lib/python3.10/site-packages/accelerate/accelerator.py", line 608, in _inner
    return PartialState().on_main_process(function)(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-6e885779-c44e-41f8-aa58-fe760d7b15f0/lib/python3.10/site-packages/accelerate/accelerator.py", line 2274, in init_trackers
    tracker.store_init_configuration(config)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-6e885779-c44e-41f8-aa58-fe760d7b15f0/lib/python3.10/site-packages/accelerate/tracking.py", line 84, in execute_on_main_process
    return PartialState().on_main_process(function)(self, *args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-6e885779-c44e-41f8-aa58-fe760d7b15f0/lib/python3.10/site-packages/accelerate/tracking.py", line 212, in store_init_configuration
    self.writer.add_hparams(values, metric_dict={})
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-6e885779-c44e-41f8-aa58-fe760d7b15f0/lib/python3.10/site-packages/torch/utils/tensorboard/writer.py", line 336, in add_hparams
    exp, ssi, sei = hparams(hparam_dict, metric_dict, hparam_domain_discrete)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-6e885779-c44e-41f8-aa58-fe760d7b15f0/lib/python3.10/site-packages/torch/utils/tensorboard/summary.py", line 228, in hparams
    raise ValueError(
ValueError: value should be one of int, float, str, bool, or torch.Tensor
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3939) of binary: /local_disk0/.ephemeral_nfs/envs/pythonEnv-6e885779-c44e-41f8-aa58-fe760d7b15f0/bin/python
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-6e885779-c44e-41f8-aa58-fe760d7b15f0/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-6e885779-c44e-41f8-aa58-fe760d7b15f0/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-6e885779-c44e-41f8-aa58-fe760d7b15f0/lib/python3.10/site-packages/accelerate/commands/launch.py", line 977, in launch_command
    multi_gpu_launcher(args)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-6e885779-c44e-41f8-aa58-fe760d7b15f0/lib/python3.10/site-packages/accelerate/commands/launch.py", line 646, in multi_gpu_launcher
    distrib_run.run(args)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-6e885779-c44e-41f8-aa58-fe760d7b15f0/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-6e885779-c44e-41f8-aa58-fe760d7b15f0/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-6e885779-c44e-41f8-aa58-fe760d7b15f0/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
```

**Comment by ghtaro** [comment]
Hi,

I noticed that in https://github.com/huggingface/accelerate/blob/41caaa56e12ea3af1a886a1adb93dcfe3371cef1/src/accelerate/tracking.py#L717 that `log_type` is set to a string ("mlflow") instead of class object.

I changed `issubclass(type(log_type), GeneralTracker)` to `issubclass(LOGGER_TYPE_TO_CLASS[str(log_type)], GeneralTracker)` and ran the rl_training.py, I was able to use mlflow tracker for PPO.

**Comment by younesbelkada** [comment]
Hmmm this is a bit odd, probably that's not the canonical way to log with mlflow using `Accelerator`, cc @muellerzr what is the canonical way to log with mlflow using the accelerator and do we potentially need to upstream any fix on accelerate? 🙏  Thanks !

**Comment by muellerzr** [comment]
Using `log_with="mlflow"` is the cannonical way. This likely means that for some reason we're not picking up MLFlow in your environment. This is the chunk that should execute when doing `"mlflow"` https://github.com/huggingface/accelerate/blob/41caaa56e12ea3af1a886a1adb93dcfe3371cef1/src/accelerate/tracking.py#L718-L730

@ghtaro can you check that the following will return `True`?

```python
from accelerate.utils.imports import is_mlflow_available

print(is_mlflow_available())
```

**Comment by ghtaro** [comment]
@muellerzr sorry for my late reply. 

I have confirmed that it returns False...
![image](https://github.com/huggingface/trl/assets/24857936/ceadf9aa-08cd-4933-9308-5814cb24e846)

I dig out a bit more and found that the below returns False as well.

```
import importlib
importlib.metadata.metadata("mlflow")
```

I use mlflow 2.5.0.  I am now asking technician in my company.

**Comment by muellerzr** [comment]
Great, I'll try and look into this here soon but as I'm unfamiliar with mlflow, if we can find a way to check that `pip show mlflow` comes true and there's a different import we can check, that'd be great!

**Comment by ghtaro** [comment]
@muellerzr I finally found a reason why it happened.

We are using databricks and the computational cluster (Runtime 13.0ML) with mlflow-skinnly (light version of mlflow) installed in the beggining.
 
Setting `log_with=mlflow`,

```
import importlib
importlib.util.find_spec('mlflow') is not None
```
gives True (which is ok), but

```
import importlib
importlib.metadata.metadata("mlflow")
```
gives False (seen above). If I pass "mlflow-skinny" to argument of metadata() funciton, it gives True.

**Comment by muellerzr** [comment]
Awesome work! Would you like to open a pr to accelerate modifying the check to include mlflow-skinny in that function? Otherwise I'll get to that tommorow 😄

**Comment by ghtaro** [comment]
@muellerzr Hi, I opened PR https://github.com/huggingface/accelerate/pull/1874.

I confirmed that it started mlflow logging in my case (trl rl_training.py), but not sure if my coding is in good manner. If any, please let me know.

**Comment by younesbelkada** [comment]
This seems to be fixed now, closing, feel free to re-open if you think that's not the case
