### ISSUE TITLE
DeepSpeed Zero3 dpo accured embedding weight error

### ISSUE THREAD

**Issue by YooSungHyun** [huggingface/trl#669]
i used `Open-Orca/OpenOrca-Platypus2-13B` and dpo error accured
dataset is used `Anthropic/hh-rlhf`

``` python3
Traceback (most recent call last):
  File "/data/workspace/train/train_dpo.py", line 133, in <module>
    main(model_args=model_args, dataset_args=dataset_args, training_args=training_args)
  File "/data/workspace/train/train_dpo.py", line 119, in main
    dpo_trainer.train()
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/transformers/trainer.py", line 1809, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/transformers/trainer.py", line 2654, in training_step
    loss = self.compute_loss(model, inputs)
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/trl/trainer/dpo_trainer.py", line 360, in compute_loss
    loss, metrics = self.get_batch_metrics(model, inputs, train_eval="train")
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/trl/trainer/dpo_trainer.py", line 327, in get_batch_metrics
    ) = self.concatenated_forward(self.ref_model, batch)
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/trl/trainer/dpo_trainer.py", line 290, in concatenated_forward
Traceback (most recent call last):
    all_logits = model(
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 806, in forward
  File "/data/workspace/train/train_dpo.py", line 133, in <module>
    main(model_args=model_args, dataset_args=dataset_args, training_args=training_args)
  File "/data/workspace/train/train_dpo.py", line 119, in main
    dpo_trainer.train()
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
    outputs = self.model(
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/transformers/trainer.py", line 1809, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/transformers/trainer.py", line 2654, in training_step
    loss = self.compute_loss(model, inputs)
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/trl/trainer/dpo_trainer.py", line 360, in compute_loss
    loss, metrics = self.get_batch_metrics(model, inputs, train_eval="train")
    return forward_call(*args, **kwargs)
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 646, in forward
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/trl/trainer/dpo_trainer.py", line 327, in get_batch_metrics
    ) = self.concatenated_forward(self.ref_model, batch)
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/trl/trainer/dpo_trainer.py", line 290, in concatenated_forward
    all_logits = model(
    inputs_embeds = self.embed_tokens(input_ids)
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 806, in forward
    outputs = self.model(
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 646, in forward
    inputs_embeds = self.embed_tokens(input_ids)
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
    return forward_call(*args, **kwargs)  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(

  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/torch/nn/functional.py", line 2210, in embedding
RuntimeError: 'weight' must be 2-D
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
```

if i changed model, error accured too.
how can i use zero3?

``` json
{
    "fp16": {
        "enabled": "auto",
        "loss_scale": 0,
        "loss_scale_window": 1000,
        "initial_scale_power": 16,
        "hysteresis": 2,
        "min_loss_scale": 1
    },
    "zero_allow_untested_optimizer": true,
    "zero_force_ds_cpu_optimizer": false,
    "zero_optimization": {
        "stage": 3,
        "offload_optimizer": {
            "device": "cpu",
            "pin_memory": true
        },
        "overlap_comm": true,
        "contiguous_gradients": true,
        "sub_group_size": 5e8,
        "allgather_partitions": true,
        "allgather_bucket_size": 1e10,
        "reduce_bucket_size": "auto",
        "stage3_prefetch_bucket_size": "auto",
        "stage3_param_persistence_threshold": "auto",
        "stage3_max_live_parameters": 1e10,
        "stage3_max_reuse_distance": 1e10,
        "stage3_gather_16bit_weights_on_model_save": true
    },
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "gradient_accumulation_steps": "auto"
}
```

**Comment by lvwerra** [comment]
cc @vwxyzjn who is currently looking at DS

**Comment by YooSungHyun** [comment]
i find that problem is accured by `ref_wav`'s set accelerate initialize....

ref_wav can not prepare for deepspeed. because using just `prepare()` not `prepare_model()`
`prepare_model` is for inference, i think. ref_wav must be freezed but not inference. so that have to on deepspeed.

i just modified, that line to `_prepare_deepspeed()`, it work. but, i have little knowledge on deepspeed. so, i don't know that is right solution.

plz check and modify it.🤗🤗🤗

**Comment by wen2cheng** [comment]
I also encountered a similar problem, can you describe your solution in detail

**Comment by wen2cheng** [comment]
I also encountered a similar problem, can you describe your solution in detail

**Comment by muximus3** [comment]
```python
dpo_trainer.ref_model = Accelerator().prepare(dpo_trainer.ref_model) # add this
dpo_trainer.train()
```
I fix this by adding one line before `train()`, before that I had to use 1 gpu with deepspeed to avoid that error. 
By the way I didn't padd ref_model to `DPOTrainer`

**Comment by ichsan2895** [comment]
> ```python
> dpo_trainer.ref_model = Accelerator().prepare(dpo_trainer.ref_model) # add this
> dpo_trainer.train()
> ```
> 
> I fix this by adding one line before `train()`, before that I had to use 1 GPU when using deepspeed to avoid that error. Also I didn't pass `ref_model` to `DPOTrainer`.

This solves my problem, thank you!

**Comment by lvwerra** [comment]
@kashif let's fix this in the `DPOTrainer` itself, no?
