### ISSUE TITLE
How do I use BetterTransformer with TRL?

### ISSUE THREAD

**Issue by larekrow** [huggingface/trl#768]
Converting the original model with `BetterTransformer.transform(model)` is fine, but I am getting this error when trying to `BetterTransformer.reverse(model)` before saving.

```
model = AutoModelForCausalLMWithValueHead.from_pretrained(
    ppo_config.model_name,
    torch_dtype=torch.bfloat16,
)
```

```
Traceback (most recent call last):
  File "/home/users/username/test_trl/src/trl_ft.py", line 177, in <module>
    finetune()
  File "/home/users/username/test_trl/src/trl_ft.py", line 168, in finetune
    model = BetterTransformer.reverse(model)
  File "/home/users/username/test_trl/venv/lib/python3.9/site-packages/optimum/bettertransformer/transformation.py", line 340, in reverse
    reversed_model = bt_model.__class__(config)
  File "/home/users/username/test_trl/venv/lib/python3.9/site-packages/trl/models/modeling_value_head.py", line 103, in __init__
    super().__init__(pretrained_model)
  File "/home/users/username/test_trl/venv/lib/python3.9/site-packages/trl/models/modeling_base.py", line 78, in __init__
    self.config = pretrained_model.config
  File "/home/users/username/test_trl/venv/lib/python3.9/site-packages/transformers/configuration_utils.py", line 261, in __getattribute__
    return super().__getattribute__(key)
AttributeError: 'LlamaConfig' object has no attribute 'config'
```

Any idea how to fix it?

**Comment by younesbelkada** [comment]
Hi @larekrow 
The correct approach here is to pass a `AutoModelForCausalLM` model that has been converted to BT format using `model.to_bettertransformer()` to `AutoModelForCausalLMWithValueHead`. After that note that there is no need to revert the model back as for decoder models BT does not change the state dict of the model.

**Comment by larekrow** [comment]
Thanks @younesbelkada!
