### ISSUE TITLE
RuntimeError: Tensors must be CUDA and dense  For tuning llama2-7b with ppo_trainer

### ISSUE THREAD

**Issue by Andcircle** [huggingface/trl#774]
I just follows the example, but using llama2 7b. When using single GPU (A100_80gb) it works, but when trying with mult-gpu (on the same node). It always give following error:

Update, tried falcon model got same error

```
Traceback (most recent call last):
  File "train/rl_train.py", line 358, in <module>
    stats = ppo_trainer.step(question_tensors, response_tensors, rewards)
  File "train/rl_train.py", line 358, in <module>
    stats = ppo_trainer.step(question_tensors, response_tensors, rewards)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/trl/trainer/ppo_trainer.py", line 788, in step
    stats = self.gather_stats(stats)
  File "/usr/local/lib/python3.8/dist-packages/trl/trainer/ppo_trainer.py", line 788, in step
    stats = self.gather_stats(stats)
  File "/usr/local/lib/python3.8/dist-packages/trl/trainer/ppo_trainer.py", line 865, in gather_stats
    dist.all_reduce(v, dist.ReduceOp.SUM)
  File "/usr/local/lib/python3.8/dist-packages/trl/trainer/ppo_trainer.py", line 865, in gather_stats
    dist.all_reduce(v, dist.ReduceOp.SUM)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py", line 1451, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py", line 1451, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py", line 1700, in all_reduce
    work = default_pg.allreduce([tensor], opts)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py", line 1700, in all_reduce
    work = default_pg.allreduce([tensor], opts)
  File "train/rl_train.py", line 358, in <module>
    stats = ppo_trainer.step(question_tensors, response_tensors, rewards)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
RuntimeError: Tensors must be CUDA and dense
```

**Comment by Andcircle** [comment]
when record stats, mean of score and std is in cpu instead of device, move to device solved the issue
