### ISSUE TITLE
DPO and accelerate

### ISSUE THREAD

**Issue by ValentinaPy** [huggingface/trl#801]
I am using the dpo_llama2.py script and I set up accelerate with accelerate config. When I then run the script with "accelerate launch dpo_llama2.py", I get the following error:

`RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn`

is that known error? What am I doing wrong?

**Comment by haoyuying** [comment]
I have the same problem, if you have solutions, please let me know, thx.

**Comment by haoyuying** [comment]
add ‘losses.requires_grad_(True)’ in https://github.com/huggingface/trl/blob/eb6aa204014fe52952a4702254a10a2b0ea23f0c/trl/trainer/dpo_trainer.py#L305       it works for me.

**Comment by ValentinaPy** [comment]
Thank you, that fixed it! (maybe it's worth suggesting this fix as a pull request? in case others are trying to run dpo with accelerate?)

**Comment by kashif** [comment]
no i never encountered it but since there were some refactorings to DPO, I need to double check

**Comment by vecorro** [comment]
Hi @lvwerra amd @kashif. The script also throws this error when using the accelerate launcher. Example 

Env setup 
Ubuntu 22.04, 
Python 3.10, 
CUDA 11.8, 
2 x A100 (40GB) GPU

Libraries:
transformers                 4.33.2
accelerate                    0.23.0
trl                           0.7.1
torch                         2.0.1
torchdata                     0.6.1
torchtext                     0.15.2+cpu

Runtime error:

```
accelerate launch trl/dpo_llama2.py --model_name_or_path="models/sft/final_checkpoint" --output_dir="models/dpo"

Traceback (most recent call last):
  File "/home/vmuser/llms/llama-2-hf/scripts/trl/dpo_llama2.py", line 218, in <module>
    dpo_trainer.train()
  File "/home/vmuser/miniconda3/envs/llm-env/lib/python3.10/site-packages/transformers/trainer.py", line 1553, in train
    return inner_training_loop(
  File "/home/vmuser/miniconda3/envs/llm-env/lib/python3.10/site-packages/transformers/trainer.py", line 1835, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/vmuser/miniconda3/envs/llm-env/lib/python3.10/site-packages/transformers/trainer.py", line 2690, in training_step
    self.accelerator.backward(loss)
  File "/home/vmuser/miniconda3/envs/llm-env/lib/python3.10/site-packages/accelerate/accelerator.py", line 1985, in backward
    loss.backward(**kwargs)
  File "/home/vmuser/miniconda3/envs/llm-env/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/vmuser/miniconda3/envs/llm-env/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
Traceback (most recent call last):
  File "/home/vmuser/llms/llama-2-hf/scripts/trl/dpo_llama2.py", line 218, in <module>
    dpo_trainer.train()
  File "/home/vmuser/miniconda3/envs/llm-env/lib/python3.10/site-packages/transformers/trainer.py", line 1553, in train
    return inner_training_loop(
  File "/home/vmuser/miniconda3/envs/llm-env/lib/python3.10/site-packages/transformers/trainer.py", line 1835, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/vmuser/miniconda3/envs/llm-env/lib/python3.10/site-packages/transformers/trainer.py", line 2690, in training_step
    self.accelerator.backward(loss)
  File "/home/vmuser/miniconda3/envs/llm-env/lib/python3.10/site-packages/accelerate/accelerator.py", line 1985, in backward
    loss.backward(**kwargs)
  File "/home/vmuser/miniconda3/envs/llm-env/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/vmuser/miniconda3/envs/llm-env/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn



```

**Comment by alex-ht** [comment]
> add ‘losses.requires_grad_(True)’ in
> 
> https://github.com/huggingface/trl/blob/eb6aa204014fe52952a4702254a10a2b0ea23f0c/trl/trainer/dpo_trainer.py#L305
> 
> it works for me.

I encountered a similar issue while implementing DPO. This modification can be executed, but the parameters won't update.

**Comment by YeonwooSung** [comment]
I was also faced with similar issue (had that error message when call the "SFTTrainer.train()" method), and was able to solve this issue by calling `model.enable_input_require_grads()` right after loading the pretrained model:

```
model = AutoModelForCausalLM.from_pretrained(
    args.model_name,
    quantization_config=bnb_config,
    device_map=device_map,
    trust_remote_code=True,
)
model.enable_input_require_grads()
```

After adding the `model.enable_input_require_grads()`,

**Comment by younesbelkada** [comment]
Hi everyone, I just pushed a fix on main: https://github.com/huggingface/trl/pull/927 that should fix the issue
Can you try that out and let me know if this fixes your issues?
