### ISSUE TITLE
Support for exporting XLA trained models

### ISSUE THREAD

**Issue by abatilo** [huggingface/trl#813]
If I train a Transformers model on Google TPU VMs, it appears that when I try to save the `SFTTrainer` models, that not everything I need gets included, I think?

```python
    model = AutoModelForCausalLM.from_pretrained("/trained/using/tpus")
    trainer = SFTTrainer(
        model,
        train_dataset=dataset,
        peft_config=lora_config,
    )

    train_result = trainer.train()
    trainer.save_model() # Gets saved to `/tmp/sft` based on `TrainingArguments.output_dir`
    trainer.model.save_pretrained("/tmp/sft-pretrained")
```

I've tried doing both `.save_model()` and `trainer.model.save_pretrained`.

If I try to load the directory created by `.save_model` directly I see:
```python
>>> AutoModelForCausalLM.from_pretrained("/tmp/sft")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ray/anaconda3/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 527, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/transformers/models/auto/configuration_auto.py", line 1023, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/transformers/configuration_utils.py", line 620, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/transformers/configuration_utils.py", line 675, in _get_config_dict
    resolved_config_file = cached_file(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/transformers/utils/hub.py", line 400, in cached_file
    raise EnvironmentError(
OSError: /tmp/sft does not appear to have a file named config.json. Checkout 'https://huggingface.co//tmp/sft/None' for available files.
```

If I try to load the adapter from calling `trainer.model.save_pretrained` then I see:
```python
>>> AutoModelForCausalLM.from_pretrained("/tmp/test-clm").load_adapter("/tmp/sft-pretrained")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ray/anaconda3/lib/python3.8/site-packages/transformers/integrations/peft.py", line 151, in load_adapter
    adapter_state_dict = load_peft_weights(peft_model_id, revision=revision, use_auth_token=token)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/peft/utils/save_and_load.py", line 198, in load_peft_weights
    adapters_weights = torch.load(filename, map_location=torch.device(device))
  File "/home/ray/anaconda3/lib/python3.8/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/torch/_utils.py", line 266, in _rebuild_device_tensor_from_numpy
    tensor = torch.from_numpy(data).to(dtype=dtype, device=device)
RuntimeError: tensorflow/compiler/xla/xla_client/computation_client.cc:280 : Missing XLA configuration
```
---
How should I be saving the model so that I can load it again later? Thank you in advance!

**Comment by steveepreston** [comment]
+1
Same problem
