### ISSUE TITLE
DPOTrainer throws error when streaming in load_dataset()

### ISSUE THREAD

**Issue by RitheshRn** [huggingface/trl#867]
Hi-

My env:
- 8 A100 (40gb)
- accelerate: v0.23.0
- transformers: v4.34.0

I am training DPO with stack-exchange dataset("lvwerra/stack-exchange-paired"), but because of memory constraints, I need to load the dataset in streaming mode(i.e. `streaming=True` in `load_dataset()`). The script throws the below error:

```
Traceback (most recent call last):
  File "/export/home/code/trl-main/examples/research_projects/stack_llama_2/scripts/dpo_llama2.py", line 288, in <module>
    dpo_trainer.train()
  File "/export/home/envs/trl/lib/python3.9/site-packages/transformers/trainer.py", line 1591, in train
    return inner_training_loop(
  File "/export/home/envs/trl/lib/python3.9/site-packages/transformers/trainer.py", line 1870, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/export/home/envs/trl/lib/python3.9/site-packages/accelerate/data_loader.py", line 560, in __iter__
    next_batch, next_batch_info = self._fetch_batches(main_iterator)
  File "/export/home/envs/trl/lib/python3.9/site-packages/accelerate/data_loader.py", line 524, in _fetch_batches
    batch = concatenate(batches, dim=0)
  File "/export/home/envs/trl/lib/python3.9/site-packages/accelerate/utils/operations.py", line 503, in concatenate
    return type(data[0])({k: concatenate([d[k] for d in data], dim=dim) for k in data[0].keys()})
  File "/export/home/envs/trl/lib/python3.9/site-packages/accelerate/utils/operations.py", line 503, in <dictcomp>
    return type(data[0])({k: concatenate([d[k] for d in data], dim=dim) for k in data[0].keys()})
  File "/export/home/envs/trl/lib/python3.9/site-packages/accelerate/utils/operations.py", line 506, in concatenate
    return torch.cat(data, dim=dim)
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 253 but got size 307 for tensor number 1 in the list.
```

I tried to run the exact same script with `streaming=False` on a smaller dataset("mychen76/stack-exchange-paired-500k") and the script ran with no issues. I believe object type i.e. **Dataset** vs **IterableDataset** is causing this issue. I did play around with different versions of accelerator and transformers but no luck. Any suggestions on how to resolve this?

**Comment by lvwerra** [comment]
Interesting, maybe there is an issue with the data collator since it seems that the samples can't be concatenated (and thus are maybe node padded properly). As a side note, I don't think the full dataset should use more memory since `datasets` uses memory mapping. So it should only use more storage but not more memory space.

**Comment by RitheshRn** [comment]
Similar issue discussed here: https://github.com/huggingface/accelerate/issues/2023
